import type { AppLocale } from "./locale";

export const en = {
  requestFailed: "BOOKPILE could not complete that request.",
  openingAccount: "Opening your account…",
  privateAccount: "Private account",
  yourProfile: "Your profile",
  profileIntro: "Choose what other signed-in BOOKPILE users can see. Email, security and storage details always remain private.",
  profileImage: "Profile image",
  yourProfileImage: "Your profile",
  chooseImage: "Choose image",
  remove: "Remove",
  whoCanSeeIt: "Who can see it?",
  aboutYou: "About you",
  name: "Name",
  nameHelp: "Shown only on your profile; BOOKPILE uses @{username} elsewhere.",
  timezone: "Timezone",
  notSpecified: "Not specified",
  city: "City",
  stateRegion: "State / region",
  country: "Country",
  dateOfBirth: "Date of birth",
  gender: "Gender",
  leaveBlank: "Leave blank",
  male: "Male",
  female: "Female",
  custom: "Custom",
  customGender: "Custom gender",
  preferredPronoun: "Preferred pronoun",
  neutral: "Neutral",
  neutralPronounText: "Neutral pronoun text",
  neutralPronounPlaceholder: "they",
  pronounVisibility: "Pronouns are visible to signed-in users even when Gender is private.",
  privacy: "Privacy",
  privacyHelp: "Personal data groups gender, location and date of birth. Pronouns remain visible to signed-in users.",
  fieldName: "Name",
  fieldTimezone: "Timezone",
  fieldPersonalData: "Personal data",
  visibilityPrivate: "Only me",
  visibilityLibrary: "People sharing a library",
  visibilityAuthenticated: "All BOOKPILE users",
  saving: "Saving…",
  saveProfile: "Save profile",
  profileSaved: "Your profile and privacy choices were saved.",
  imageUpdated: "Your private profile image was updated.",
  imageRemoved: "Your profile image was removed.",
  storage: "Storage",
  storageHelp: "Each colour shows how your used space is distributed. Shared-library storage is allocated across its Owners.",
  accountData: "Account data",
  accountDataStorageLabel: "Account data contribution to used storage",
  libraryStorageLabel: "{library}, contribution to used account storage",
  totalAccountStorage: "Total account storage",
  totalStorageLabel: "Total account storage used",
  account: "Account",
  username: "Username",
  registrationEmail: "Registration email",
  password: "Password",
  notSet: "Not set",
  memberSince: "Member since",
  language: "Language",
  languageHelp: "Your account preference follows you across devices and is used for account messages. Invitation messages can use a different language.",
  bookpileLanguage: "BOOKPILE language",
  languageSaved: "Your language preference was saved for this account.",
  inviteSomeone: "Invite someone to BOOKPILE",
  betaInvitationHelp: "Every three different days you use BOOKPILE earns one beta account invitation. Each day counts once, and your progress restarts after the third active day. Created invitations expire after seven days.",
  invitationProgressLabel: "{active} of {required} active days toward the next invitation",
  invitationProgress: "{active} of {required} active days toward your next invitation",
  invitationsReady: "ready to create",
  invitationsOpen: "created and still usable",
  invitationLanguage: "Invitation language",
  createAccountInvitation: "Create account invitation",
  invitationReady: "Your account invitation is ready. It is shown only in this session.",
  invitationMessage: "Invitation message",
  invitationLink: "Invitation link",
  copyMessage: "Copy message",
  copyLinkOnly: "Copy link only",
  copied: "{label} copied.",
  clipboardFailed: "BOOKPILE could not access the clipboard. Select and copy the visible link manually.",
  invitationExpires: "Expires {date}. For security, copy it now; BOOKPILE stores only its hash.",
  recentlyDeletedLibraries: "Recently deleted libraries",
  recoveryHelp: "Every former Owner may restore the complete library for 48 hours. Recovery is all-or-nothing and requires available shared storage.",
  recoverableUntil: "Recoverable until {date}",
  restore: "Restore",
  libraryRestored: "“{name}” and all its memberships were restored.",
  security: "Security",
  securityHelp: "Change your password or end signed-in sessions.",
  currentPassword: "Current password",
  newPassword: "New password",
  confirmNewPassword: "Confirm new password",
  changePassword: "Change password",
  passwordChanged: "Your password was changed. Other signed-in devices were disconnected.",
  signOut: "Sign out",
  signOutEverywhere: "Sign out everywhere",
  deleteAccount: "Delete account",
  completeRecovery: "Complete recovery",
  restoreLibraryTitle: "Restore “{name}”?",
  restoreLibraryHelp: "Books, covers, layout, readings, loans and every previous membership will return together.",
  yourCurrentPassword: "Your current password",
  cancel: "Cancel",
  restoring: "Restoring…",
  restoreLibrary: "Restore library",
  dangerZone: "Danger zone",
  deleteAccountTitle: "Delete your account?",
  deleteAccountHelp: "Your profile becomes invisible, every session is closed and your Viewer memberships are removed immediately. You must transfer or delete every library you own first. You may recover the complete account for 48 hours; after that your profile, personal readings and personal data are permanently erased.",
  typeUsername: "Type {username} exactly",
  deletionAcknowledgement: "I understand that account recovery expires after 48 hours.",
  deleting: "Deleting…",
  navControls: "BOOKPILE workspace controls",
  chooseLibrary: "Choose library",
  owner: "Owner",
  viewer: "Viewer",
  myProfile: "My profile",
  customizeLayout: "Customize layout",
  protectedSession: "Protected session",
  openPrivateProfile: "Open your private profile and account",
  yourLibraries: "Your libraries",
  closeLibraries: "Close libraries panel",
  viewerCatalogueMap: "Viewer · catalogue + map",
  viewerCatalogue: "Viewer · catalogue",
  noLibraries: "No libraries yet. Create your first one below.",
  librarySettings: "Library settings",
  librarySettingsHelp: "Members, physical structure and deletion",
  newLibraryName: "New library name",
  createLibrary: "Create library",
  libraryInvitation: "Library invitation link or token",
  joinLibrary: "Join library",
  viewPerspective: "View and reading perspective",
  closeViewPanel: "Close view and perspective panel",
  libraryView: "Library view",
  catalogue: "Catalogue",
  libraryMap: "Library Map",
  statistics: "Statistics",
  catalogueAndMap: "Catalogue and map",
  catalogueOnly: "Catalogue only",
  perspectiveHelp: "Choose whose personal reading data is represented. Other members' perspectives are read-only.",
  editablePerspective: "your editable perspective",
  readOnly: "read only",
  memberProfiles: "Member profiles",
  self: "self",
} as const;

export type AuthenticatedCopyKey = keyof typeof en;






const catalogues: Partial<Record<AppLocale, Record<AuthenticatedCopyKey, string>>> = { en };

export function registerAuthenticatedCatalogue(
  locale: AppLocale,
  catalogue: Record<AuthenticatedCopyKey, string>,
): void {
  catalogues[locale] = catalogue;
}

export function authenticatedCopy(locale: AppLocale) {
  const catalogue = catalogues[locale];
  if (!catalogue) throw new Error(`Locale catalogue not loaded: ${locale}`);
  return (key: AuthenticatedCopyKey, values: Record<string, string | number> = {}) =>
    catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) =>
      Object.hasOwn(values, name) ? String(values[name]) : token,
    );
}
