import type { AppLocale } from "./locale";

export const en = {
  requestFailed: "BOOKPILE could not complete that request.",
  openingAccount: "Opening your account…",
  privateAccount: "Private account",
  yourProfile: "Your profile",
  profileIntro: "Choose what other signed-in BOOKPILE users can see. Email, security and storage details always remain private.",
  profileImage: "Profile image",
  yourProfileImage: "Your profile",
  chooseImage: "Choose image",
  remove: "Remove",
  whoCanSeeIt: "Who can see it?",
  aboutYou: "About you",
  name: "Name",
  nameHelp: "Shown only on your profile; BOOKPILE uses @{username} elsewhere.",
  timezone: "Timezone",
  notSpecified: "Not specified",
  city: "City",
  stateRegion: "State / region",
  country: "Country",
  dateOfBirth: "Date of birth",
  gender: "Gender",
  leaveBlank: "Leave blank",
  male: "Male",
  female: "Female",
  custom: "Custom",
  customGender: "Custom gender",
  preferredPronoun: "Preferred pronoun",
  neutral: "Neutral",
  neutralPronounText: "Neutral pronoun text",
  neutralPronounPlaceholder: "they",
  pronounVisibility: "Pronouns are visible to signed-in users even when Gender is private.",
  privacy: "Privacy",
  privacyHelp: "Personal data groups gender, location and date of birth. Pronouns remain visible to signed-in users.",
  fieldName: "Name",
  fieldTimezone: "Timezone",
  fieldPersonalData: "Personal data",
  visibilityPrivate: "Only me",
  visibilityLibrary: "People sharing a library",
  visibilityAuthenticated: "All BOOKPILE users",
  saving: "Saving…",
  saveProfile: "Save profile",
  profileSaved: "Your profile and privacy choices were saved.",
  imageUpdated: "Your private profile image was updated.",
  imageRemoved: "Your profile image was removed.",
  storage: "Storage",
  storageHelp: "Each colour shows how your used space is distributed. Shared-library storage is allocated across its Owners.",
  accountData: "Account data",
  accountDataStorageLabel: "Account data contribution to used storage",
  libraryStorageLabel: "{library}, contribution to used account storage",
  totalAccountStorage: "Total account storage",
  totalStorageLabel: "Total account storage used",
  account: "Account",
  username: "Username",
  registrationEmail: "Registration email",
  password: "Password",
  notSet: "Not set",
  memberSince: "Member since",
  language: "Language",
  languageHelp: "Your account preference follows you across devices and is used for account messages. Invitation messages can use a different language.",
  bookpileLanguage: "BOOKPILE language",
  languageSaved: "Your language preference was saved for this account.",
  inviteSomeone: "Invite someone to BOOKPILE",
  betaInvitationHelp: "Every three different days you use BOOKPILE earns one beta account invitation. Each day counts once, and your progress restarts after the third active day. Created invitations expire after seven days.",
  invitationProgressLabel: "{active} of {required} active days toward the next invitation",
  invitationProgress: "{active} of {required} active days toward your next invitation",
  invitationsReady: "ready to create",
  invitationsOpen: "created and still usable",
  invitationLanguage: "Invitation language",
  createAccountInvitation: "Create account invitation",
  invitationReady: "Your account invitation is ready. It is shown only in this session.",
  invitationMessage: "Invitation message",
  invitationLink: "Invitation link",
  copyMessage: "Copy message",
  copyLinkOnly: "Copy link only",
  copied: "{label} copied.",
  clipboardFailed: "BOOKPILE could not access the clipboard. Select and copy the visible link manually.",
  invitationExpires: "Expires {date}. For security, copy it now; BOOKPILE stores only its hash.",
  recentlyDeletedLibraries: "Recently deleted libraries",
  recoveryHelp: "Every former Owner may restore the complete library for 48 hours. Recovery is all-or-nothing and requires available shared storage.",
  recoverableUntil: "Recoverable until {date}",
  restore: "Restore",
  libraryRestored: "“{name}” and all its memberships were restored.",
  security: "Security",
  securityHelp: "Change your password or end signed-in sessions.",
  currentPassword: "Current password",
  newPassword: "New password",
  confirmNewPassword: "Confirm new password",
  changePassword: "Change password",
  passwordChanged: "Your password was changed. Other signed-in devices were disconnected.",
  signOut: "Sign out",
  signOutEverywhere: "Sign out everywhere",
  deleteAccount: "Delete account",
  completeRecovery: "Complete recovery",
  restoreLibraryTitle: "Restore “{name}”?",
  restoreLibraryHelp: "Books, covers, layout, readings, loans and every previous membership will return together.",
  yourCurrentPassword: "Your current password",
  cancel: "Cancel",
  restoring: "Restoring…",
  restoreLibrary: "Restore library",
  dangerZone: "Danger zone",
  deleteAccountTitle: "Delete your account?",
  deleteAccountHelp: "Your profile becomes invisible, every session is closed and your Viewer memberships are removed immediately. You must transfer or delete every library you own first. You may recover the complete account for 48 hours; after that your profile, personal readings and personal data are permanently erased.",
  typeUsername: "Type {username} exactly",
  deletionAcknowledgement: "I understand that account recovery expires after 48 hours.",
  deleting: "Deleting…",
  navControls: "BOOKPILE workspace controls",
  chooseLibrary: "Choose library",
  owner: "Owner",
  viewer: "Viewer",
  myProfile: "My profile",
  customizeLayout: "Customize layout",
  protectedSession: "Protected session",
  openPrivateProfile: "Open your private profile and account",
  yourLibraries: "Your libraries",
  closeLibraries: "Close libraries panel",
  viewerCatalogueMap: "Viewer · catalogue + map",
  viewerCatalogue: "Viewer · catalogue",
  noLibraries: "No libraries yet. Create your first one below.",
  librarySettings: "Library settings",
  librarySettingsHelp: "Members, physical structure and deletion",
  newLibraryName: "New library name",
  createLibrary: "Create library",
  libraryInvitation: "Library invitation link or token",
  joinLibrary: "Join library",
  viewPerspective: "View and reading perspective",
  closeViewPanel: "Close view and perspective panel",
  libraryView: "Library view",
  catalogue: "Catalogue",
  libraryMap: "Library Map",
  statistics: "Statistics",
  catalogueAndMap: "Catalogue and map",
  catalogueOnly: "Catalogue only",
  perspectiveHelp: "Choose whose personal reading data is represented. Other members' perspectives are read-only.",
  editablePerspective: "your editable perspective",
  readOnly: "read only",
  memberProfiles: "Member profiles",
} as const;

export type AuthenticatedCopyKey = keyof typeof en;

const gl = {
  requestFailed: "BOOKPILE non puido completar esa solicitude.",
  openingAccount: "Abrindo a túa conta…",
  privateAccount: "Conta privada",
  yourProfile: "O teu perfil",
  profileIntro: "Escolle o que poden ver as outras persoas con sesión iniciada en BOOKPILE. O correo, a seguridade e os datos de almacenamento son sempre privados.",
  profileImage: "Imaxe do perfil",
  yourProfileImage: "O teu perfil",
  chooseImage: "Escoller imaxe",
  remove: "Eliminar",
  whoCanSeeIt: "Quen pode vela?",
  aboutYou: "Sobre ti",
  name: "Nome",
  nameHelp: "Só se mostra no teu perfil; BOOKPILE usa @{username} no resto da aplicación.",
  timezone: "Fuso horario",
  notSpecified: "Sen especificar",
  city: "Cidade",
  stateRegion: "Provincia / rexión",
  country: "País",
  dateOfBirth: "Data de nacemento",
  gender: "Xénero",
  leaveBlank: "Deixar en branco",
  male: "Masculino",
  female: "Feminino",
  custom: "Personalizado",
  customGender: "Xénero personalizado",
  preferredPronoun: "Pronome preferido",
  neutral: "Neutro",
  neutralPronounText: "Texto do pronome neutro",
  neutralPronounPlaceholder: "elu",
  pronounVisibility: "Os pronomes son visibles para as persoas con sesión iniciada aínda que o xénero sexa privado.",
  privacy: "Privacidade",
  privacyHelp: "Os datos persoais agrupan o xénero, a localización e a data de nacemento. Os pronomes seguen visibles para as persoas con sesión iniciada.",
  fieldName: "Nome",
  fieldTimezone: "Fuso horario",
  fieldPersonalData: "Datos persoais",
  visibilityPrivate: "Só eu",
  visibilityLibrary: "Persoas coas que comparto unha biblioteca",
  visibilityAuthenticated: "Todas as persoas usuarias de BOOKPILE",
  saving: "Gardando…",
  saveProfile: "Gardar perfil",
  profileSaved: "Gardáronse o teu perfil e as opcións de privacidade.",
  imageUpdated: "Actualizouse a túa imaxe de perfil privada.",
  imageRemoved: "Eliminouse a túa imaxe de perfil.",
  storage: "Almacenamento",
  storageHelp: "Cada cor mostra como se distribúe o espazo que usas. O almacenamento das bibliotecas compartidas repártese entre as persoas propietarias.",
  accountData: "Datos da conta",
  accountDataStorageLabel: "Contribución dos datos da conta ao almacenamento usado",
  libraryStorageLabel: "{library}, contribución ao almacenamento usado da conta",
  totalAccountStorage: "Almacenamento total da conta",
  totalStorageLabel: "Almacenamento total usado da conta",
  account: "Conta",
  username: "Nome de usuario",
  registrationEmail: "Correo de rexistro",
  password: "Contrasinal",
  notSet: "Sen establecer",
  memberSince: "Membro desde",
  language: "Idioma",
  languageHelp: "A preferencia da conta acompáñate entre dispositivos e úsase nas mensaxes da conta. Os convites poden usar outro idioma.",
  bookpileLanguage: "Idioma de BOOKPILE",
  languageSaved: "Gardouse a preferencia de idioma da túa conta.",
  inviteSomeone: "Convidar alguén a BOOKPILE",
  betaInvitationHelp: "Por cada tres días distintos nos que uses BOOKPILE gañas un convite para unha conta beta. Cada día conta unha vez e o progreso reiníciase despois do terceiro día activo. Os convites creados caducan aos sete días.",
  invitationProgressLabel: "{active} de {required} días activos para o seguinte convite",
  invitationProgress: "{active} de {required} días activos para o teu seguinte convite",
  invitationsReady: "dispoñibles para crear",
  invitationsOpen: "creados e aínda utilizables",
  invitationLanguage: "Idioma do convite",
  createAccountInvitation: "Crear convite para unha conta",
  invitationReady: "O convite para a conta está listo. Só se mostra nesta sesión.",
  invitationMessage: "Mensaxe do convite",
  invitationLink: "Ligazón do convite",
  copyMessage: "Copiar mensaxe",
  copyLinkOnly: "Copiar só a ligazón",
  copied: "Copiouse: {label}.",
  clipboardFailed: "BOOKPILE non puido acceder ao portapapeis. Selecciona e copia manualmente a ligazón visible.",
  invitationExpires: "Caduca o {date}. Por seguridade, cópiao agora; BOOKPILE só almacena o seu hash.",
  recentlyDeletedLibraries: "Bibliotecas eliminadas recentemente",
  recoveryHelp: "Calquera persoa que fose propietaria pode restaurar a biblioteca completa durante 48 horas. A recuperación é total e require espazo compartido dispoñible.",
  recoverableUntil: "Recuperable ata o {date}",
  restore: "Restaurar",
  libraryRestored: "Restauráronse «{name}» e todas as súas pertenzas.",
  security: "Seguridade",
  securityHelp: "Cambia o contrasinal ou pecha sesións iniciadas.",
  currentPassword: "Contrasinal actual",
  newPassword: "Contrasinal novo",
  confirmNewPassword: "Confirmar o contrasinal novo",
  changePassword: "Cambiar o contrasinal",
  passwordChanged: "Cambiouse o contrasinal. Desconectáronse os outros dispositivos.",
  signOut: "Pechar sesión",
  signOutEverywhere: "Pechar sesión en todas partes",
  deleteAccount: "Eliminar conta",
  completeRecovery: "Completar a recuperación",
  restoreLibraryTitle: "Restaurar «{name}»?",
  restoreLibraryHelp: "Os libros, as portadas, a disposición, as lecturas, os préstamos e todas as pertenzas anteriores volverán xuntos.",
  yourCurrentPassword: "O teu contrasinal actual",
  cancel: "Cancelar",
  restoring: "Restaurando…",
  restoreLibrary: "Restaurar biblioteca",
  dangerZone: "Zona de perigo",
  deleteAccountTitle: "Eliminar a túa conta?",
  deleteAccountHelp: "O teu perfil deixa de ser visible, péchanse todas as sesións e elimínanse de inmediato as túas pertenzas como visitante. Primeiro debes transferir ou eliminar todas as bibliotecas que posúas. Podes recuperar a conta completa durante 48 horas; despois elimínanse definitivamente o perfil, as lecturas persoais e os datos persoais.",
  typeUsername: "Escribe {username} exactamente",
  deletionAcknowledgement: "Entendo que a recuperación da conta caduca ás 48 horas.",
  deleting: "Eliminando…",
  navControls: "Controis do espazo de traballo de BOOKPILE",
  chooseLibrary: "Escoller biblioteca",
  owner: "Propietario/a",
  viewer: "Visitante",
  myProfile: "O meu perfil",
  customizeLayout: "Personalizar disposición",
  protectedSession: "Sesión protexida",
  openPrivateProfile: "Abrir o teu perfil e a túa conta privados",
  yourLibraries: "As túas bibliotecas",
  closeLibraries: "Pechar o panel de bibliotecas",
  viewerCatalogueMap: "Visitante · catálogo + mapa",
  viewerCatalogue: "Visitante · catálogo",
  noLibraries: "Aínda non hai bibliotecas. Crea a primeira aquí embaixo.",
  librarySettings: "Configuración da biblioteca",
  librarySettingsHelp: "Membros, estrutura física e eliminación",
  newLibraryName: "Nome da biblioteca nova",
  createLibrary: "Crear biblioteca",
  libraryInvitation: "Ligazón ou código do convite á biblioteca",
  joinLibrary: "Unirse á biblioteca",
  viewPerspective: "Vista e perspectiva de lectura",
  closeViewPanel: "Pechar o panel de vista e perspectiva",
  libraryView: "Vista da biblioteca",
  catalogue: "Catálogo",
  libraryMap: "Mapa da biblioteca",
  statistics: "Estatísticas",
  catalogueAndMap: "Catálogo e mapa",
  catalogueOnly: "Só catálogo",
  perspectiveHelp: "Escolle os datos persoais de lectura que se representan. As perspectivas doutras persoas son de só lectura.",
  editablePerspective: "a túa perspectiva editable",
  readOnly: "só lectura",
  memberProfiles: "Perfís dos membros",
} satisfies Record<AuthenticatedCopyKey, string>;

export const es = {
  requestFailed: "BOOKPILE no ha podido completar esa solicitud.",
  openingAccount: "Abriendo tu cuenta…",
  privateAccount: "Cuenta privada",
  yourProfile: "Tu perfil",
  profileIntro: "Elige qué pueden ver las demás personas con sesión iniciada en BOOKPILE. El correo, la seguridad y los datos de almacenamiento son siempre privados.",
  profileImage: "Imagen de perfil",
  yourProfileImage: "Tu perfil",
  chooseImage: "Elegir imagen",
  remove: "Eliminar",
  whoCanSeeIt: "¿Quién puede verla?",
  aboutYou: "Sobre ti",
  name: "Nombre",
  nameHelp: "Solo se muestra en tu perfil; BOOKPILE usa @{username} en el resto de la aplicación.",
  timezone: "Zona horaria",
  notSpecified: "Sin especificar",
  city: "Ciudad",
  stateRegion: "Provincia / región",
  country: "País",
  dateOfBirth: "Fecha de nacimiento",
  gender: "Género",
  leaveBlank: "Dejar en blanco",
  male: "Masculino",
  female: "Femenino",
  custom: "Personalizado",
  customGender: "Género personalizado",
  preferredPronoun: "Pronombre preferido",
  neutral: "Neutro",
  neutralPronounText: "Texto del pronombre neutro",
  neutralPronounPlaceholder: "elle",
  pronounVisibility: "Los pronombres son visibles para las personas con sesión iniciada aunque el género sea privado.",
  privacy: "Privacidad",
  privacyHelp: "Los datos personales agrupan el género, la ubicación y la fecha de nacimiento. Los pronombres siguen siendo visibles para las personas con sesión iniciada.",
  fieldName: "Nombre",
  fieldTimezone: "Zona horaria",
  fieldPersonalData: "Datos personales",
  visibilityPrivate: "Solo yo",
  visibilityLibrary: "Personas con las que comparto una biblioteca",
  visibilityAuthenticated: "Todas las personas usuarias de BOOKPILE",
  saving: "Guardando…",
  saveProfile: "Guardar perfil",
  profileSaved: "Se han guardado tu perfil y las opciones de privacidad.",
  imageUpdated: "Se ha actualizado tu imagen de perfil privada.",
  imageRemoved: "Se ha eliminado tu imagen de perfil.",
  storage: "Almacenamiento",
  storageHelp: "Cada color muestra cómo se distribuye el espacio que usas. El almacenamiento de las bibliotecas compartidas se reparte entre las personas propietarias.",
  accountData: "Datos de la cuenta",
  accountDataStorageLabel: "Contribución de los datos de la cuenta al almacenamiento usado",
  libraryStorageLabel: "{library}, contribución al almacenamiento usado de la cuenta",
  totalAccountStorage: "Almacenamiento total de la cuenta",
  totalStorageLabel: "Almacenamiento total usado de la cuenta",
  account: "Cuenta",
  username: "Nombre de usuario",
  registrationEmail: "Correo de registro",
  password: "Contraseña",
  notSet: "Sin establecer",
  memberSince: "Miembro desde",
  language: "Idioma",
  languageHelp: "La preferencia de la cuenta te acompaña entre dispositivos y se usa en los mensajes de la cuenta. Las invitaciones pueden usar otro idioma.",
  bookpileLanguage: "Idioma de BOOKPILE",
  languageSaved: "Se ha guardado la preferencia de idioma de tu cuenta.",
  inviteSomeone: "Invitar a alguien a BOOKPILE",
  betaInvitationHelp: "Por cada tres días distintos en los que uses BOOKPILE obtienes una invitación para una cuenta beta. Cada día cuenta una vez y el progreso se reinicia después del tercer día activo. Las invitaciones creadas caducan a los siete días.",
  invitationProgressLabel: "{active} de {required} días activos para la siguiente invitación",
  invitationProgress: "{active} de {required} días activos para tu siguiente invitación",
  invitationsReady: "disponibles para crear",
  invitationsOpen: "creadas y todavía utilizables",
  invitationLanguage: "Idioma de la invitación",
  createAccountInvitation: "Crear invitación para una cuenta",
  invitationReady: "La invitación para la cuenta está lista. Solo se muestra en esta sesión.",
  invitationMessage: "Mensaje de la invitación",
  invitationLink: "Enlace de la invitación",
  copyMessage: "Copiar mensaje",
  copyLinkOnly: "Copiar solo el enlace",
  copied: "Se ha copiado: {label}.",
  clipboardFailed: "BOOKPILE no ha podido acceder al portapapeles. Selecciona y copia manualmente el enlace visible.",
  invitationExpires: "Caduca el {date}. Por seguridad, cópiala ahora; BOOKPILE solo almacena su hash.",
  recentlyDeletedLibraries: "Bibliotecas eliminadas recientemente",
  recoveryHelp: "Cualquier persona que fuese propietaria puede restaurar la biblioteca completa durante 48 horas. La recuperación es total y requiere espacio compartido disponible.",
  recoverableUntil: "Recuperable hasta el {date}",
  restore: "Restaurar",
  libraryRestored: "Se han restaurado «{name}» y todas sus pertenencias.",
  security: "Seguridad",
  securityHelp: "Cambia la contraseña o cierra sesiones iniciadas.",
  currentPassword: "Contraseña actual",
  newPassword: "Contraseña nueva",
  confirmNewPassword: "Confirmar la contraseña nueva",
  changePassword: "Cambiar la contraseña",
  passwordChanged: "Se ha cambiado la contraseña. Se han desconectado los demás dispositivos.",
  signOut: "Cerrar sesión",
  signOutEverywhere: "Cerrar sesión en todas partes",
  deleteAccount: "Eliminar cuenta",
  completeRecovery: "Completar la recuperación",
  restoreLibraryTitle: "¿Restaurar «{name}»?",
  restoreLibraryHelp: "Los libros, las portadas, la disposición, las lecturas, los préstamos y todas las pertenencias anteriores volverán juntos.",
  yourCurrentPassword: "Tu contraseña actual",
  cancel: "Cancelar",
  restoring: "Restaurando…",
  restoreLibrary: "Restaurar biblioteca",
  dangerZone: "Zona de peligro",
  deleteAccountTitle: "¿Eliminar tu cuenta?",
  deleteAccountHelp: "Tu perfil deja de ser visible, se cierran todas las sesiones y se eliminan de inmediato tus pertenencias como visitante. Primero debes transferir o eliminar todas las bibliotecas que poseas. Puedes recuperar la cuenta completa durante 48 horas; después se eliminan definitivamente el perfil, las lecturas personales y los datos personales.",
  typeUsername: "Escribe {username} exactamente",
  deletionAcknowledgement: "Entiendo que la recuperación de la cuenta caduca a las 48 horas.",
  deleting: "Eliminando…",
  navControls: "Controles del espacio de trabajo de BOOKPILE",
  chooseLibrary: "Elegir biblioteca",
  owner: "Propietario/a",
  viewer: "Visitante",
  myProfile: "Mi perfil",
  customizeLayout: "Personalizar disposición",
  protectedSession: "Sesión protegida",
  openPrivateProfile: "Abrir tu perfil y tu cuenta privados",
  yourLibraries: "Tus bibliotecas",
  closeLibraries: "Cerrar el panel de bibliotecas",
  viewerCatalogueMap: "Visitante · catálogo + mapa",
  viewerCatalogue: "Visitante · catálogo",
  noLibraries: "Todavía no hay bibliotecas. Crea la primera aquí debajo.",
  librarySettings: "Configuración de la biblioteca",
  librarySettingsHelp: "Miembros, estructura física y eliminación",
  newLibraryName: "Nombre de la biblioteca nueva",
  createLibrary: "Crear biblioteca",
  libraryInvitation: "Enlace o código de invitación a la biblioteca",
  joinLibrary: "Unirse a la biblioteca",
  viewPerspective: "Vista y perspectiva de lectura",
  closeViewPanel: "Cerrar el panel de vista y perspectiva",
  libraryView: "Vista de la biblioteca",
  catalogue: "Catálogo",
  libraryMap: "Mapa de la biblioteca",
  statistics: "Estadísticas",
  catalogueAndMap: "Catálogo y mapa",
  catalogueOnly: "Solo catálogo",
  perspectiveHelp: "Elige los datos personales de lectura que se representan. Las perspectivas de otras personas son de solo lectura.",
  editablePerspective: "tu perspectiva editable",
  readOnly: "solo lectura",
  memberProfiles: "Perfiles de los miembros",
} satisfies Record<AuthenticatedCopyKey, string>;

const catalogues: Record<AppLocale, Record<AuthenticatedCopyKey, string>> = { en, gl, es };

export function authenticatedCopy(locale: AppLocale) {
  const catalogue = catalogues[locale];
  return (key: AuthenticatedCopyKey, values: Record<string, string | number> = {}) =>
    catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) =>
      Object.hasOwn(values, name) ? String(values[name]) : token,
    );
}
