import type { AppLocale } from "./locale";

const en = {
  serverUnavailable: "BOOKPILE could not reach the server. Please try again.",
  coverOf: "Cover of {title}",
  shelf: "Shelf",
  background: "Background",
  foreground: "Foreground",
  row: "Row",
  pile: "Pile",
  position: "Position",
  contributorRolesUnavailable: "Contributor roles are unavailable. Please reload and try again.",
  noSuggestedBooks: "No available pending books match the current catalogue filters.",
  privateCatalogue: "Private catalogue",
  sharedCatalogue: "Shared catalogue",
  yourBooks: "Your books",
  usersBooks: "{username}'s books",
  owner: "Owner",
  viewer: "Viewer",
  memberCount: "{count} members",
  book: "book",
  books: "books",
  match: "match",
  newRead: "New read",
  add: "Add",
  addSingleBook: "Add single book",
  batchAdd: "Batch add",
  scanSingleBarcode: "Scan single barcode",
  batchScan: "Batch scan",
  readingSuggestion: "Reading suggestion",
  another: "Another",
  startReading: "Start reading",
  closeSuggestion: "Close suggestion",
  readingSummary: "Catalogue reading summary",
  totalBooks: "Total books",
  waitingToRead: "Waiting to be read",
  currentlyReading: "Currently reading",
  read: "Read",
  searchPlaceholder: "Search title, author, contributor or series",
  searchCatalogue: "Search catalogue",
  sort: "Sort",
  sortCatalogue: "Sort catalogue",
  advancedSort: "Advanced sort",
  title: "Title",
  author: "Author",
  physicalLocation: "Physical location",
  advanced: "Advanced",
  languages: "Languages",
  originalLanguages: "Original languages",
  genres: "Genres",
  publishers: "Publishers",
  series: "Series",
  translation: "Translation",
  category: "Category",
  binding: "Binding",
  publicationType: "Publication type",
  unknown: "Unknown",
  original: "Original",
  translated: "Translated",
  fiction: "Fiction",
  nonFiction: "Non-fiction",
  hardcover: "Hardcover",
  paperback: "Paperback",
  flexibound: "Flexibound",
  spiral: "Spiral bound",
  stapled: "Stapled",
  other: "Other",
  conventionalBook: "Conventional book",
  comicGraphicNovel: "Comic / graphic novel",
  atlas: "Atlas",
  reference: "Reference",
  artPhotographyIllustrated: "Art / photography / illustrated",
  magazinePeriodical: "Magazine / periodical",
  seriesMembership: "Series membership",
  any: "Any",
  inSeries: "In a series",
  notInSeries: "Not in a series",
  authors: "Authors",
  singleAuthor: "Single author",
  multipleAuthors: "Multiple authors",
  minimumPages: "Minimum pages",
  maximumPages: "Maximum pages",
  yearField: "Year field",
  currentEdition: "Current edition",
  originalPublication: "Original publication",
  minimumYear: "Minimum year",
  maximumYear: "Maximum year",
  personalReadingState: "Personal reading state",
  pending: "Pending",
  activeReading: "Currently reading — any active reading",
  firstReading: "Reading — first time",
  rereadingNow: "Re-reading now",
  readInactive: "Read — not active",
  rereadingHistory: "Rereading history",
  hasBeenReread: "Has been reread",
  hasNotBeenReread: "Has not been reread",
  readingDate: "Reading date",
  readingStarted: "Reading started",
  finishedReading: "Finished reading",
  readingDateFrom: "Reading date from",
  readingDateTo: "Reading date to",
  loanHistory: "Loan history",
  currentlyOnLoan: "Currently on loan",
  overdue: "Overdue",
  everLoaned: "Ever loaned",
  neverLoaned: "Never loaned",
  borrowerContains: "Borrower contains",
  loanDate: "Loan date",
  loaned: "Loaned",
  expectedReturn: "Expected return",
  returned: "Returned",
  loanDateFrom: "Loan date from",
  loanDateTo: "Loan date to",
  sortBy: "Sort by",
  dateAdded: "Date added",
  lastUpdated: "Last updated",
  pages: "Pages",
  publisher: "Publisher",
  editionYear: "Edition year",
  originalYear: "Original year",
  acquisitionDate: "Acquisition date",
  loanedDate: "Loaned date",
  ascending: "Ascending",
  descending: "Descending",
  direction: "Direction",
  clear: "Clear",
  applyFilters: "Apply filters",
  onLoanTo: "On loan to {borrower}",
  onLoan: "On loan",
  returnsTo: "returns to {location}",
  beingRead: "Being read",
  noPhysicalLocation: "No physical location",
  pageCount: "{count} pages",
  noOptionalMetadata: "No optional metadata recorded",
  completeInformation: "Complete information",
  goodreadsReview: "{username}'s Goodreads review",
  myReading: "My reading",
  manageLoan: "Manage or return loan",
  loanBook: "Loan this book",
  editBookLocation: "Edit book and physical location",
  delete: "Delete",
  everyBookPlace: "A place for every book",
  buildPhysicalLibrary: "Build your physical library",
  mapOnboarding: "BOOKPILE's map connects every catalogue record to its real place. It is optional, but spending a few minutes defining your furniture, shelves and containers now will make adding and finding books much easier.",
  setUpMap: "Set up the Library Map",
  skipMap: "You can also skip this and add books directly whenever you prefer.",
  noBooksMatch: "No books match",
  tryAnotherFilter: "Try another page or filter.",
  noCatalogueRecords: "This library has no catalogue records yet.",
  cataloguePages: "Catalogue pages",
  previous: "Previous",
  next: "Next",
} as const;

export type CatalogueCopyKey = keyof typeof en;
export type CatalogueCopy = (key: CatalogueCopyKey, values?: Record<string, string | number>) => string;

const gl = {
  serverUnavailable: "BOOKPILE non puido conectar co servidor. Téntao de novo.",
  coverOf: "Portada de {title}",
  shelf: "Andel",
  background: "Fondo",
  foreground: "Fronte",
  row: "Fila",
  pile: "Pila",
  position: "Posición",
  contributorRolesUnavailable: "Os roles das persoas colaboradoras non están dispoñibles. Recarga a páxina e téntao de novo.",
  noSuggestedBooks: "Non hai libros pendentes e dispoñibles que coincidan cos filtros actuais do catálogo.",
  privateCatalogue: "Catálogo privado",
  sharedCatalogue: "Catálogo compartido",
  yourBooks: "Os teus libros",
  usersBooks: "Libros de {username}",
  owner: "Propietario/a",
  viewer: "Visitante",
  memberCount: "{count} membros",
  book: "libro",
  books: "libros",
  match: "coincidente",
  newRead: "Nova lectura",
  add: "Engadir",
  addSingleBook: "Engadir un libro",
  batchAdd: "Engadir varios",
  scanSingleBarcode: "Escanear un código de barras",
  batchScan: "Escanear varios",
  readingSuggestion: "Suxestión de lectura",
  another: "Outra",
  startReading: "Comezar a ler",
  closeSuggestion: "Pechar a suxestión",
  readingSummary: "Resumo de lecturas do catálogo",
  totalBooks: "Total de libros",
  waitingToRead: "Pendentes de lectura",
  currentlyReading: "En lectura",
  read: "Lidos",
  searchPlaceholder: "Buscar por título, autoría, colaboración ou serie",
  searchCatalogue: "Buscar no catálogo",
  sort: "Ordenar",
  sortCatalogue: "Ordenar o catálogo",
  advancedSort: "Orde avanzada",
  title: "Título",
  author: "Autoría",
  physicalLocation: "Localización física",
  advanced: "Avanzado",
  languages: "Idiomas",
  originalLanguages: "Idiomas orixinais",
  genres: "Xéneros",
  publishers: "Editoriais",
  series: "Series",
  translation: "Tradución",
  category: "Categoría",
  binding: "Encadernación",
  publicationType: "Tipo de publicación",
  unknown: "Descoñecida",
  original: "Orixinal",
  translated: "Traducida",
  fiction: "Ficción",
  nonFiction: "Non ficción",
  hardcover: "Tapa dura",
  paperback: "Tapa branda",
  flexibound: "Tapa flexible reforzada",
  spiral: "Espiral",
  stapled: "Grapado",
  other: "Outro",
  conventionalBook: "Libro convencional",
  comicGraphicNovel: "Banda deseñada / novela gráfica",
  atlas: "Atlas",
  reference: "Consulta",
  artPhotographyIllustrated: "Arte / fotografía / ilustrado",
  magazinePeriodical: "Revista / publicación periódica",
  seriesMembership: "Pertenza a unha serie",
  any: "Calquera",
  inSeries: "Nunha serie",
  notInSeries: "Fóra dunha serie",
  authors: "Autoría",
  singleAuthor: "Autoría única",
  multipleAuthors: "Autoría múltiple",
  minimumPages: "Mínimo de páxinas",
  maximumPages: "Máximo de páxinas",
  yearField: "Campo de ano",
  currentEdition: "Edición actual",
  originalPublication: "Publicación orixinal",
  minimumYear: "Ano mínimo",
  maximumYear: "Ano máximo",
  personalReadingState: "Estado persoal de lectura",
  pending: "Pendente",
  activeReading: "En lectura — calquera lectura activa",
  firstReading: "En lectura — primeira vez",
  rereadingNow: "En relectura agora",
  readInactive: "Lido — sen lectura activa",
  rereadingHistory: "Historial de relecturas",
  hasBeenReread: "Foi relido",
  hasNotBeenReread: "Non foi relido",
  readingDate: "Data de lectura",
  readingStarted: "Inicio da lectura",
  finishedReading: "Fin da lectura",
  readingDateFrom: "Data de lectura desde",
  readingDateTo: "Data de lectura ata",
  loanHistory: "Historial de préstamos",
  currentlyOnLoan: "Prestado actualmente",
  overdue: "Atrasado",
  everLoaned: "Prestado algunha vez",
  neverLoaned: "Nunca prestado",
  borrowerContains: "O nome de quen o ten contén",
  loanDate: "Data do préstamo",
  loaned: "Prestado",
  expectedReturn: "Devolución prevista",
  returned: "Devolto",
  loanDateFrom: "Data do préstamo desde",
  loanDateTo: "Data do préstamo ata",
  sortBy: "Ordenar por",
  dateAdded: "Data de alta",
  lastUpdated: "Última actualización",
  pages: "Páxinas",
  publisher: "Editorial",
  editionYear: "Ano da edición",
  originalYear: "Ano orixinal",
  acquisitionDate: "Data de adquisición",
  loanedDate: "Data do préstamo",
  ascending: "Ascendente",
  descending: "Descendente",
  direction: "Dirección",
  clear: "Limpar",
  applyFilters: "Aplicar filtros",
  onLoanTo: "Prestado a {borrower}",
  onLoan: "Prestado",
  returnsTo: "volve a {location}",
  beingRead: "En lectura",
  noPhysicalLocation: "Sen localización física",
  pageCount: "{count} páxinas",
  noOptionalMetadata: "Non se rexistraron metadatos opcionais",
  completeInformation: "Información completa",
  goodreadsReview: "Recensión de {username} en Goodreads",
  myReading: "A miña lectura",
  manageLoan: "Xestionar ou devolver o préstamo",
  loanBook: "Prestar este libro",
  editBookLocation: "Editar o libro e a localización física",
  delete: "Eliminar",
  everyBookPlace: "Un lugar para cada libro",
  buildPhysicalLibrary: "Constrúe a túa biblioteca física",
  mapOnboarding: "O mapa de BOOKPILE conecta cada rexistro do catálogo co seu lugar real. É opcional, pero dedicar uns minutos a definir os mobles, andeis e contedores facilitará moito engadir e atopar libros.",
  setUpMap: "Configurar o mapa da biblioteca",
  skipMap: "Tamén podes omitir este paso e engadir libros directamente cando queiras.",
  noBooksMatch: "Non hai libros coincidentes",
  tryAnotherFilter: "Proba outra páxina ou outro filtro.",
  noCatalogueRecords: "Esta biblioteca aínda non ten rexistros no catálogo.",
  cataloguePages: "Páxinas do catálogo",
  previous: "Anterior",
  next: "Seguinte",
} satisfies Record<CatalogueCopyKey, string>;

const catalogues: Record<AppLocale, Record<CatalogueCopyKey, string>> = { en, gl };

export function catalogueCopy(locale: AppLocale): CatalogueCopy {
  const catalogue = catalogues[locale];
  return (key, values = {}) => catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) =>
    Object.hasOwn(values, name) ? String(values[name]) : token,
  );
}
