import type { AppLocale } from "./locale";
import { cataloguePt } from "./locales/pt/catalogue";
import { catalogueCa } from "./locales/ca/catalogue";

export const en = {
  serverUnavailable: "BOOKPILE could not reach the server. Please try again.",
  coverOf: "Cover of {title}",
  shelf: "Shelf",
  background: "Background",
  foreground: "Foreground",
  row: "Row",
  pile: "Pile",
  position: "Position",
  contributorRolesUnavailable: "Contributor roles are unavailable. Please reload and try again.",
  noSuggestedBooks: "No available pending books match the current catalogue filters.",
  privateCatalogue: "Private catalogue",
  sharedCatalogue: "Shared catalogue",
  yourBooks: "Your books",
  usersBooks: "{username}'s books",
  owner: "Owner",
  viewer: "Viewer",
  memberCount: "{count} members",
  book: "book",
  books: "books",
  match: "match",
  newRead: "New read",
  add: "Add",
  addSingleBook: "Add single book",
  batchAdd: "Batch add",
  scanSingleBarcode: "Scan single barcode",
  batchScan: "Batch scan",
  readingSuggestion: "Reading suggestion",
  another: "Another",
  startReading: "Start reading",
  closeSuggestion: "Close suggestion",
  readingSummary: "Catalogue reading summary",
  totalBooks: "Total books",
  waitingToRead: "Waiting to be read",
  currentlyReading: "Currently reading",
  read: "Read",
  searchPlaceholder: "Search title, author, contributor or series",
  searchCatalogue: "Search catalogue",
  sort: "Sort",
  sortCatalogue: "Sort catalogue",
  advancedSort: "Advanced sort",
  title: "Title",
  author: "Author",
  physicalLocation: "Physical location",
  advanced: "Advanced",
  languages: "Languages",
  originalLanguages: "Original languages",
  genres: "Genres",
  publishers: "Publishers",
  series: "Series",
  translation: "Translation",
  category: "Category",
  binding: "Binding",
  publicationType: "Publication type",
  unknown: "Unknown",
  original: "Original",
  translated: "Translated",
  fiction: "Fiction",
  nonFiction: "Non-fiction",
  hardcover: "Hardcover",
  paperback: "Paperback",
  flexibound: "Flexibound",
  spiral: "Spiral bound",
  stapled: "Stapled",
  other: "Other",
  conventionalBook: "Conventional book",
  comicGraphicNovel: "Comic / graphic novel",
  atlas: "Atlas",
  reference: "Reference",
  artPhotographyIllustrated: "Art / photography / illustrated",
  magazinePeriodical: "Magazine / periodical",
  seriesMembership: "Series membership",
  any: "Any",
  inSeries: "In a series",
  notInSeries: "Not in a series",
  authors: "Authors",
  singleAuthor: "Single author",
  multipleAuthors: "Multiple authors",
  minimumPages: "Minimum pages",
  maximumPages: "Maximum pages",
  yearField: "Year field",
  currentEdition: "Current edition",
  originalPublication: "Original publication",
  minimumYear: "Minimum year",
  maximumYear: "Maximum year",
  personalReadingState: "Personal reading state",
  pending: "Pending",
  activeReading: "Currently reading — any active reading",
  firstReading: "Reading — first time",
  rereadingNow: "Re-reading now",
  readInactive: "Read — not active",
  rereadingHistory: "Rereading history",
  hasBeenReread: "Has been reread",
  hasNotBeenReread: "Has not been reread",
  readingDate: "Reading date",
  readingStarted: "Reading started",
  finishedReading: "Finished reading",
  readingDateFrom: "Reading date from",
  readingDateTo: "Reading date to",
  loanHistory: "Loan history",
  currentlyOnLoan: "Currently on loan",
  overdue: "Overdue",
  everLoaned: "Ever loaned",
  neverLoaned: "Never loaned",
  borrowerContains: "Borrower contains",
  loanDate: "Loan date",
  loaned: "Loaned",
  expectedReturn: "Expected return",
  returned: "Returned",
  loanDateFrom: "Loan date from",
  loanDateTo: "Loan date to",
  sortBy: "Sort by",
  dateAdded: "Date added",
  lastUpdated: "Last updated",
  pages: "Pages",
  publisher: "Publisher",
  editionYear: "Edition year",
  originalYear: "Original year",
  acquisitionDate: "Acquisition date",
  loanedDate: "Loaned date",
  ascending: "Ascending",
  descending: "Descending",
  direction: "Direction",
  clear: "Clear",
  applyFilters: "Apply filters",
  onLoanTo: "On loan to {borrower}",
  onLoan: "On loan",
  returnsTo: "returns to {location}",
  beingRead: "Being read",
  noPhysicalLocation: "No physical location",
  pageCount: "{count} pages",
  noOptionalMetadata: "No optional metadata recorded",
  completeInformation: "Complete information",
  goodreadsReview: "{username}'s Goodreads review",
  myReading: "My reading",
  manageLoan: "Manage or return loan",
  loanBook: "Loan this book",
  editBookLocation: "Edit book and physical location",
  delete: "Delete",
  everyBookPlace: "A place for every book",
  buildPhysicalLibrary: "Build your physical library",
  mapOnboarding: "BOOKPILE's map connects every catalogue record to its real place. It is optional, but spending a few minutes defining your furniture, shelves and containers now will make adding and finding books much easier.",
  setUpMap: "Set up the Library Map",
  skipMap: "You can also skip this and add books directly whenever you prefer.",
  noBooksMatch: "No books match",
  tryAnotherFilter: "Try another page or filter.",
  noCatalogueRecords: "This library has no catalogue records yet.",
  cataloguePages: "Catalogue pages",
  previous: "Previous",
  next: "Next",
  close: "Close", readOnlyRecord: "Read-only catalogue record", contributors: "Contributors", selectedOwner: "Selected Owner", notRecorded: "Not recorded", editBook: "Edit book",
  subtitle: "Subtitle", isbn10: "ISBN-10", isbn13: "ISBN-13", currentEditionYear: "Current edition year", originalPublicationYear: "Original publication year", language: "Language", originalLanguage: "Original language", edition: "Edition", seriesVolume: "Series volume", acquired: "Acquired", originalCollection: "Original collection", height: "Height", width: "Width", thickness: "Thickness", notes: "Notes",
  chooseTransferValues: "Choose the values to transfer", transferNoneAutomatic: "Nothing is selected or saved automatically.", applyMetadata: "Apply selected metadata",
  batchCataloguing: "Batch cataloguing", sharedRecord: "Shared catalogue record", addNextBook: "Add the next book", addBook: "Add a book", batchCountOne: "{count} book added in this batch.", batchCountMany: "{count} books added in this batch.", batchHelp: "After saving, BOOKPILE clears the book data but retains this container and suggests the next position.",
  identifyIsbn: "Identify by ISBN or barcode", barcodePrivacy: "The barcode photograph is decoded on this device and immediately discarded. Review provider values before transferring them.", enterIsbn: "Enter or scan an ISBN first.", lookingUp: "Looking up…", lookupIsbn: "Look up ISBN", readingPhoto: "Reading photo…", takeBarcodePhoto: "Take barcode photo", isbnAlreadyPresent: "This ISBN is already in this library", noBibliographicRecord: "No bibliographic record was found. You can continue manually.",
  requiredInformation: "Required information", titleRequired: "Title *", authorDisplayRequired: "Author display *", privateCover: "Private cover image", coverPrivacy: "Visible only to signed-in members of this library. BOOKPILE discards the original after removing metadata and creating a private WebP copy.", storedCover: "Stored private cover", noCover: "No cover selected", chooseCover: "Take or choose cover", removeCover: "Remove cover", keepCover: "Keep existing cover",
  contributorHelp: "Add authors, translators, illustrators and other credited roles in display order.", contributorName: "Contributor name", moveUp: "Move up", moveDown: "Move down", removeContributor: "Remove contributor", addContributor: "Add contributor",
  editionClassification: "Edition and classification", editionNumber: "Edition number", commaSeparated: "Comma-separated", languageTranslation: "Language and translation", translationStatus: "Translation status", originalLanguageValue: "Original language", identifiers: "Identifiers", copyDetails: "Copy details",
  physicalLocationHelp: "Optional. An occupied position makes room automatically; moving a book compacts its previous container.", bookcase: "Bookcase", chooseShelf: "Choose shelf", container: "Container", chooseContainer: "Choose container", libraryNotes: "Library notes",
  optional: "optional", initialReadingHelp: "Add your own reading record and Goodreads review while creating this shared catalogue record. These values are personal and are cleared before the next Batch Add book.", readingRecord: "Reading record", noReadingRecord: "No reading record", historicalCompleted: "Historical reading — completed", activeStarted: "Currently reading — started", readingDatesUnknown: "Reading dates unknown", started: "Started", finished: "Finished", goodreadsUrl: "My Goodreads review URL",
  currentLoan: "Current loan", copyCurrentlyLoaned: "This physical copy is currently on loan", retainedPositionHelp: "The retained shelf position is preserved while the copy appears in the shared On loan area.", loanedToRequired: "Loaned to *", loanDateLabel: "Loan date", optionalUnknown: "optional / unknown", expectedReturnLabel: "Expected return", privateOwnerNotes: "Private Owner notes",
  processingPhotoHelp: "Large phone photos can take several seconds. Please keep this window open.", finishBatch: "Finish batch", cancel: "Cancel", pleaseWait: "Please wait…", saveScanNext: "Save and scan next", saveAddNext: "Save and add next", saveBook: "Save book",
  barcodeReadingLocally: "Reading the barcode locally…", checkingSources: "Checking bibliographic sources and this library…", selectedCoverPreview: "Selected cover preview", loanReadingConflict: "A copy cannot be on loan and actively read at the same time.",
  processingCover: "Processing private cover…", removingCover: "Removing private cover…", savingGoodreads: "Saving your Goodreads review…", savingReadingHistory: "Saving your reading history…", startingReading: "Starting your reading…",
  partialSave: "The shared book and location were saved, but some private cover or personal reading data was not. {error} Correct it and retry: BOOKPILE will update this book rather than create a duplicate.", savedNext: "“{title}” saved. Ready for the next book.", bookSaved: "Book and private cover saved.", bookUpdated: "Book updated.", deleteBookConfirm: "Permanently delete “{title}”? This cannot be undone.", bookDeleted: "Book permanently deleted.", personalDataUpdated: "Personal reading data updated.", loanDataUpdated: "Shared loan data updated.",
} as const;

export type CatalogueCopyKey = keyof typeof en;
export type CatalogueCopy = (key: CatalogueCopyKey, values?: Record<string, string | number>) => string;

const gl = {
  serverUnavailable: "BOOKPILE non puido conectar co servidor. Téntao de novo.",
  coverOf: "Portada de {title}",
  shelf: "Andel",
  background: "Fondo",
  foreground: "Fronte",
  row: "Fila",
  pile: "Pila",
  position: "Posición",
  contributorRolesUnavailable: "Os roles das persoas colaboradoras non están dispoñibles. Recarga a páxina e téntao de novo.",
  noSuggestedBooks: "Non hai libros pendentes e dispoñibles que coincidan cos filtros actuais do catálogo.",
  privateCatalogue: "Catálogo privado",
  sharedCatalogue: "Catálogo compartido",
  yourBooks: "Os teus libros",
  usersBooks: "Libros de {username}",
  owner: "Propietario/a",
  viewer: "Visitante",
  memberCount: "{count} membros",
  book: "libro",
  books: "libros",
  match: "coincidente",
  newRead: "Nova lectura",
  add: "Engadir",
  addSingleBook: "Engadir un libro",
  batchAdd: "Engadir varios",
  scanSingleBarcode: "Escanear un código de barras",
  batchScan: "Escanear varios",
  readingSuggestion: "Suxestión de lectura",
  another: "Outra",
  startReading: "Comezar a ler",
  closeSuggestion: "Pechar a suxestión",
  readingSummary: "Resumo de lecturas do catálogo",
  totalBooks: "Total de libros",
  waitingToRead: "Pendentes de lectura",
  currentlyReading: "En lectura",
  read: "Lidos",
  searchPlaceholder: "Buscar por título, autoría, colaboración ou serie",
  searchCatalogue: "Buscar no catálogo",
  sort: "Ordenar",
  sortCatalogue: "Ordenar o catálogo",
  advancedSort: "Orde avanzada",
  title: "Título",
  author: "Autoría",
  physicalLocation: "Localización física",
  advanced: "Avanzado",
  languages: "Idiomas",
  originalLanguages: "Idiomas orixinais",
  genres: "Xéneros",
  publishers: "Editoriais",
  series: "Series",
  translation: "Tradución",
  category: "Categoría",
  binding: "Encadernación",
  publicationType: "Tipo de publicación",
  unknown: "Descoñecida",
  original: "Orixinal",
  translated: "Traducida",
  fiction: "Ficción",
  nonFiction: "Non ficción",
  hardcover: "Tapa dura",
  paperback: "Tapa branda",
  flexibound: "Tapa flexible reforzada",
  spiral: "Espiral",
  stapled: "Grapado",
  other: "Outro",
  conventionalBook: "Libro convencional",
  comicGraphicNovel: "Banda deseñada / novela gráfica",
  atlas: "Atlas",
  reference: "Consulta",
  artPhotographyIllustrated: "Arte / fotografía / ilustrado",
  magazinePeriodical: "Revista / publicación periódica",
  seriesMembership: "Pertenza a unha serie",
  any: "Calquera",
  inSeries: "Nunha serie",
  notInSeries: "Fóra dunha serie",
  authors: "Autoría",
  singleAuthor: "Autoría única",
  multipleAuthors: "Autoría múltiple",
  minimumPages: "Mínimo de páxinas",
  maximumPages: "Máximo de páxinas",
  yearField: "Campo de ano",
  currentEdition: "Edición actual",
  originalPublication: "Publicación orixinal",
  minimumYear: "Ano mínimo",
  maximumYear: "Ano máximo",
  personalReadingState: "Estado persoal de lectura",
  pending: "Pendente",
  activeReading: "En lectura — calquera lectura activa",
  firstReading: "En lectura — primeira vez",
  rereadingNow: "En relectura agora",
  readInactive: "Lido — sen lectura activa",
  rereadingHistory: "Historial de relecturas",
  hasBeenReread: "Foi relido",
  hasNotBeenReread: "Non foi relido",
  readingDate: "Data de lectura",
  readingStarted: "Inicio da lectura",
  finishedReading: "Fin da lectura",
  readingDateFrom: "Data de lectura desde",
  readingDateTo: "Data de lectura ata",
  loanHistory: "Historial de préstamos",
  currentlyOnLoan: "Prestado actualmente",
  overdue: "Atrasado",
  everLoaned: "Prestado algunha vez",
  neverLoaned: "Nunca prestado",
  borrowerContains: "O nome de quen o ten contén",
  loanDate: "Data do préstamo",
  loaned: "Prestado",
  expectedReturn: "Devolución prevista",
  returned: "Devolto",
  loanDateFrom: "Data do préstamo desde",
  loanDateTo: "Data do préstamo ata",
  sortBy: "Ordenar por",
  dateAdded: "Data de alta",
  lastUpdated: "Última actualización",
  pages: "Páxinas",
  publisher: "Editorial",
  editionYear: "Ano da edición",
  originalYear: "Ano orixinal",
  acquisitionDate: "Data de adquisición",
  loanedDate: "Data do préstamo",
  ascending: "Ascendente",
  descending: "Descendente",
  direction: "Dirección",
  clear: "Limpar",
  applyFilters: "Aplicar filtros",
  onLoanTo: "Prestado a {borrower}",
  onLoan: "Prestado",
  returnsTo: "volve a {location}",
  beingRead: "En lectura",
  noPhysicalLocation: "Sen localización física",
  pageCount: "{count} páxinas",
  noOptionalMetadata: "Non se rexistraron metadatos opcionais",
  completeInformation: "Información completa",
  goodreadsReview: "Recensión de {username} en Goodreads",
  myReading: "A miña lectura",
  manageLoan: "Xestionar ou devolver o préstamo",
  loanBook: "Prestar este libro",
  editBookLocation: "Editar o libro e a localización física",
  delete: "Eliminar",
  everyBookPlace: "Un lugar para cada libro",
  buildPhysicalLibrary: "Constrúe a túa biblioteca física",
  mapOnboarding: "O mapa de BOOKPILE conecta cada rexistro do catálogo co seu lugar real. É opcional, pero dedicar uns minutos a definir os mobles, andeis e contedores facilitará moito engadir e atopar libros.",
  setUpMap: "Configurar o mapa da biblioteca",
  skipMap: "Tamén podes omitir este paso e engadir libros directamente cando queiras.",
  noBooksMatch: "Non hai libros coincidentes",
  tryAnotherFilter: "Proba outra páxina ou outro filtro.",
  noCatalogueRecords: "Esta biblioteca aínda non ten rexistros no catálogo.",
  cataloguePages: "Páxinas do catálogo",
  previous: "Anterior",
  next: "Seguinte",
  close: "Pechar", readOnlyRecord: "Rexistro do catálogo de só lectura", contributors: "Persoas colaboradoras", selectedOwner: "Persoa propietaria seleccionada", notRecorded: "Sen rexistrar", editBook: "Editar libro",
  subtitle: "Subtítulo", isbn10: "ISBN-10", isbn13: "ISBN-13", currentEditionYear: "Ano da edición actual", originalPublicationYear: "Ano da publicación orixinal", language: "Idioma", originalLanguage: "Idioma orixinal", edition: "Edición", seriesVolume: "Volume da serie", acquired: "Adquirido", originalCollection: "Colección orixinal", height: "Altura", width: "Largura", thickness: "Grosor", notes: "Notas",
  chooseTransferValues: "Escolle os valores que queres transferir", transferNoneAutomatic: "Non se selecciona nin se garda nada automaticamente.", applyMetadata: "Aplicar os metadatos seleccionados",
  batchCataloguing: "Catalogación por lotes", sharedRecord: "Rexistro do catálogo compartido", addNextBook: "Engadir o seguinte libro", addBook: "Engadir un libro", batchCountOne: "Engadiuse {count} libro neste lote.", batchCountMany: "Engadíronse {count} libros neste lote.", batchHelp: "Despois de gardar, BOOKPILE limpa os datos do libro, conserva este contedor e suxire a posición seguinte.",
  identifyIsbn: "Identificar mediante ISBN ou código de barras", barcodePrivacy: "A fotografía do código de barras descodifícase neste dispositivo e elimínase de inmediato. Revisa os valores do provedor antes de transferilos.", enterIsbn: "Introduce ou escanea primeiro un ISBN.", lookingUp: "Buscando…", lookupIsbn: "Buscar ISBN", readingPhoto: "Lendo a foto…", takeBarcodePhoto: "Fotografar o código", isbnAlreadyPresent: "Este ISBN xa está nesta biblioteca", noBibliographicRecord: "Non se atopou ningún rexistro bibliográfico. Podes continuar manualmente.",
  requiredInformation: "Información obrigatoria", titleRequired: "Título *", authorDisplayRequired: "Autoría mostrada *", privateCover: "Imaxe privada da portada", coverPrivacy: "Só é visible para os membros da biblioteca con sesión iniciada. BOOKPILE elimina o orixinal despois de retirar os metadatos e crear unha copia WebP privada.", storedCover: "Portada privada gardada", noCover: "Non se seleccionou unha portada", chooseCover: "Fotografar ou escoller portada", removeCover: "Eliminar portada", keepCover: "Conservar a portada existente",
  contributorHelp: "Engade autoría, tradución, ilustración e outros roles acreditados na orde de presentación.", contributorName: "Nome da persoa colaboradora", moveUp: "Subir", moveDown: "Baixar", removeContributor: "Eliminar persoa colaboradora", addContributor: "Engadir persoa colaboradora",
  editionClassification: "Edición e clasificación", editionNumber: "Número de edición", commaSeparated: "Separados por comas", languageTranslation: "Idioma e tradución", translationStatus: "Estado da tradución", originalLanguageValue: "Idioma orixinal", identifiers: "Identificadores", copyDetails: "Datos do exemplar",
  physicalLocationHelp: "Opcional. Unha posición ocupada fai sitio automaticamente; ao mover un libro compáctase o contedor anterior.", bookcase: "Moble", chooseShelf: "Escoller andel", container: "Contedor", chooseContainer: "Escoller contedor", libraryNotes: "Notas da biblioteca",
  optional: "opcional", initialReadingHelp: "Engade o teu rexistro de lectura e a recensión de Goodreads ao crear este rexistro compartido. Estes valores son persoais e límpanse antes do seguinte libro do lote.", readingRecord: "Rexistro de lectura", noReadingRecord: "Sen rexistro de lectura", historicalCompleted: "Lectura histórica — rematada", activeStarted: "En lectura — comezada", readingDatesUnknown: "Datas de lectura descoñecidas", started: "Comezada", finished: "Rematada", goodreadsUrl: "URL da miña recensión en Goodreads",
  currentLoan: "Préstamo actual", copyCurrentlyLoaned: "Este exemplar físico está prestado actualmente", retainedPositionHelp: "A posición reservada no andel consérvase mentres o exemplar aparece na zona compartida de préstamos.", loanedToRequired: "Prestado a *", loanDateLabel: "Data do préstamo", optionalUnknown: "opcional / descoñecida", expectedReturnLabel: "Devolución prevista", privateOwnerNotes: "Notas privadas das persoas propietarias",
  processingPhotoHelp: "As fotos grandes do móbil poden tardar varios segundos. Mantén esta xanela aberta.", finishBatch: "Rematar lote", cancel: "Cancelar", pleaseWait: "Agarda…", saveScanNext: "Gardar e escanear o seguinte", saveAddNext: "Gardar e engadir o seguinte", saveBook: "Gardar libro",
  barcodeReadingLocally: "Lendo o código de barras no dispositivo…", checkingSources: "Consultando as fontes bibliográficas e esta biblioteca…", selectedCoverPreview: "Vista previa da portada seleccionada", loanReadingConflict: "Un exemplar non pode estar prestado e en lectura activa ao mesmo tempo.",
  processingCover: "Procesando a portada privada…", removingCover: "Eliminando a portada privada…", savingGoodreads: "Gardando a túa recensión de Goodreads…", savingReadingHistory: "Gardando o teu historial de lectura…", startingReading: "Iniciando a túa lectura…",
  partialSave: "Gardáronse o libro compartido e a localización, pero non se puideron gardar algúns datos privados da portada ou da lectura. {error} Corríxeos e téntao de novo: BOOKPILE actualizará este libro en vez de crear un duplicado.", savedNext: "Gardouse «{title}». Todo listo para o seguinte libro.", bookSaved: "Gardáronse o libro e a portada privada.", bookUpdated: "Actualizouse o libro.", deleteBookConfirm: "Eliminar definitivamente «{title}»? Esta acción non se pode desfacer.", bookDeleted: "O libro eliminouse definitivamente.", personalDataUpdated: "Actualizáronse os datos persoais de lectura.", loanDataUpdated: "Actualizáronse os datos compartidos do préstamo.",
} satisfies Record<CatalogueCopyKey, string>;
export const es = {
  serverUnavailable: "BOOKPILE no ha podido conectar con el servidor. Inténtalo de nuevo.",
  coverOf: "Portada de {title}",
  shelf: "Estante",
  background: "Fondo",
  foreground: "Primer plano",
  row: "Fila",
  pile: "Pila",
  position: "Posición",
  contributorRolesUnavailable: "Los roles de colaboración no están disponibles. Recarga la página e inténtalo de nuevo.",
  noSuggestedBooks: "No hay libros pendientes disponibles que coincidan con los filtros actuales del catálogo.",
  privateCatalogue: "Catálogo privado",
  sharedCatalogue: "Catálogo compartido",
  yourBooks: "Tus libros",
  usersBooks: "Libros de {username}",
  owner: "Propietario/a",
  viewer: "Visitante",
  memberCount: "{count} miembros",
  book: "libro",
  books: "libros",
  match: "coincidencia",
  newRead: "Nueva lectura",
  add: "Añadir",
  addSingleBook: "Añadir un libro",
  batchAdd: "Añadir por lotes",
  scanSingleBarcode: "Escanear un código de barras",
  batchScan: "Escanear por lotes",
  readingSuggestion: "Sugerencia de lectura",
  another: "Otra",
  startReading: "Empezar a leer",
  closeSuggestion: "Cerrar sugerencia",
  readingSummary: "Resumen de lectura del catálogo",
  totalBooks: "Libros totales",
  waitingToRead: "Pendientes de leer",
  currentlyReading: "En lectura",
  read: "Leídos",
  searchPlaceholder: "Buscar por título, autoría, colaborador o serie",
  searchCatalogue: "Buscar en el catálogo",
  sort: "Ordenar",
  sortCatalogue: "Ordenar catálogo",
  advancedSort: "Orden avanzado",
  title: "Título",
  author: "Autoría",
  physicalLocation: "Ubicación física",
  advanced: "Avanzado",
  languages: "Idiomas",
  originalLanguages: "Idiomas originales",
  genres: "Géneros",
  publishers: "Editoriales",
  series: "Series",
  translation: "Traducción",
  category: "Categoría",
  binding: "Encuadernación",
  publicationType: "Tipo de publicación",
  unknown: "Desconocido",
  original: "Original",
  translated: "Traducido",
  fiction: "Ficción",
  nonFiction: "No ficción",
  hardcover: "Tapa dura",
  paperback: "Tapa blanda",
  flexibound: "Tapa flexible",
  spiral: "Espiral",
  stapled: "Grapado",
  other: "Otro",
  conventionalBook: "Libro convencional",
  comicGraphicNovel: "Cómic / novela gráfica",
  atlas: "Atlas",
  reference: "Consulta",
  artPhotographyIllustrated: "Arte / fotografía / ilustrado",
  magazinePeriodical: "Revista / publicación periódica",
  seriesMembership: "Pertenencia a una serie",
  any: "Cualquiera",
  inSeries: "En una serie",
  notInSeries: "Fuera de una serie",
  authors: "Autorías",
  singleAuthor: "Una autoría",
  multipleAuthors: "Varias autorías",
  minimumPages: "Páginas mínimas",
  maximumPages: "Páginas máximas",
  yearField: "Campo de año",
  currentEdition: "Edición actual",
  originalPublication: "Publicación original",
  minimumYear: "Año mínimo",
  maximumYear: "Año máximo",
  personalReadingState: "Estado personal de lectura",
  pending: "Pendiente",
  activeReading: "En lectura — cualquier lectura activa",
  firstReading: "En lectura — primera vez",
  rereadingNow: "En relectura",
  readInactive: "Leído — sin lectura activa",
  rereadingHistory: "Historial de relecturas",
  hasBeenReread: "Se ha releído",
  hasNotBeenReread: "No se ha releído",
  readingDate: "Fecha de lectura",
  readingStarted: "Inicio de lectura",
  finishedReading: "Fin de lectura",
  readingDateFrom: "Fecha de lectura desde",
  readingDateTo: "Fecha de lectura hasta",
  loanHistory: "Historial de préstamos",
  currentlyOnLoan: "Prestado actualmente",
  overdue: "Atrasado",
  everLoaned: "Prestado alguna vez",
  neverLoaned: "Nunca prestado",
  borrowerContains: "El prestatario contiene",
  loanDate: "Fecha del préstamo",
  loaned: "Prestado",
  expectedReturn: "Devolución prevista",
  returned: "Devuelto",
  loanDateFrom: "Fecha de préstamo desde",
  loanDateTo: "Fecha de préstamo hasta",
  sortBy: "Ordenar por",
  dateAdded: "Fecha de alta",
  lastUpdated: "Última actualización",
  pages: "Páginas",
  publisher: "Editorial",
  editionYear: "Año de edición",
  originalYear: "Año original",
  acquisitionDate: "Fecha de adquisición",
  loanedDate: "Fecha del préstamo",
  ascending: "Ascendente",
  descending: "Descendente",
  direction: "Dirección",
  clear: "Limpiar",
  applyFilters: "Aplicar filtros",
  onLoanTo: "Prestado a {borrower}",
  onLoan: "Prestado",
  returnsTo: "vuelve a {location}",
  beingRead: "En lectura",
  noPhysicalLocation: "Sin ubicación física",
  pageCount: "{count} páginas",
  noOptionalMetadata: "No se han registrado metadatos opcionales",
  completeInformation: "Información completa",
  goodreadsReview: "Reseña de Goodreads de {username}",
  myReading: "Mi lectura",
  manageLoan: "Gestionar o devolver préstamo",
  loanBook: "Prestar este libro",
  editBookLocation: "Editar libro y ubicación física",
  delete: "Eliminar",
  everyBookPlace: "Un lugar para cada libro",
  buildPhysicalLibrary: "Construye tu biblioteca física",
  mapOnboarding: "El mapa de BOOKPILE conecta cada registro del catálogo con su lugar real. Es opcional, pero dedicar ahora unos minutos a definir tus muebles, estantes y contenedores facilitará mucho añadir y encontrar libros.",
  setUpMap: "Configurar el mapa de la biblioteca",
  skipMap: "También puedes omitirlo y añadir libros directamente cuando prefieras.",
  noBooksMatch: "Ningún libro coincide",
  tryAnotherFilter: "Prueba otra página u otro filtro.",
  noCatalogueRecords: "Esta biblioteca todavía no tiene registros de catálogo.",
  cataloguePages: "Páginas del catálogo",
  previous: "Anterior",
  next: "Siguiente",
  close: "Cerrar", readOnlyRecord: "Registro de catálogo de solo lectura", contributors: "Colaboradores", selectedOwner: "Propietario seleccionado", notRecorded: "Sin registrar", editBook: "Editar libro",
  subtitle: "Subtítulo", isbn10: "ISBN-10", isbn13: "ISBN-13", currentEditionYear: "Año de la edición actual", originalPublicationYear: "Año de publicación original", language: "Idioma", originalLanguage: "Idioma original", edition: "Edición", seriesVolume: "Volumen de la serie", acquired: "Adquirido", originalCollection: "Colección original", height: "Altura", width: "Anchura", thickness: "Grosor", notes: "Notas",
  chooseTransferValues: "Elige los valores que deseas transferir", transferNoneAutomatic: "No se selecciona ni guarda nada automáticamente.", applyMetadata: "Aplicar metadatos seleccionados",
  batchCataloguing: "Catalogación por lotes", sharedRecord: "Registro de catálogo compartido", addNextBook: "Añadir el siguiente libro", addBook: "Añadir un libro", batchCountOne: "Se ha añadido {count} libro en este lote.", batchCountMany: "Se han añadido {count} libros en este lote.", batchHelp: "Después de guardar, BOOKPILE borra los datos del libro, pero conserva este contenedor y sugiere la posición siguiente.",
  identifyIsbn: "Identificar mediante ISBN o código de barras", barcodePrivacy: "La fotografía del código de barras se descodifica en este dispositivo y se descarta inmediatamente. Revisa los valores del proveedor antes de transferirlos.", enterIsbn: "Introduce o escanea primero un ISBN.", lookingUp: "Buscando…", lookupIsbn: "Buscar ISBN", readingPhoto: "Leyendo fotografía…", takeBarcodePhoto: "Hacer foto del código de barras", isbnAlreadyPresent: "Este ISBN ya está en la biblioteca", noBibliographicRecord: "No se ha encontrado ningún registro bibliográfico. Puedes continuar manualmente.",
  requiredInformation: "Información obligatoria", titleRequired: "Título *", authorDisplayRequired: "Autoría mostrada *", privateCover: "Imagen de portada privada", coverPrivacy: "Solo es visible para los miembros de esta biblioteca con sesión iniciada. BOOKPILE descarta el original después de eliminar los metadatos y crear una copia WebP privada.", storedCover: "Portada privada guardada", noCover: "Ninguna portada seleccionada", chooseCover: "Hacer o elegir portada", removeCover: "Eliminar portada", keepCover: "Conservar portada existente",
  contributorHelp: "Añade autores, traductores, ilustradores y otros roles acreditados en el orden en que se muestran.", contributorName: "Nombre del colaborador", moveUp: "Subir", moveDown: "Bajar", removeContributor: "Eliminar colaborador", addContributor: "Añadir colaborador",
  editionClassification: "Edición y clasificación", editionNumber: "Número de edición", commaSeparated: "Separado por comas", languageTranslation: "Idioma y traducción", translationStatus: "Estado de traducción", originalLanguageValue: "Idioma original", identifiers: "Identificadores", copyDetails: "Datos del ejemplar",
  physicalLocationHelp: "Opcional. Una posición ocupada crea espacio automáticamente; al mover un libro se compacta su contenedor anterior.", bookcase: "Mueble", chooseShelf: "Elegir estante", container: "Contenedor", chooseContainer: "Elegir contenedor", libraryNotes: "Notas de la biblioteca",
  optional: "opcional", initialReadingHelp: "Añade tu propio registro de lectura y reseña de Goodreads al crear este registro de catálogo compartido. Estos valores son personales y se borran antes del siguiente libro añadido por lotes.", readingRecord: "Registro de lectura", noReadingRecord: "Sin registro de lectura", historicalCompleted: "Lectura histórica — terminada", activeStarted: "En lectura — iniciada", readingDatesUnknown: "Fechas de lectura desconocidas", started: "Inicio", finished: "Fin", goodreadsUrl: "URL de mi reseña de Goodreads",
  currentLoan: "Préstamo actual", copyCurrentlyLoaned: "Este ejemplar físico está prestado actualmente", retainedPositionHelp: "La posición reservada en el estante se conserva mientras el ejemplar aparece en el área compartida de préstamos.", loanedToRequired: "Prestado a *", loanDateLabel: "Fecha del préstamo", optionalUnknown: "opcional / desconocida", expectedReturnLabel: "Devolución prevista", privateOwnerNotes: "Notas privadas de las personas propietarias",
  processingPhotoHelp: "Las fotografías grandes del teléfono pueden tardar varios segundos. Mantén abierta esta ventana.", finishBatch: "Terminar lote", cancel: "Cancelar", pleaseWait: "Espera…", saveScanNext: "Guardar y escanear siguiente", saveAddNext: "Guardar y añadir siguiente", saveBook: "Guardar libro",
  barcodeReadingLocally: "Leyendo el código de barras localmente…", checkingSources: "Consultando fuentes bibliográficas y esta biblioteca…", selectedCoverPreview: "Vista previa de la portada seleccionada", loanReadingConflict: "Un ejemplar no puede estar prestado y en lectura activa al mismo tiempo.",
  processingCover: "Procesando portada privada…", removingCover: "Eliminando portada privada…", savingGoodreads: "Guardando tu reseña de Goodreads…", savingReadingHistory: "Guardando tu historial de lectura…", startingReading: "Iniciando tu lectura…",
  partialSave: "Se han guardado el libro compartido y su ubicación, pero han fallado algunos datos de portada privada o lectura personal. {error} Corrígelo y vuelve a intentarlo: BOOKPILE actualizará este libro en vez de crear un duplicado.", savedNext: "«{title}» guardado. Todo listo para el siguiente libro.", bookSaved: "Libro y portada privada guardados.", bookUpdated: "Libro actualizado.", deleteBookConfirm: "¿Eliminar definitivamente «{title}»? Esta acción no se puede deshacer.", bookDeleted: "Libro eliminado definitivamente.", personalDataUpdated: "Datos personales de lectura actualizados.", loanDataUpdated: "Datos compartidos del préstamo actualizados.",
} satisfies Record<CatalogueCopyKey, string>;

export const pt = cataloguePt;
export const ca = catalogueCa;

const catalogues: Record<AppLocale, Record<CatalogueCopyKey, string>> = { en, gl, es, pt, ca };

export function catalogueCopy(locale: AppLocale): CatalogueCopy {
  const catalogue = catalogues[locale];
  return (key, values = {}) => catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) =>
    Object.hasOwn(values, name) ? String(values[name]) : token,
  );
}
