import type { AppLocale } from "./locale";

const en = {
  requestFailed: "BOOKPILE could not complete that request.", libraryCreated: "“{name}” was created. You are its first Owner.", joinedOwner: "You joined “{name}” as an Owner.", joinedViewer: "You joined “{name}” as a Viewer.",
  invitationReadyNotice: "The single-use library invitation is ready. It expires in seven days.", copied: "{label} copied to the clipboard.", clipboardFailed: "BOOKPILE could not access the clipboard. Select and copy the visible value manually.",
  invitationMessageLabel: "Library invitation message", invitationLinkLabel: "Library invitation link", memberUpdated: "{username}'s membership was updated.", libraryDeleted: "“{name}” was deleted. Its former Owners can restore it from their private profiles for 48 hours.",
  newLibraryImported: "“{name}” was created and the {source} library was imported atomically.", existingLibraryImported: "The {source} library was imported into “{name}” without replacing its existing books.", sourceServer: "Server", sourceLocal: "Local", preparingExport: "Preparing a private portable export of “{name}”.",
  updateMembership: "Update membership", confirmAccessChange: "Confirm this change to the member's library access.", giveMapTitle: "Give {username} map access?", removeMapTitle: "Remove {username}'s map access?",
  giveMapHelp: "This Viewer will be able to see the physical Library Map and saved book locations, in addition to the catalogue. Access remains read-only.", removeMapHelp: "This Viewer will retain read-only catalogue access, but physical locations and the Library Map will no longer be available.",
  promoteTitle: "Make {username} an equal co-Owner?", promoteHelp: "A co-Owner receives the same authority as you: they can edit the catalogue and layout, manage members and loans, remove your own membership, export or restore data, and initiate deletion of the entire library. Only grant this role to someone you fully trust.",
  downgradeTitle: "Change {username} from Owner to Viewer?", downgradeHelp: "This person will lose all editing and member-management powers. Choose whether their remaining read-only access includes the physical Library Map.",
  removeTitle: "Remove {username} from this library?", removeHelp: "This immediately removes their access to the catalogue, map, covers, reading perspectives, and library membership. Their BOOKPILE account is not deleted.",
  closeSettings: "Close settings panel", settingsTitle: "Library settings: {name}", manageStructure: "Manage physical structure", manageStructureHelp: "Create or remove furniture, shelves and containers.", manageMembers: "Manage members", manageMembersHelp: "Members, permissions and invitations.", dataPortability: "Data & portability", dataPortabilityHelp: "Import a BOOKPILE Local backup or export this library.", deleteLibrary: "Delete library", deleteLibraryMenuHelp: "Remove it for everyone, with a 48-hour recovery window.",
  equalCoOwner: "Equal co-Owner", viewerCatalogueMap: "Viewer · catalogue + map", viewerCatalogueOnly: "Viewer · catalogue only", giveMapAccess: "Give map access", removeMapAccess: "Remove map access", makeCoOwner: "Make co-Owner", makeViewer: "Make Viewer", remove: "Remove",
  inviteMember: "Invite a member", role: "Role", viewer: "Viewer", access: "Access", catalogueOnly: "Catalogue only", catalogueMap: "Catalogue and map", invitationLanguage: "Invitation language", ownerAcknowledgement: "I understand this person receives equal authority and may remove me.", generateInvitation: "Generate invitation", invitationMessage: "Invitation message", copyMessage: "Copy message", copyLinkOnly: "Copy link only",
  exportTitle: "Export “{name}”", exportHelp: "Download a verified Server ZIP containing this library, its map, covers, loans and member-labelled reading data. Account credentials, email, profiles and other libraries are never included.", downloadZip: "Download portable ZIP",
  importTitle: "Restore or import a BOOKPILE ZIP", importHelp: "Local backups add a catalogue and assign its personal history to one Owner. Portable Server exports restore shared structure exactly and let you map each source identity to a current Owner.", zipSource: "ZIP source", localBackup: "BOOKPILE Local full backup", serverExport: "BOOKPILE Server portable export", localZip: "Local full-backup ZIP", serverZip: "Server portable ZIP", readingOwner: "Reading history belongs to", you: "you", inspecting: "Inspecting safely…", inspectZip: "Inspect ZIP", importLimit: "Maximum compressed ZIP: 100 MiB. Inspection is isolated and cannot change this library until you approve its report.",
  uploading: "Uploading and inspecting the ZIP…", uploadingHelp: "Checksums, covers, data integrity and relationships are being verified. Large libraries can take a while; keep this window open.", readyReview: "Ready for review", exportDescription: "Server export “{name}”", localDescription: "Local backup", created: "created", capacityError: "The final Server representation does not currently fit the shared storage available to this library's Owners.", repeatedArchive: "I intend to add another set of physical copies from this same backup.",
  countBooks: "books", countBookcases: "bookcases", countShelves: "shelves", countContainers: "containers", countContributors: "contributors", countAuthors: "book authors", countReadings: "readings", countLoans: "loans", countCovers: "covers",
  warningRepeated: "This exact ZIP was already prepared or imported into this library.", warningDuplicateIsbn: "{count} imported books may duplicate an existing ISBN.", warningDuplicateTitle: "{count} imported books may duplicate an existing title and author.", warningCapacity: "The imported data does not fit the Owners' shared storage capacity.", warningCoordinates: "This library uses a different map mode or coordinate system. Restore the ZIP as a new library to preserve its geometry.", warningFurniture: "Some furniture names already exist in this library. Rename them or restore the ZIP as a new library.", warningOutsideAreas: "Some existing outside-library areas will take precedence. Imported books and shared data are unaffected.", warningGeneric: "The inspection found a condition requiring your attention ({code}).",
  personalDataTitle: "Personal data in “{name}”", personalDataHelp: "Memberships are never restored. Map a source person to a current Owner to restore that person's readings and Goodreads links.", sourcePersonalCounts: "@{username} · {readings} readings · {records} personal records", doNotRestorePersonal: "Do not restore personal data", duplicateOwner: "Each destination Owner can receive only one source identity.", omitUnmapped: "I understand that the unmapped readings and Goodreads links will be omitted.",
  creatingImport: "Creating the library and importing atomically…", importing: "Importing atomically…", processingImport: "Processing {books} books, {covers} covers, {readings} readings and {loans} loans. Nothing becomes visible unless the whole operation succeeds.", cancelStaging: "Cancel and erase staging", restoreHere: "Restore into this library", importHere: "Import into this library", createSeparate: "Or create a separate library", newLibraryName: "New library name", sourceIdentity: "Source identity to restore as you", noneOmitPersonal: "None — omit all personal data", sourceReadings: "@{username} · {readings} readings", omitOtherMembers: "I understand that all other source members' readings and Goodreads links will be omitted.", creatingAndImporting: "Creating and importing…", importAsNew: "Import as a new library", newOwnerHelp: "You will be its only initial Owner. Server memberships are never recreated; invite people afterwards.", importComplete: "Import complete. {books} books and all compatible related records were added.",
  permissionChange: "Permission change", viewerAccess: "Viewer access", currentPassword: "Your current password", cancel: "Cancel", applying: "Applying…", confirmChange: "Confirm change", dangerZone: "Danger zone", deleteTitle: "Delete “{name}”?", deleteHelp: "This immediately removes access for every member and quarantines all books, covers, physical layout, readings and loans. Any person who was an Owner at deletion time may restore everything for 48 hours. After that, deletion is permanent.", typeExactly: "Type {name} exactly", deletionAcknowledgement: "I understand that recovery expires after 48 hours and then all library data is permanently deleted.", deleting: "Deleting…",
  emptyTitle: "Create or join a library", emptyHelp: "Accounts and libraries are separate: an account may own or view several libraries.",
} as const;

export type LibraryAdminCopyKey = keyof typeof en;
const gl = {
  requestFailed: "BOOKPILE non puido completar esa solicitude.", libraryCreated: "Creouse «{name}». Es a primeira persoa propietaria.", joinedOwner: "Unícheste a «{name}» como persoa propietaria.", joinedViewer: "Unícheste a «{name}» como visitante.",
  invitationReadyNotice: "O convite de uso único para a biblioteca está listo. Caduca aos sete días.", copied: "Copiouse {label} no portapapeis.", clipboardFailed: "BOOKPILE non puido acceder ao portapapeis. Selecciona e copia manualmente o valor visible.",
  invitationMessageLabel: "mensaxe do convite á biblioteca", invitationLinkLabel: "ligazón do convite á biblioteca", memberUpdated: "Actualizouse a pertenza de {username}.", libraryDeleted: "Eliminouse «{name}». As persoas que eran propietarias poden restaurala desde os seus perfís privados durante 48 horas.",
  newLibraryImported: "Creouse «{name}» e importouse atomicamente a biblioteca {source}.", existingLibraryImported: "Importouse a biblioteca {source} en «{name}» sen substituír os libros existentes.", sourceServer: "Server", sourceLocal: "Local", preparingExport: "Preparando unha exportación portátil privada de «{name}».",
  updateMembership: "Actualizar pertenza", confirmAccessChange: "Confirma este cambio no acceso do membro á biblioteca.", giveMapTitle: "Dar acceso ao mapa a {username}?", removeMapTitle: "Retirar o acceso ao mapa a {username}?",
  giveMapHelp: "Este visitante poderá ver o mapa físico da biblioteca e as localizacións gardadas dos libros, ademais do catálogo. O acceso seguirá sendo de só lectura.", removeMapHelp: "Este visitante conservará o acceso de só lectura ao catálogo, pero deixará de poder ver as localizacións físicas e o mapa da biblioteca.",
  promoteTitle: "Facer de {username} unha persoa copropietaria con iguais permisos?", promoteHelp: "Unha persoa copropietaria recibe a mesma autoridade ca ti: pode editar o catálogo e a disposición, xestionar membros e préstamos, eliminar a túa pertenza, exportar ou restaurar datos e iniciar a eliminación da biblioteca completa. Concede este rol só a alguén de plena confianza.",
  downgradeTitle: "Cambiar {username} de propietario/a a visitante?", downgradeHelp: "Esta persoa perderá todos os permisos de edición e xestión de membros. Escolle se o seu acceso restante de só lectura inclúe o mapa físico da biblioteca.",
  removeTitle: "Eliminar {username} desta biblioteca?", removeHelp: "Isto retira de inmediato o seu acceso ao catálogo, mapa, portadas, perspectivas de lectura e pertenza á biblioteca. A súa conta de BOOKPILE non se elimina.",
  closeSettings: "Pechar o panel de configuración", settingsTitle: "Configuración da biblioteca: {name}", manageStructure: "Xestionar estrutura física", manageStructureHelp: "Crear ou eliminar mobles, andeis e contedores.", manageMembers: "Xestionar membros", manageMembersHelp: "Membros, permisos e convites.", dataPortability: "Datos e portabilidade", dataPortabilityHelp: "Importar unha copia de BOOKPILE Local ou exportar esta biblioteca.", deleteLibrary: "Eliminar biblioteca", deleteLibraryMenuHelp: "Elimínaa para todo o mundo cun prazo de recuperación de 48 horas.",
  equalCoOwner: "Copropietario/a con iguais permisos", viewerCatalogueMap: "Visitante · catálogo + mapa", viewerCatalogueOnly: "Visitante · só catálogo", giveMapAccess: "Dar acceso ao mapa", removeMapAccess: "Retirar acceso ao mapa", makeCoOwner: "Facer copropietario/a", makeViewer: "Facer visitante", remove: "Eliminar",
  inviteMember: "Convidar un membro", role: "Rol", viewer: "Visitante", access: "Acceso", catalogueOnly: "Só catálogo", catalogueMap: "Catálogo e mapa", invitationLanguage: "Idioma do convite", ownerAcknowledgement: "Entendo que esta persoa recibe a mesma autoridade e pode eliminar a miña pertenza.", generateInvitation: "Xerar convite", invitationMessage: "Mensaxe do convite", copyMessage: "Copiar mensaxe", copyLinkOnly: "Copiar só a ligazón",
  exportTitle: "Exportar «{name}»", exportHelp: "Descarga un ZIP de Server verificado que contén esta biblioteca, o seu mapa, portadas, préstamos e datos de lectura identificados por membro. Nunca inclúe credenciais, correo, perfís nin outras bibliotecas.", downloadZip: "Descargar ZIP portátil",
  importTitle: "Restaurar ou importar un ZIP de BOOKPILE", importHelp: "As copias de Local engaden un catálogo e atribúen o seu historial persoal a unha persoa propietaria. As exportacións portátiles de Server restauran exactamente a estrutura compartida e permiten asociar cada identidade de orixe cun propietario actual.", zipSource: "Orixe do ZIP", localBackup: "Copia completa de BOOKPILE Local", serverExport: "Exportación portátil de BOOKPILE Server", localZip: "ZIP de copia completa de Local", serverZip: "ZIP portátil de Server", readingOwner: "O historial de lectura pertence a", you: "ti", inspecting: "Inspeccionando con seguridade…", inspectZip: "Inspeccionar ZIP", importLimit: "ZIP comprimido máximo: 100 MiB. A inspección está illada e non pode cambiar esta biblioteca ata que aprobes o informe.",
  uploading: "Subindo e inspeccionando o ZIP…", uploadingHelp: "Estanse verificando as sumas de comprobación, as portadas, a integridade dos datos e as relacións. As bibliotecas grandes poden tardar; mantén esta xanela aberta.", readyReview: "Listo para revisar", exportDescription: "Exportación de Server «{name}»", localDescription: "Copia de Local", created: "creada", capacityError: "A representación final en Server non cabe actualmente no almacenamento compartido dispoñible para as persoas propietarias desta biblioteca.", repeatedArchive: "Quero engadir outro conxunto de exemplares físicos desta mesma copia.",
  countBooks: "libros", countBookcases: "mobles", countShelves: "andeis", countContainers: "contedores", countContributors: "colaboradores", countAuthors: "autorías", countReadings: "lecturas", countLoans: "préstamos", countCovers: "portadas",
  warningRepeated: "Este mesmo ZIP xa se preparou ou importou nesta biblioteca.", warningDuplicateIsbn: "{count} libros importados poden duplicar un ISBN existente.", warningDuplicateTitle: "{count} libros importados poden duplicar un título e autoría existentes.", warningCapacity: "Os datos importados non caben no almacenamento compartido das persoas propietarias.", warningCoordinates: "Esta biblioteca usa un modo de mapa ou sistema de coordenadas diferente. Restaura o ZIP como biblioteca nova para conservar a súa xeometría.", warningFurniture: "Algúns nomes de mobles xa existen nesta biblioteca. Cámbiaos ou restaura o ZIP como biblioteca nova.", warningOutsideAreas: "Algunhas áreas existentes fóra da biblioteca terán prioridade. Os libros importados e os datos compartidos non se verán afectados.", warningGeneric: "A inspección atopou unha condición que require atención ({code}).",
  personalDataTitle: "Datos persoais en «{name}»", personalDataHelp: "As pertenzas nunca se restauran. Asocia unha persoa de orixe cun propietario actual para restaurar as súas lecturas e ligazóns de Goodreads.", sourcePersonalCounts: "@{username} · {readings} lecturas · {records} rexistros persoais", doNotRestorePersonal: "Non restaurar datos persoais", duplicateOwner: "Cada propietario de destino só pode recibir unha identidade de orixe.", omitUnmapped: "Entendo que se omitirán as lecturas e ligazóns de Goodreads non asociadas.",
  creatingImport: "Creando a biblioteca e importando atomicamente…", importing: "Importando atomicamente…", processingImport: "Procesando {books} libros, {covers} portadas, {readings} lecturas e {loans} préstamos. Nada será visible se non se completa toda a operación.", cancelStaging: "Cancelar e borrar a área temporal", restoreHere: "Restaurar nesta biblioteca", importHere: "Importar nesta biblioteca", createSeparate: "Ou crear unha biblioteca separada", newLibraryName: "Nome da biblioteca nova", sourceIdentity: "Identidade de orixe que se restaurará como ti", noneOmitPersonal: "Ningunha — omitir todos os datos persoais", sourceReadings: "@{username} · {readings} lecturas", omitOtherMembers: "Entendo que se omitirán as lecturas e ligazóns de Goodreads dos demais membros de orixe.", creatingAndImporting: "Creando e importando…", importAsNew: "Importar como biblioteca nova", newOwnerHelp: "Serás a única persoa propietaria inicial. As pertenzas de Server nunca se recrean; convida despois as persoas.", importComplete: "Importación completa. Engadíronse {books} libros e todos os rexistros relacionados compatibles.",
  permissionChange: "Cambio de permisos", viewerAccess: "Acceso de visitante", currentPassword: "O teu contrasinal actual", cancel: "Cancelar", applying: "Aplicando…", confirmChange: "Confirmar cambio", dangerZone: "Zona de perigo", deleteTitle: "Eliminar «{name}»?", deleteHelp: "Isto retira inmediatamente o acceso a todos os membros e pon en corentena os libros, portadas, disposición física, lecturas e préstamos. Calquera persoa que fose propietaria no momento da eliminación pode restauralo todo durante 48 horas. Despois, a eliminación é definitiva.", typeExactly: "Escribe {name} exactamente", deletionAcknowledgement: "Entendo que a recuperación caduca ás 48 horas e que despois se eliminan definitivamente todos os datos da biblioteca.", deleting: "Eliminando…",
  emptyTitle: "Crear ou unirse a unha biblioteca", emptyHelp: "As contas e as bibliotecas son independentes: unha conta pode posuír ou ver varias bibliotecas.",
} satisfies Record<LibraryAdminCopyKey, string>;

export type LibraryAdminCopy = (key: LibraryAdminCopyKey, values?: Record<string, string | number>) => string;
const catalogues: Record<AppLocale, Record<LibraryAdminCopyKey, string>> = { en, gl };
export function libraryAdminCopy(locale: AppLocale): LibraryAdminCopy {
  const catalogue = catalogues[locale];
  return (key, values = {}) => catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? String(values[name]) : token);
}
