import type { AppLocale } from "./locale";

export const en = {
  requestFailed: "BOOKPILE could not complete that request.", libraryCreated: "“{name}” was created. You are its first Owner.", joinedOwner: "You joined “{name}” as an Owner.", joinedViewer: "You joined “{name}” as a Viewer.",
  invitationReadyNotice: "The single-use library invitation is ready. It expires in seven days.", copied: "{label} copied to the clipboard.", clipboardFailed: "BOOKPILE could not access the clipboard. Select and copy the visible value manually.",
  invitationMessageLabel: "Library invitation message", invitationLinkLabel: "Library invitation link", memberUpdated: "{username}'s membership was updated.", libraryDeleted: "“{name}” was deleted. Its former Owners can restore it from their private profiles for 48 hours.",
  newLibraryImported: "“{name}” was created and the {source} library was imported atomically.", existingLibraryImported: "The {source} library was imported into “{name}” without replacing its existing books.", sourceServer: "Server", sourceLocal: "Local", preparingExport: "Preparing a private portable export of “{name}”.",
  updateMembership: "Update membership", confirmAccessChange: "Confirm this change to the member's library access.", giveMapTitle: "Give {username} map access?", removeMapTitle: "Remove {username}'s map access?",
  giveMapHelp: "This Viewer will be able to see the physical Library Map and saved book locations, in addition to the catalogue. Access remains read-only.", removeMapHelp: "This Viewer will retain read-only catalogue access, but physical locations and the Library Map will no longer be available.",
  promoteTitle: "Make {username} an equal co-Owner?", promoteHelp: "A co-Owner receives the same authority as you: they can edit the catalogue and layout, manage members and loans, remove your own membership, export or restore data, and initiate deletion of the entire library. Only grant this role to someone you fully trust.",
  downgradeTitle: "Change {username} from Owner to Viewer?", downgradeHelp: "This person will lose all editing and member-management powers. Choose whether their remaining read-only access includes the physical Library Map.",
  removeTitle: "Remove {username} from this library?", removeHelp: "This immediately removes their access to the catalogue, map, covers, reading perspectives, and library membership. Their BOOKPILE account is not deleted.",
  closeSettings: "Close settings panel", settingsTitle: "Library settings: {name}", manageStructure: "Manage physical structure", manageStructureHelp: "Create or remove furniture, shelves and containers.", manageMembers: "Manage members", manageMembersHelp: "Members, permissions and invitations.", dataPortability: "Data & portability", dataPortabilityHelp: "Import a BOOKPILE Local backup or export this library.", deleteLibrary: "Delete library", deleteLibraryMenuHelp: "Remove it for everyone, with a 48-hour recovery window.",
  equalCoOwner: "Equal co-Owner", viewerCatalogueMap: "Viewer · catalogue + map", viewerCatalogueOnly: "Viewer · catalogue only", giveMapAccess: "Give map access", removeMapAccess: "Remove map access", makeCoOwner: "Make co-Owner", makeViewer: "Make Viewer", remove: "Remove",
  inviteMember: "Invite a member", role: "Role", viewer: "Viewer", access: "Access", catalogueOnly: "Catalogue only", catalogueMap: "Catalogue and map", invitationLanguage: "Invitation language", ownerAcknowledgement: "I understand this person receives equal authority and may remove me.", generateInvitation: "Generate invitation", invitationMessage: "Invitation message", copyMessage: "Copy message", copyLinkOnly: "Copy link only",
  exportTitle: "Export “{name}”", exportHelp: "Download a verified Server ZIP containing this library, its map, covers, loans and member-labelled reading data. Account credentials, email, profiles and other libraries are never included.", downloadZip: "Download portable ZIP",
  importTitle: "Restore or import a BOOKPILE ZIP", importHelp: "Local backups add a catalogue and assign its personal history to one Owner. Portable Server exports restore shared structure exactly and let you map each source identity to a current Owner.", zipSource: "ZIP source", localBackup: "BOOKPILE Local full backup", serverExport: "BOOKPILE Server portable export", localZip: "Local full-backup ZIP", serverZip: "Server portable ZIP", readingOwner: "Reading history belongs to", you: "you", inspecting: "Inspecting safely…", inspectZip: "Inspect ZIP", importLimit: "Maximum compressed ZIP: 100 MiB. Inspection is isolated and cannot change this library until you approve its report.",
  uploading: "Uploading and inspecting the ZIP…", uploadingHelp: "Checksums, covers, data integrity and relationships are being verified. Large libraries can take a while; keep this window open.", readyReview: "Ready for review", exportDescription: "Server export “{name}”", localDescription: "Local backup", format: "format", schema: "schema", created: "created", capacityError: "The final Server representation does not currently fit the shared storage available to this library's Owners.", repeatedArchive: "I intend to add another set of physical copies from this same backup.",
  countBooks: "books", countBookcases: "bookcases", countShelves: "shelves", countContainers: "containers", countContributors: "contributors", countAuthors: "book authors", countReadings: "readings", countLoans: "loans", countCovers: "covers",
  warningRepeated: "This exact ZIP was already prepared or imported into this library.", warningDuplicateIsbn: "{count} imported books may duplicate an existing ISBN.", warningDuplicateTitle: "{count} imported books may duplicate an existing title and author.", warningCapacity: "The imported data does not fit the Owners' shared storage capacity.", warningCoordinates: "This library uses a different map mode or coordinate system. Restore the ZIP as a new library to preserve its geometry.", warningFurniture: "Some furniture names already exist in this library. Rename them or restore the ZIP as a new library.", warningOutsideAreas: "Some existing outside-library areas will take precedence. Imported books and shared data are unaffected.", warningGeneric: "The inspection found a condition requiring your attention ({code}).",
  personalDataTitle: "Personal data in “{name}”", personalDataHelp: "Memberships are never restored. Map a source person to a current Owner to restore that person's readings and Goodreads links.", sourcePersonalCounts: "@{username} · {readings} readings · {records} personal records", doNotRestorePersonal: "Do not restore personal data", duplicateOwner: "Each destination Owner can receive only one source identity.", omitUnmapped: "I understand that the unmapped readings and Goodreads links will be omitted.",
  creatingImport: "Creating the library and importing atomically…", importing: "Importing atomically…", processingImport: "Processing {books} books, {covers} covers, {readings} readings and {loans} loans. Nothing becomes visible unless the whole operation succeeds.", cancelStaging: "Cancel and erase staging", restoreHere: "Restore into this library", importHere: "Import into this library", createSeparate: "Or create a separate library", newLibraryName: "New library name", sourceIdentity: "Source identity to restore as you", noneOmitPersonal: "None — omit all personal data", sourceReadings: "@{username} · {readings} readings", omitOtherMembers: "I understand that all other source members' readings and Goodreads links will be omitted.", creatingAndImporting: "Creating and importing…", importAsNew: "Import as a new library", newOwnerHelp: "You will be its only initial Owner. Server memberships are never recreated; invite people afterwards.", importComplete: "Import complete. {books} books and all compatible related records were added.",
  permissionChange: "Permission change", viewerAccess: "Viewer access", currentPassword: "Your current password", cancel: "Cancel", applying: "Applying…", confirmChange: "Confirm change", dangerZone: "Danger zone", deleteTitle: "Delete “{name}”?", deleteHelp: "This immediately removes access for every member and quarantines all books, covers, physical layout, readings and loans. Any person who was an Owner at deletion time may restore everything for 48 hours. After that, deletion is permanent.", typeExactly: "Type {name} exactly", deletionAcknowledgement: "I understand that recovery expires after 48 hours and then all library data is permanently deleted.", deleting: "Deleting…",
  emptyTitle: "Create or join a library", emptyHelp: "Accounts and libraries are separate: an account may own or view several libraries.",
} as const;

export type LibraryAdminCopyKey = keyof typeof en;



export type LibraryAdminCopy = (key: LibraryAdminCopyKey, values?: Record<string, string | number>) => string;
const catalogues: Partial<Record<AppLocale, Record<LibraryAdminCopyKey, string>>> = { en };

export function registerLibraryAdminCatalogue(
  locale: AppLocale,
  catalogue: Record<LibraryAdminCopyKey, string>,
): void {
  catalogues[locale] = catalogue;
}
export function libraryAdminCopy(locale: AppLocale): LibraryAdminCopy {
  const catalogue = catalogues[locale];
  if (!catalogue) throw new Error(`Locale catalogue not loaded: ${locale}`);
  return (key, values = {}) => catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? String(values[name]) : token);
}
