import type { AppLocale } from "./locale";

export const en = {
  unavailable: "Library Map unavailable.", bookUnavailable: "Book information unavailable.", previewFailed: "The destination could not be previewed.", undoFailed: "Undo failed.", applyFailed: "The rearrangement could not be applied.", loading: "Loading Library Map…",
  visualIndex: "Visual library index", libraryMap: "Library Map", backCatalogue: "Back to catalogue", catalogue: "Catalogue", reorganize: "Reorganize books", editLayout: "Edit layout", chooseInspection: "Choose inspection mode", books: "Books", containers: "Containers", inspectionMode: "Inspection mode: {mode}. Tap to switch.",
  colourBy: "Colour by", genre: "Genre", publisher: "Publisher", author: "Author", choose: "Choose…", perspectiveColours: "Colours show {username}'s perspective. Physical custody is shared.",
  dragObject: "Drag selected object", resizeObject: "Resize selected object", cameraControls: "Map camera controls", resetView: "Reset view", zoomIn: "Zoom in", zoomOut: "Zoom out",
  draftMovement: "Draft movement", chooseBook: "Choose a book", chooseBookMap: "Choose a book on the map", expandDraft: "Expand draft", collapseDraft: "Collapse draft", expand: "Expand", collapse: "Collapse", cancelDraft: "Cancel draft",
  oldPosition: "Old position", newPosition: "New position", collapsePosition: "Collapse", leaveGap: "Leave gap", squeeze: "Squeeze", swap: "Swap", continue: "Continue", releaseSpace: "Release shelf space if this move removes pages from its source container",
  book: "Book", chooseMapHere: "Choose on map or here", destinationContainer: "Destination container", shelf: "Shelf", background: "Background", foreground: "Foreground", row: "Row", pile: "Pile", position: "Position", previewDestination: "Preview destination", moveNumber: "Move {number}", unchangedDraft: "This draft adds up to an unchanged arrangement. Add another move or cancel it.", undo: "Undo last step", addMove: "Add another move", apply: "Apply",
  bookMoved: "“{title}”: {source} → {destination}", bookShifted: "{count} book shifted {reason}.", booksShifted: "{count} books shifted {reason}.", occupyGap: "to occupy the gap", fillGapAndMakeRoom: "to fill the gap and make new room", makeRoom: "to make room", continueWithBook: "Continue with “{title}”.", noStackingCapacity: "{container} has no free stacking-axis capacity.", booksCompressed: "{container} will compress its books by {percent}%.", insufficientCapacity: "{container} needs {needed}% but only {available}% is available.", unknownScale: "{container} had no known scale; its first book uses 10% of available space.", layoutConflict: "The projected layout conflicts with another physical element.", rearrangementWarning: "The movement needs attention before it can be applied.",
  clearSelection: "Clear selection", selectedBook: "Selected book", pages: "{count} pages", unknownPages: "Page count unknown · visual fallback {count} pages", selectedContainer: "Selected container", bookCount: "{count} book", booksCount: "{count} books", focusContainer: "Focus container", loadingDetails: "Loading…", completeInformation: "Complete information", readOnlyInspection: "Read-only inspection",
  readingStatus: "Reading status", acquisitionRecency: "Acquisition recency", readingRecency: "Reading recency", pendingDuration: "Time spent pending", readingDuration: "Reading duration", readingRate: "Reading rate (pages/day)", language: "Language", originalLanguage: "Original language", translationStatus: "Translation status", editionYear: "Current edition year", originalYear: "Original publication year", genreFocus: "Genre focus", publisherFocus: "Publisher focus", authorFocus: "Author focus", fictionCategory: "Fiction / non-fiction", binding: "Binding", publicationType: "Publication type",
  pending: "Pending", reading: "Reading", onLoan: "On loan", physicalCopyReading: "This physical copy is being read", physicalCopyOnLoan: "This physical copy is on loan", rereading: "Re-reading", read: "Read", notSelected: "Not selected", otherBooks: "Other books", chooseFocus: "Choose a {mode}", notRecorded: "Not recorded", originalCollection: "Original collection", noAcquisitionDate: "No acquisition date", stillReading: "Still reading", stillRereading: "Still re-reading", readNoData: "Read · no data", noData: "No data", days: "{count} days", pagesPerDay: "{count} pages/day", noRecordedData: "No recorded data", shortest: "Shortest", longest: "Longest", slowest: "Slowest", fastest: "Fastest", oldest: "Oldest", newest: "Newest", endpointOne: "{adjective}: “{title}” · {value}", endpointTie: "{adjective}: tie ({count}) · {value}",
} as const;
export type MapCopyKey = keyof typeof en;
const gl = {
  unavailable: "O mapa da biblioteca non está dispoñible.", bookUnavailable: "A información do libro non está dispoñible.", previewFailed: "Non se puido previsualizar o destino.", undoFailed: "Non se puido desfacer.", applyFailed: "Non se puido aplicar a reorganización.", loading: "Cargando o mapa da biblioteca…",
  visualIndex: "Índice visual da biblioteca", libraryMap: "Mapa da biblioteca", backCatalogue: "Volver ao catálogo", catalogue: "Catálogo", reorganize: "Reorganizar libros", editLayout: "Editar disposición", chooseInspection: "Escoller modo de inspección", books: "Libros", containers: "Contedores", inspectionMode: "Modo de inspección: {mode}. Toca para cambiar.",
  colourBy: "Cor segundo", genre: "Xénero", publisher: "Editorial", author: "Autoría", choose: "Escoller…", perspectiveColours: "As cores mostran a perspectiva de {username}. A custodia física é compartida.",
  dragObject: "Arrastrar o obxecto seleccionado", resizeObject: "Redimensionar o obxecto seleccionado", cameraControls: "Controis da cámara do mapa", resetView: "Restablecer vista", zoomIn: "Achegar", zoomOut: "Afastar",
  draftMovement: "Movemento en borrador", chooseBook: "Escoller un libro", chooseBookMap: "Escolle un libro no mapa", expandDraft: "Expandir borrador", collapseDraft: "Contraer borrador", expand: "Expandir", collapse: "Contraer", cancelDraft: "Cancelar borrador",
  oldPosition: "Posición anterior", newPosition: "Posición nova", collapsePosition: "Compactar", leaveGap: "Deixar o oco", squeeze: "Apertar", swap: "Intercambiar", continue: "Continuar", releaseSpace: "Liberar espazo no andel se este movemento retira páxinas do contedor de orixe",
  book: "Libro", chooseMapHere: "Escoller no mapa ou aquí", destinationContainer: "Contedor de destino", shelf: "Andel", background: "Fondo", foreground: "Primeiro plano", row: "Fila", pile: "Pila", position: "Posición", previewDestination: "Previsualizar destino", moveNumber: "Movemento {number}", unchangedDraft: "Este borrador produce a mesma disposición. Engade outro movemento ou cancélao.", undo: "Desfacer último paso", addMove: "Engadir outro movemento", apply: "Aplicar",
  bookMoved: "«{title}»: {source} → {destination}", bookShifted: "Desprazouse {count} libro {reason}.", booksShifted: "Desprazáronse {count} libros {reason}.", occupyGap: "para ocupar o oco", fillGapAndMakeRoom: "para encher o oco e crear espazo novo", makeRoom: "para crear espazo", continueWithBook: "Continúa con «{title}».", noStackingCapacity: "{container} non ten capacidade libre no eixe de apilamento.", booksCompressed: "{container} comprimirá os seus libros un {percent}%.", insufficientCapacity: "{container} precisa un {needed}%, pero só hai un {available}% dispoñible.", unknownScale: "{container} non tiña unha escala coñecida; o primeiro libro usa o 10% do espazo dispoñible.", layoutConflict: "A disposición proxectada entra en conflito con outro elemento físico.", rearrangementWarning: "O movemento require atención antes de poder aplicalo.",
  clearSelection: "Limpar selección", selectedBook: "Libro seleccionado", pages: "{count} páxinas", unknownPages: "Número de páxinas descoñecido · estimación visual de {count} páxinas", selectedContainer: "Contedor seleccionado", bookCount: "{count} libro", booksCount: "{count} libros", focusContainer: "Enfocar contedor", loadingDetails: "Cargando…", completeInformation: "Información completa", readOnlyInspection: "Inspección de só lectura",
  readingStatus: "Estado de lectura", acquisitionRecency: "Antigüidade da adquisición", readingRecency: "Antigüidade da lectura", pendingDuration: "Tempo pendente", readingDuration: "Duración da lectura", readingRate: "Ritmo de lectura (páxinas/día)", language: "Idioma", originalLanguage: "Idioma orixinal", translationStatus: "Estado da tradución", editionYear: "Ano da edición actual", originalYear: "Ano de publicación orixinal", genreFocus: "Xénero destacado", publisherFocus: "Editorial destacada", authorFocus: "Autoría destacada", fictionCategory: "Ficción / non ficción", binding: "Encadernación", publicationType: "Tipo de publicación",
  pending: "Pendente", reading: "En lectura", onLoan: "Prestado", physicalCopyReading: "Este exemplar físico está en lectura", physicalCopyOnLoan: "Este exemplar físico está prestado", rereading: "En relectura", read: "Lido", notSelected: "Non seleccionado", otherBooks: "Outros libros", chooseFocus: "Escoller {mode}", notRecorded: "Sen rexistrar", originalCollection: "Colección orixinal", noAcquisitionDate: "Sen data de adquisición", stillReading: "Aínda en lectura", stillRereading: "Aínda en relectura", readNoData: "Lido · sen datos", noData: "Sen datos", days: "{count} días", pagesPerDay: "{count} páxinas/día", noRecordedData: "Non hai datos rexistrados", shortest: "Máis breve", longest: "Máis longo", slowest: "Máis lento", fastest: "Máis rápido", oldest: "Máis antigo", newest: "Máis recente", endpointOne: "{adjective}: «{title}» · {value}", endpointTie: "{adjective}: empate ({count}) · {value}",
} satisfies Record<MapCopyKey, string>;
export const es = {
  unavailable: "El mapa de la biblioteca no está disponible.", bookUnavailable: "La información del libro no está disponible.", previewFailed: "No se ha podido previsualizar el destino.", undoFailed: "No se ha podido deshacer.", applyFailed: "No se ha podido aplicar la reorganización.", loading: "Cargando el mapa de la biblioteca…",
  visualIndex: "Índice visual de la biblioteca", libraryMap: "Mapa de la biblioteca", backCatalogue: "Volver al catálogo", catalogue: "Catálogo", reorganize: "Reorganizar libros", editLayout: "Editar disposición", chooseInspection: "Elegir modo de inspección", books: "Libros", containers: "Contenedores", inspectionMode: "Modo de inspección: {mode}. Toca para cambiar.",
  colourBy: "Colorear por", genre: "Género", publisher: "Editorial", author: "Autoría", choose: "Elegir…", perspectiveColours: "Los colores muestran la perspectiva de {username}. La custodia física es compartida.",
  dragObject: "Arrastrar objeto seleccionado", resizeObject: "Cambiar tamaño del objeto seleccionado", cameraControls: "Controles de cámara del mapa", resetView: "Restablecer vista", zoomIn: "Acercar", zoomOut: "Alejar",
  draftMovement: "Movimiento provisional", chooseBook: "Elegir un libro", chooseBookMap: "Elegir un libro en el mapa", expandDraft: "Expandir borrador", collapseDraft: "Contraer borrador", expand: "Expandir", collapse: "Contraer", cancelDraft: "Cancelar borrador",
  oldPosition: "Posición anterior", newPosition: "Posición nueva", collapsePosition: "Compactar", leaveGap: "Dejar hueco", squeeze: "Comprimir", swap: "Intercambiar", continue: "Continuar", releaseSpace: "Liberar espacio del estante si este movimiento retira páginas de su contenedor de origen",
  book: "Libro", chooseMapHere: "Elegir en el mapa o aquí", destinationContainer: "Contenedor de destino", shelf: "Estante", background: "Fondo", foreground: "Primer plano", row: "Fila", pile: "Pila", position: "Posición", previewDestination: "Previsualizar destino", moveNumber: "Movimiento {number}", unchangedDraft: "Este borrador da como resultado una disposición sin cambios. Añade otro movimiento o cancélalo.", undo: "Deshacer último paso", addMove: "Añadir otro movimiento", apply: "Aplicar",
  bookMoved: "«{title}»: {source} → {destination}", bookShifted: "Se ha desplazado {count} libro {reason}.", booksShifted: "Se han desplazado {count} libros {reason}.", occupyGap: "para ocupar el hueco", fillGapAndMakeRoom: "para llenar el hueco y crear espacio", makeRoom: "para crear espacio", continueWithBook: "Continuar con «{title}».", noStackingCapacity: "{container} no tiene espacio libre en el eje de apilado.", booksCompressed: "{container} comprimirá sus libros un {percent}%.", insufficientCapacity: "{container} necesita un {needed}%, pero solo hay un {available}% disponible.", unknownScale: "{container} no tenía una escala conocida; su primer libro usa el 10% del espacio disponible.", layoutConflict: "La disposición proyectada entra en conflicto con otro elemento físico.", rearrangementWarning: "El movimiento requiere atención antes de poder aplicarlo.",
  clearSelection: "Borrar selección", selectedBook: "Libro seleccionado", pages: "{count} páginas", unknownPages: "Número de páginas desconocido · estimación visual de {count} páginas", selectedContainer: "Contenedor seleccionado", bookCount: "{count} libro", booksCount: "{count} libros", focusContainer: "Centrar contenedor", loadingDetails: "Cargando…", completeInformation: "Información completa", readOnlyInspection: "Inspección de solo lectura",
  readingStatus: "Estado de lectura", acquisitionRecency: "Antigüedad de adquisición", readingRecency: "Antigüedad de lectura", pendingDuration: "Tiempo pendiente", readingDuration: "Duración de la lectura", readingRate: "Ritmo de lectura (páginas/día)", language: "Idioma", originalLanguage: "Idioma original", translationStatus: "Estado de traducción", editionYear: "Año de la edición actual", originalYear: "Año de publicación original", genreFocus: "Género destacado", publisherFocus: "Editorial destacada", authorFocus: "Autoría destacada", fictionCategory: "Ficción / no ficción", binding: "Encuadernación", publicationType: "Tipo de publicación",
  pending: "Pendiente", reading: "En lectura", onLoan: "Prestado", physicalCopyReading: "Este ejemplar físico está en lectura", physicalCopyOnLoan: "Este ejemplar físico está prestado", rereading: "En relectura", read: "Leído", notSelected: "No seleccionado", otherBooks: "Otros libros", chooseFocus: "Elegir {mode}", notRecorded: "Sin registrar", originalCollection: "Colección original", noAcquisitionDate: "Sin fecha de adquisición", stillReading: "Todavía en lectura", stillRereading: "Todavía en relectura", readNoData: "Leído · sin datos", noData: "Sin datos", days: "{count} días", pagesPerDay: "{count} páginas/día", noRecordedData: "No hay datos registrados", shortest: "Más breve", longest: "Más largo", slowest: "Más lento", fastest: "Más rápido", oldest: "Más antiguo", newest: "Más reciente", endpointOne: "{adjective}: «{title}» · {value}", endpointTie: "{adjective}: empate ({count}) · {value}",
} satisfies Record<MapCopyKey, string>;

export type MapCopy = (key: MapCopyKey, values?: Record<string, string | number>) => string;
const catalogues: Record<AppLocale, Record<MapCopyKey, string>> = { en, gl, es };
export function mapCopy(locale: AppLocale): MapCopy {
  const catalogue = catalogues[locale];
  return (key, values = {}) => catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? String(values[name]) : token);
}
