import type { AppLocale } from "./locale";

const en = {
  requestFailed: "BOOKPILE could not complete that request.", maintenance: "Physical library maintenance", editTarget: "Edit {target}", bookcase: "bookcase", shelf: "shelf", container: "container", nameRequired: "Name *", description: "Description", numberRequired: "{target} number *", optionalDimensions: "Optional physical dimensions", height: "Height", width: "Width", depth: "Depth", usableHeight: "Usable height", usableWidth: "Usable width", usableDepth: "Usable depth", cancel: "Cancel", saveChanges: "Save changes", dimensionsMissing: "Dimensions not recorded",
  homogeneousConfirm: "Make this furniture homogeneous? Independent shelf frames and separators will be recalculated when you save. This may move shelf boundaries.", recalculateConfirm: "This recalculates shared shelf geometry. Previewed values will replace the current derived layout only if every shelf fits. Continue?",
  visualWorkspace: "Visual workspace", customizeMap: "Customize library map", expandEditor: "Expand layout editor", minimizeEditor: "Minimize layout editor", expand: "Expand", minimize: "Minimize", cancelEditing: "Cancel layout editing", preciseHelp: "Select one object on the map to reveal its move and resize handles, or use these precise controls. Changes remain a local preview until Apply.",
  geometryMode: "Geometry mode", projection: "Projection", manualProportions: "Manual proportions", physicalDimensions: "Physical dimensions", physicalModeHelp: "Entered exterior furniture and interior shelf measurements govern the projection. Missing axes use labelled fallbacks; invalid structures cannot be applied.", manualModeHelp: "Furniture uses millimetre-shaped map units. Shelf and container controls are percentages of their parent; physical metadata remains informative.",
  furnitureGeometry: "Furniture geometry (mm)", sizeFixed: "Size fixed by recorded physical dimensions.", exteriorBoth: "Exterior width and height", exteriorWidth: "Exterior width", exteriorHeight: "Exterior height", sizeFixedHelp: "{dimensions} cannot be resized on the map. Edit the furniture dimensions in Library layout to change {pronoun}.", horizontalLeft: "Horizontal — left edge", floorBaseline: "Floor baseline", fixedDistribution: "Fixed shelf distribution", topBottom: "Top to bottom", bottomTop: "Bottom to top", leftRight: "Left to right", rightLeft: "Right to left", homogeneous: "Homogeneous structure", sharedStructure: "Shared shelf placement structure", sharedStructureHelp: "Frames and closures position the shelf compartments inside this furniture. Separator thickness controls the distance between consecutive shelves. These values remain editable when shelf width or height is fixed by recorded measurements.", leftFrame: "Left frame", rightFrame: "Right frame", upperClosure: "Upper closure", lowerClosure: "Lower closure / board", separatorThickness: "Separator thickness", fallbackExterior: "Missing exterior measurements use editable fallback map millimetres (2200 × 800 × 280 defaults).",
  shelfCompartment: "Shelf compartment {unit}", chooseShelf: "Choose shelf", noShelves: "This furniture has no shelves", shelfNumber: "Shelf {number}", recordedSizeFixed: "Only the recorded size is fixed.", interiorBoth: "Interior width and height", interiorWidth: "Interior width", interiorHeight: "Interior height", shelfFixedHelp: "{dimensions} cannot be resized on the map. Its position remains editable through {structure}. Edit the physical measurement itself in Library layout.", sharedStructureReference: "the shared frames, closures and separators in Furniture geometry above", independentStructureReference: "the independent shelf structure below", derivedLeft: "Derived left edge (mm)", leftPercent: "Left edge (%)", derivedFloor: "Derived floor baseline (mm)", floorPercent: "Floor baseline (%)", widthPercent: "Width (%)", heightPercent: "Height (%)", sourceSummary: "Left edge and floor baseline are calculated from the placement structure. Width source: {width} · Height source: {height}.", sourceEntered: "entered", sourceFallback: "fallback", sourceDerived: "derived", resetAutomatic: "Reset unmeasured size to automatic fit", openTop: "Open top shelf", independentStructure: "Independent shelf structure", independentHelp: "Frames define this shelf's usable rectangle. Alignment adjustment is retained only for exceptional asymmetric measured shelves.", lowerBoard: "Lower board", followingSeparator: "Following separator", advancedAlignment: "Advanced alignment adjustment", horizontalAlignment: "Horizontal alignment", left: "Left", centre: "Centre", right: "Right", alignmentOffset: "Additional offset", separatorAnchor: "Separator anchor",
  containerGeometry: "Container geometry and support {unit}", chooseContainer: "Choose container", noContainers: "This shelf has no containers", chooseShelfFirst: "Choose a shelf first", backgroundShort: "BG", foregroundShort: "FG", background: "Background", foreground: "Foreground", row: "Row", pile: "Pile", anchorPosition: "Anchor position {unit}", alignmentPosition: "Alignment position {unit}", bottomClearance: "Bottom clearance {unit}", occupiedHelp: "Occupied width and height are derived from the books' physical dimensions and documented fallbacks. Change the anchor, alignment or support here; edit book measurements to change occupied size.", envelopeHelp: "When physical book measurements are unavailable, this editable visual envelope is retained; Manual mode expresses it as percentages. Bottom clearance is relative to the immediate support; zero means physical contact.", depthOffsetHelp: "Only shelf-supported background containers may use a visual depth offset.", rowAnchor: "Row growth anchor", leftGrowRight: "Left edge fixed — grow right", rightGrowLeft: "Right edge fixed — grow left", restsOn: "Rests on", shelfBottom: "Shelf bottom", supportHelp: "Only a non-empty opposite-type container in this shelf and layer can be used.", pileAlignment: "Pile alignment", unmeasuredRow: "Unmeasured row size", unmeasuredRowHelp: "No book in this row has explicit physical dimensions, so its visual envelope may be set manually until measurements become available.", fillShelf: "Fill the complete shelf width",
  outsideAreas: "Outside-library areas (mm)", area: "Area", reading: "Reading", onLoan: "On loan", horizontal: "Horizontal", areaHelp: "Horizontal marks the left edge; Floor baseline marks the bottom edge. Width and Height extend right and upward from those coordinates.", saving: "Saving…", applyLayout: "Apply visual layout",
  layout: "Library layout", loadingPhysical: "Loading physical library…", unavailable: "Physical library unavailable.", sharedPhysical: "Shared physical structure", structure: "Library structure", ownerHelp: "Create, edit or remove furniture, shelves, rows and piles. Use Visual layout only to position and resize their map representation.", viewerHelp: "Read-only physical hierarchy. Your Viewer access includes the Library Map.", visualLayout: "Visual layout",
  addBookcase: "Add bookcase", initialStructure: "Initial structure and dimensions", numberingDirection: "Shelf numbering direction", homogeneousShelf: "Homogeneous shelf structure", exteriorDepth: "Exterior depth", directionHelp: "Direction becomes fixed after the first shelf is added. Blank dimensions use independent map fallbacks and remain physically unrecorded.", addShelf: "Add shelf", chooseBookcase: "Choose bookcase", number: "Number", addContainer: "Add container", type: "Type", layer: "Layer",
  addedBookcase: "Bookcase added.", addedShelf: "Shelf added.", addedContainer: "Container added.", updated: "Physical library updated.", layoutSaved: "Visual layout saved.", deleteConfirm: "Delete {label}? BOOKPILE will refuse if it still contains other physical-library records.", deleted: "{label} deleted.", bookCount: "{count} book", booksCount: "{count} books", shelfCount: "{count} shelf", shelvesCount: "{count} shelves", editBookcase: "Edit bookcase", deleteBookcase: "Delete bookcase", editShelf: "Edit shelf", deleteShelf: "Delete shelf", editContainer: "Edit container", deleteContainer: "Delete container", noStructure: "No physical structure yet", addFirst: "Add the first bookcase above.", ownersNotConfigured: "The Owners have not configured the Library Map yet.",
} as const;
export type PhysicalCopyKey = keyof typeof en;
const gl = {
  requestFailed: "BOOKPILE non puido completar esa solicitude.", maintenance: "Mantemento da biblioteca física", editTarget: "Editar {target}", bookcase: "moble", shelf: "andel", container: "contedor", nameRequired: "Nome *", description: "Descrición", numberRequired: "Número de {target} *", optionalDimensions: "Dimensións físicas opcionais", height: "Altura", width: "Anchura", depth: "Profundidade", usableHeight: "Altura útil", usableWidth: "Anchura útil", usableDepth: "Profundidade útil", cancel: "Cancelar", saveChanges: "Gardar cambios", dimensionsMissing: "Dimensións sen rexistrar",
  homogeneousConfirm: "Facer homoxéneo este moble? Os marcos e separadores independentes dos andeis recalcularanse ao gardar. Isto pode mover os límites dos andeis.", recalculateConfirm: "Isto recalcula a xeometría compartida dos andeis. Os valores previsualizados substituirán a disposición derivada actual só se caben todos os andeis. Continuar?",
  visualWorkspace: "Espazo de traballo visual", customizeMap: "Personalizar mapa da biblioteca", expandEditor: "Expandir editor da disposición", minimizeEditor: "Minimizar editor da disposición", expand: "Expandir", minimize: "Minimizar", cancelEditing: "Cancelar edición da disposición", preciseHelp: "Selecciona un obxecto no mapa para mostrar os controis de movemento e tamaño, ou usa estes controis precisos. Os cambios son unha previsualización local ata que premas Aplicar.",
  geometryMode: "Modo de xeometría", projection: "Proxección", manualProportions: "Proporcións manuais", physicalDimensions: "Dimensións físicas", physicalModeHelp: "As medidas exteriores dos mobles e interiores dos andeis determinan a proxección. Os eixes sen datos usan estimacións identificadas; non se poden aplicar estruturas inválidas.", manualModeHelp: "Os mobles usan unidades de mapa con forma de milímetros. Os controis de andeis e contedores son porcentaxes do elemento pai; os metadatos físicos seguen sendo informativos.",
  furnitureGeometry: "Xeometría do moble (mm)", sizeFixed: "Tamaño fixado polas dimensións físicas rexistradas.", exteriorBoth: "A anchura e altura exteriores", exteriorWidth: "A anchura exterior", exteriorHeight: "A altura exterior", sizeFixedHelp: "{dimensions} non se pode cambiar no mapa. Edita as dimensións do moble en Disposición da biblioteca para cambialas.", horizontalLeft: "Horizontal — bordo esquerdo", floorBaseline: "Liña base do chan", fixedDistribution: "Distribución fixa dos andeis", topBottom: "De arriba abaixo", bottomTop: "De abaixo arriba", leftRight: "De esquerda a dereita", rightLeft: "De dereita a esquerda", homogeneous: "Estrutura homoxénea", sharedStructure: "Estrutura compartida de colocación dos andeis", sharedStructureHelp: "Os marcos e peches sitúan os compartimentos dos andeis dentro do moble. O grosor do separador controla a distancia entre andeis consecutivos. Estes valores seguen editables cando a anchura ou altura do andel está fixada por medidas rexistradas.", leftFrame: "Marco esquerdo", rightFrame: "Marco dereito", upperClosure: "Peche superior", lowerClosure: "Peche / táboa inferior", separatorThickness: "Grosor do separador", fallbackExterior: "As medidas exteriores ausentes usan milímetros de mapa estimados e editables (valores predeterminados 2200 × 800 × 280).",
  shelfCompartment: "Compartimento do andel {unit}", chooseShelf: "Escoller andel", noShelves: "Este moble non ten andeis", shelfNumber: "Andel {number}", recordedSizeFixed: "Só está fixado o tamaño rexistrado.", interiorBoth: "A anchura e altura interiores", interiorWidth: "A anchura interior", interiorHeight: "A altura interior", shelfFixedHelp: "{dimensions} non se pode cambiar no mapa. A súa posición segue editable mediante {structure}. Edita a propia medida física en Disposición da biblioteca.", sharedStructureReference: "os marcos, peches e separadores compartidos da Xeometría do moble", independentStructureReference: "a estrutura independente do andel inferior", derivedLeft: "Bordo esquerdo derivado (mm)", leftPercent: "Bordo esquerdo (%)", derivedFloor: "Liña base derivada (mm)", floorPercent: "Liña base (%)", widthPercent: "Anchura (%)", heightPercent: "Altura (%)", sourceSummary: "O bordo esquerdo e a liña base calcúlanse coa estrutura de colocación. Orixe da anchura: {width} · Orixe da altura: {height}.", sourceEntered: "introducida", sourceFallback: "estimada", sourceDerived: "derivada", resetAutomatic: "Restablecer o tamaño non medido ao axuste automático", openTop: "Andel superior aberto", independentStructure: "Estrutura independente do andel", independentHelp: "Os marcos definen o rectángulo útil deste andel. O axuste de aliñamento consérvase só para andeis medidos asimétricos excepcionais.", lowerBoard: "Táboa inferior", followingSeparator: "Separador seguinte", advancedAlignment: "Axuste avanzado do aliñamento", horizontalAlignment: "Aliñamento horizontal", left: "Esquerda", centre: "Centro", right: "Dereita", alignmentOffset: "Desprazamento adicional", separatorAnchor: "Referencia do separador",
  containerGeometry: "Xeometría e soporte do contedor {unit}", chooseContainer: "Escoller contedor", noContainers: "Este andel non ten contedores", chooseShelfFirst: "Escolle primeiro un andel", backgroundShort: "F", foregroundShort: "PP", background: "Fondo", foreground: "Primeiro plano", row: "Fila", pile: "Pila", anchorPosition: "Posición da referencia {unit}", alignmentPosition: "Posición do aliñamento {unit}", bottomClearance: "Separación inferior {unit}", occupiedHelp: "A anchura e altura ocupadas derívanse das dimensións físicas dos libros e das estimacións documentadas. Cambia aquí a referencia, o aliñamento ou o soporte; edita as medidas dos libros para cambiar o tamaño ocupado.", envelopeHelp: "Se non hai medidas físicas dos libros, consérvase esta envolvente visual editable; o modo manual exprésaa en porcentaxes. A separación inferior é relativa ao soporte inmediato; cero significa contacto físico.", depthOffsetHelp: "Só os contedores de fondo apoiados no andel poden usar un desprazamento visual de profundidade.", rowAnchor: "Referencia de crecemento da fila", leftGrowRight: "Bordo esquerdo fixo — medra á dereita", rightGrowLeft: "Bordo dereito fixo — medra á esquerda", restsOn: "Apóiase en", shelfBottom: "Fondo do andel", supportHelp: "Só se pode usar un contedor non baleiro do tipo oposto neste andel e capa.", pileAlignment: "Aliñamento da pila", unmeasuredRow: "Tamaño da fila sen medir", unmeasuredRowHelp: "Ningún libro desta fila ten dimensións físicas explícitas, polo que a súa envolvente visual pode establecerse manualmente ata dispoñer de medidas.", fillShelf: "Ocupar toda a anchura do andel",
  outsideAreas: "Áreas fóra da biblioteca (mm)", area: "Área", reading: "En lectura", onLoan: "Prestado", horizontal: "Horizontal", areaHelp: "Horizontal marca o bordo esquerdo; Liña base marca o bordo inferior. Anchura e Altura esténdense á dereita e cara arriba desde esas coordenadas.", saving: "Gardando…", applyLayout: "Aplicar disposición visual",
  layout: "Disposición da biblioteca", loadingPhysical: "Cargando a biblioteca física…", unavailable: "A biblioteca física non está dispoñible.", sharedPhysical: "Estrutura física compartida", structure: "Estrutura da biblioteca", ownerHelp: "Crea, edita ou elimina mobles, andeis, filas e pilas. Usa Disposición visual só para situar e redimensionar a súa representación no mapa.", viewerHelp: "Xerarquía física de só lectura. O teu acceso como visitante inclúe o mapa da biblioteca.", visualLayout: "Disposición visual",
  addBookcase: "Engadir moble", initialStructure: "Estrutura e dimensións iniciais", numberingDirection: "Dirección de numeración dos andeis", homogeneousShelf: "Estrutura homoxénea dos andeis", exteriorDepth: "Profundidade exterior", directionHelp: "A dirección queda fixada ao engadir o primeiro andel. As dimensións baleiras usan estimacións independentes no mapa e non se rexistran como medidas físicas.", addShelf: "Engadir andel", chooseBookcase: "Escoller moble", number: "Número", addContainer: "Engadir contedor", type: "Tipo", layer: "Capa",
  addedBookcase: "Engadiuse o moble.", addedShelf: "Engadiuse o andel.", addedContainer: "Engadiuse o contedor.", updated: "Actualizouse a biblioteca física.", layoutSaved: "Gardouse a disposición visual.", deleteConfirm: "Eliminar {label}? BOOKPILE rexeitará a operación se aínda contén outros rexistros da biblioteca física.", deleted: "Eliminouse {label}.", bookCount: "{count} libro", booksCount: "{count} libros", shelfCount: "{count} andel", shelvesCount: "{count} andeis", editBookcase: "Editar moble", deleteBookcase: "Eliminar moble", editShelf: "Editar andel", deleteShelf: "Eliminar andel", editContainer: "Editar contedor", deleteContainer: "Eliminar contedor", noStructure: "Aínda non hai estrutura física", addFirst: "Engade arriba o primeiro moble.", ownersNotConfigured: "As persoas propietarias aínda non configuraron o mapa da biblioteca.",
} satisfies Record<PhysicalCopyKey, string>;

export type PhysicalCopy = (key: PhysicalCopyKey, values?: Record<string, string | number>) => string;
const catalogues: Record<AppLocale, Record<PhysicalCopyKey, string>> = { en, gl };
export function physicalCopy(locale: AppLocale): PhysicalCopy {
  const catalogue = catalogues[locale];
  return (key, values = {}) => catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? String(values[name]) : token);
}
