import type { AppLocale } from "./locale";

export const en = {
  requestFailed: "BOOKPILE could not complete that request.", maintenance: "Physical library maintenance", editTarget: "Edit {target}", bookcase: "bookcase", shelf: "shelf", container: "container", nameRequired: "Name *", description: "Description", numberRequired: "{target} number *", optionalDimensions: "Optional physical dimensions", height: "Height", width: "Width", depth: "Depth", usableHeight: "Usable height", usableWidth: "Usable width", usableDepth: "Usable depth", cancel: "Cancel", saveChanges: "Save changes", dimensionsMissing: "Dimensions not recorded",
  homogeneousConfirm: "Make this furniture homogeneous? Independent shelf frames and separators will be recalculated when you save. This may move shelf boundaries.", recalculateConfirm: "This recalculates shared shelf geometry. Previewed values will replace the current derived layout only if every shelf fits. Continue?",
  visualWorkspace: "Visual workspace", customizeMap: "Customize library map", expandEditor: "Expand layout editor", minimizeEditor: "Minimize layout editor", expand: "Expand", minimize: "Minimize", cancelEditing: "Cancel layout editing", preciseHelp: "Select one object on the map to reveal its move and resize handles, or use these precise controls. Changes remain a local preview until Apply.",
  geometryMode: "Geometry mode", projection: "Projection", manualProportions: "Manual proportions", physicalDimensions: "Physical dimensions", physicalModeHelp: "Entered exterior furniture and interior shelf measurements govern the projection. Missing axes use labelled fallbacks; invalid structures cannot be applied.", manualModeHelp: "Furniture uses millimetre-shaped map units. Shelf and container controls are percentages of their parent; physical metadata remains informative.",
  furnitureGeometry: "Furniture geometry (mm)", sizeFixed: "Size fixed by recorded physical dimensions.", exteriorBoth: "Exterior width and height", exteriorWidth: "Exterior width", exteriorHeight: "Exterior height", sizeFixedHelp: "{dimensions} cannot be resized on the map. Edit the furniture dimensions in Library layout to change {pronoun}.", horizontalLeft: "Horizontal — left edge", floorBaseline: "Floor baseline", fixedDistribution: "Fixed shelf distribution", topBottom: "Top to bottom", bottomTop: "Bottom to top", leftRight: "Left to right", rightLeft: "Right to left", homogeneous: "Homogeneous structure", sharedStructure: "Shared shelf placement structure", sharedStructureHelp: "Frames and closures position the shelf compartments inside this furniture. Separator thickness controls the distance between consecutive shelves. These values remain editable when shelf width or height is fixed by recorded measurements.", leftFrame: "Left frame", rightFrame: "Right frame", upperClosure: "Upper closure", lowerClosure: "Lower closure / board", separatorThickness: "Separator thickness", fallbackExterior: "Missing exterior measurements use editable fallback map millimetres (2200 × 800 × 280 defaults).",
  shelfCompartment: "Shelf compartment {unit}", chooseShelf: "Choose shelf", noShelves: "This furniture has no shelves", shelfNumber: "Shelf {number}", recordedSizeFixed: "Only the recorded size is fixed.", interiorBoth: "Interior width and height", interiorWidth: "Interior width", interiorHeight: "Interior height", shelfFixedHelp: "{dimensions} cannot be resized on the map. Its position remains editable through {structure}. Edit the physical measurement itself in Library layout.", sharedStructureReference: "the shared frames, closures and separators in Furniture geometry above", independentStructureReference: "the independent shelf structure below", derivedLeft: "Derived left edge (mm)", leftPercent: "Left edge (%)", derivedFloor: "Derived floor baseline (mm)", floorPercent: "Floor baseline (%)", widthPercent: "Width (%)", heightPercent: "Height (%)", sourceSummary: "Left edge and floor baseline are calculated from the placement structure. Width source: {width} · Height source: {height}.", sourceEntered: "entered", sourceFallback: "fallback", sourceDerived: "derived", resetAutomatic: "Reset unmeasured size to automatic fit", openTop: "Open top shelf", independentStructure: "Independent shelf structure", independentHelp: "Frames define this shelf's usable rectangle. Alignment adjustment is retained only for exceptional asymmetric measured shelves.", lowerBoard: "Lower board", followingSeparator: "Following separator", advancedAlignment: "Advanced alignment adjustment", horizontalAlignment: "Horizontal alignment", left: "Left", centre: "Centre", right: "Right", alignmentOffset: "Additional offset", separatorAnchor: "Separator anchor",
  containerGeometry: "Container geometry and support {unit}", chooseContainer: "Choose container", noContainers: "This shelf has no containers", chooseShelfFirst: "Choose a shelf first", backgroundShort: "BG", foregroundShort: "FG", background: "Background", foreground: "Foreground", row: "Row", pile: "Pile", anchorPosition: "Anchor position {unit}", alignmentPosition: "Alignment position {unit}", bottomClearance: "Bottom clearance {unit}", occupiedHelp: "Occupied width and height are derived from the books' physical dimensions and documented fallbacks. Change the anchor, alignment or support here; edit book measurements to change occupied size.", envelopeHelp: "When physical book measurements are unavailable, this editable visual envelope is retained; Manual mode expresses it as percentages. Bottom clearance is relative to the immediate support; zero means physical contact.", depthOffsetHelp: "Only shelf-supported background containers may use a visual depth offset.", rowAnchor: "Row growth anchor", leftGrowRight: "Left edge fixed — grow right", rightGrowLeft: "Right edge fixed — grow left", restsOn: "Rests on", shelfBottom: "Shelf bottom", supportHelp: "Only a non-empty opposite-type container in this shelf and layer can be used.", pileAlignment: "Pile alignment", unmeasuredRow: "Unmeasured row size", unmeasuredRowHelp: "No book in this row has explicit physical dimensions, so its visual envelope may be set manually until measurements become available.", fillShelf: "Fill the complete shelf width",
  outsideAreas: "Outside-library areas (mm)", area: "Area", reading: "Reading", onLoan: "On loan", horizontal: "Horizontal", areaHelp: "Horizontal marks the left edge; Floor baseline marks the bottom edge. Width and Height extend right and upward from those coordinates.", saving: "Saving…", applyLayout: "Apply visual layout",
  layout: "Library layout", loadingPhysical: "Loading physical library…", unavailable: "Physical library unavailable.", sharedPhysical: "Shared physical structure", structure: "Library structure", ownerHelp: "Create, edit or remove furniture, shelves, rows and piles. Use Visual layout only to position and resize their map representation.", viewerHelp: "Read-only physical hierarchy. Your Viewer access includes the Library Map.", visualLayout: "Visual layout",
  addBookcase: "Add bookcase", initialStructure: "Initial structure and dimensions", numberingDirection: "Shelf numbering direction", homogeneousShelf: "Homogeneous shelf structure", exteriorDepth: "Exterior depth", directionHelp: "Direction becomes fixed after the first shelf is added. Blank dimensions use independent map fallbacks and remain physically unrecorded.", addShelf: "Add shelf", chooseBookcase: "Choose bookcase", number: "Number", addContainer: "Add container", type: "Type", layer: "Layer",
  addedBookcase: "Bookcase added.", addedShelf: "Shelf added.", addedContainer: "Container added.", updated: "Physical library updated.", layoutSaved: "Visual layout saved.", deleteConfirm: "Delete {label}? BOOKPILE will refuse if it still contains other physical-library records.", deleted: "{label} deleted.", bookCount: "{count} book", booksCount: "{count} books", shelfCount: "{count} shelf", shelvesCount: "{count} shelves", editBookcase: "Edit bookcase", deleteBookcase: "Delete bookcase", editShelf: "Edit shelf", deleteShelf: "Delete shelf", editContainer: "Edit container", deleteContainer: "Delete container", noStructure: "No physical structure yet", addFirst: "Add the first bookcase above.", ownersNotConfigured: "The Owners have not configured the Library Map yet.",
} as const;
export type PhysicalCopyKey = keyof typeof en;



export type PhysicalCopy = (key: PhysicalCopyKey, values?: Record<string, string | number>) => string;
const catalogues: Partial<Record<AppLocale, Record<PhysicalCopyKey, string>>> = { en };

export function registerPhysicalCatalogue(
  locale: AppLocale,
  catalogue: Record<PhysicalCopyKey, string>,
): void {
  catalogues[locale] = catalogue;
}
export function physicalCopy(locale: AppLocale): PhysicalCopy {
  const catalogue = catalogues[locale];
  if (!catalogue) throw new Error(`Locale catalogue not loaded: ${locale}`);
  return (key, values = {}) => catalogue[key].replace(/\{(\w+)\}/g, (token, name: string) => Object.hasOwn(values, name) ? String(values[name]) : token);
}
