import type { CatalogueCopyKey } from "../../catalogueCopy";

export const cataloguePt = {
  serverUnavailable: "O BOOKPILE não conseguiu ligar ao servidor. Tente novamente.", coverOf: "Capa de {title}", shelf: "Prateleira", background: "Fundo", foreground: "Primeiro plano", row: "Fila", pile: "Pilha", position: "Posição",
  contributorRolesUnavailable: "As funções de colaboração não estão disponíveis. Recarregue a página e tente novamente.",
  noSuggestedBooks: "Não existem livros pendentes disponíveis que correspondam aos filtros atuais do catálogo.", privateCatalogue: "Catálogo privado", sharedCatalogue: "Catálogo partilhado", yourBooks: "Os seus livros", usersBooks: "Livros de {username}", owner: "Proprietário/a", viewer: "Visitante", memberCount: "{count} membros", book: "livro", books: "livros", match: "correspondência", newRead: "Nova leitura", add: "Adicionar", addSingleBook: "Adicionar um livro", batchAdd: "Adicionar em lote", scanSingleBarcode: "Ler um código de barras", batchScan: "Ler em lote", readingSuggestion: "Sugestão de leitura", another: "Outra", startReading: "Começar a ler", closeSuggestion: "Fechar sugestão", readingSummary: "Resumo de leitura do catálogo", totalBooks: "Total de livros", waitingToRead: "Por ler", currentlyReading: "Em leitura", read: "Lidos",
  searchPlaceholder: "Pesquisar por título, autoria, colaborador ou série", searchCatalogue: "Pesquisar no catálogo", sort: "Ordenar", sortCatalogue: "Ordenar catálogo", advancedSort: "Ordenação avançada", title: "Título", author: "Autoria", physicalLocation: "Localização física", advanced: "Avançado", languages: "Idiomas", originalLanguages: "Idiomas originais", genres: "Géneros", publishers: "Editoras", series: "Séries", translation: "Tradução", category: "Categoria", binding: "Encadernação", publicationType: "Tipo de publicação", unknown: "Desconhecido", original: "Original", translated: "Traduzido", fiction: "Ficção", nonFiction: "Não ficção", hardcover: "Capa dura", paperback: "Capa mole", flexibound: "Capa flexível", spiral: "Espiral", stapled: "Agrafado", other: "Outro", conventionalBook: "Livro convencional", comicGraphicNovel: "Banda desenhada / romance gráfico", atlas: "Atlas", reference: "Consulta", artPhotographyIllustrated: "Arte / fotografia / ilustrado", magazinePeriodical: "Revista / publicação periódica", seriesMembership: "Pertença a uma série", any: "Qualquer", inSeries: "Numa série", notInSeries: "Fora de uma série", authors: "Autorias", singleAuthor: "Uma autoria", multipleAuthors: "Várias autorias", minimumPages: "Mínimo de páginas", maximumPages: "Máximo de páginas", yearField: "Campo de ano", currentEdition: "Edição atual", originalPublication: "Publicação original", minimumYear: "Ano mínimo", maximumYear: "Ano máximo",
  personalReadingState: "Estado pessoal de leitura", pending: "Pendente", activeReading: "Em leitura — qualquer leitura ativa", firstReading: "Em leitura — primeira vez", rereadingNow: "Em releitura", readInactive: "Lido — sem leitura ativa", rereadingHistory: "Histórico de releituras", hasBeenReread: "Foi relido", hasNotBeenReread: "Não foi relido", readingDate: "Data de leitura", readingStarted: "Início da leitura", finishedReading: "Fim da leitura", readingDateFrom: "Data de leitura desde", readingDateTo: "Data de leitura até",
  loanHistory: "Histórico de empréstimos", currentlyOnLoan: "Atualmente emprestado", overdue: "Em atraso", everLoaned: "Emprestado alguma vez", neverLoaned: "Nunca emprestado", borrowerContains: "O nome de quem pediu contém", loanDate: "Data do empréstimo", loaned: "Emprestado", expectedReturn: "Devolução prevista", returned: "Devolvido", loanDateFrom: "Data do empréstimo desde", loanDateTo: "Data do empréstimo até",
  sortBy: "Ordenar por", dateAdded: "Data de adição", lastUpdated: "Última atualização", pages: "Páginas", publisher: "Editora", editionYear: "Ano da edição", originalYear: "Ano original", acquisitionDate: "Data de aquisição", loanedDate: "Data do empréstimo", ascending: "Ascendente", descending: "Descendente", direction: "Direção", clear: "Limpar", applyFilters: "Aplicar filtros",
  onLoanTo: "Emprestado a {borrower}", onLoan: "Emprestado", returnsTo: "regressa a {location}", beingRead: "Em leitura", noPhysicalLocation: "Sem localização física", pageCount: "{count} páginas", noOptionalMetadata: "Não foram registados metadados opcionais", completeInformation: "Informação completa", goodreadsReview: "Crítica de {username} no Goodreads", myReading: "A minha leitura", manageLoan: "Gerir ou devolver empréstimo", loanBook: "Emprestar este livro", editBookLocation: "Editar livro e localização física", delete: "Eliminar",
  everyBookPlace: "Um lugar para cada livro", buildPhysicalLibrary: "Construa a sua biblioteca física",
  mapOnboarding: "O mapa do BOOKPILE liga cada registo do catálogo ao seu lugar real. É opcional, mas dedicar agora alguns minutos a definir os móveis, as prateleiras e os contentores tornará muito mais fácil adicionar e encontrar livros.", setUpMap: "Configurar o mapa da biblioteca", skipMap: "Também pode ignorá-lo e adicionar livros diretamente quando preferir.", noBooksMatch: "Nenhum livro corresponde", tryAnotherFilter: "Experimente outra página ou outro filtro.", noCatalogueRecords: "Esta biblioteca ainda não tem registos no catálogo.", cataloguePages: "Páginas do catálogo", previous: "Anterior", next: "Seguinte", close: "Fechar", readOnlyRecord: "Registo de catálogo apenas de leitura", contributors: "Colaboradores", selectedOwner: "Proprietário selecionado", notRecorded: "Não registado",
  editBook: "Editar livro", subtitle: "Subtítulo", isbn10: "ISBN-10", isbn13: "ISBN-13", currentEditionYear: "Ano da edição atual", originalPublicationYear: "Ano da publicação original", language: "Idioma", originalLanguage: "Idioma original", edition: "Edição", seriesVolume: "Volume da série", acquired: "Adquirido", originalCollection: "Coleção original", height: "Altura", width: "Largura", thickness: "Espessura", notes: "Notas", chooseTransferValues: "Escolha os valores que pretende transferir", transferNoneAutomatic: "Nada é selecionado ou guardado automaticamente.", applyMetadata: "Aplicar metadados selecionados",
  batchCataloguing: "Catalogação em lote", sharedRecord: "Registo de catálogo partilhado", addNextBook: "Adicionar o livro seguinte", addBook: "Adicionar um livro", batchCountOne: "Foi adicionado {count} livro neste lote.", batchCountMany: "Foram adicionados {count} livros neste lote.", batchHelp: "Depois de guardar, o BOOKPILE limpa os dados do livro, mas conserva este contentor e sugere a posição seguinte.",
  identifyIsbn: "Identificar por ISBN ou código de barras", barcodePrivacy: "A fotografia do código de barras é descodificada neste dispositivo e descartada imediatamente. Reveja os valores do fornecedor antes de os transferir.", enterIsbn: "Introduza ou leia primeiro um ISBN.", lookingUp: "A pesquisar…", lookupIsbn: "Pesquisar ISBN", readingPhoto: "A ler fotografia…", takeBarcodePhoto: "Fotografar o código de barras", isbnAlreadyPresent: "Este ISBN já existe na biblioteca", noBibliographicRecord: "Não foi encontrado nenhum registo bibliográfico. Pode continuar manualmente.",
  requiredInformation: "Informação obrigatória", titleRequired: "Título *", authorDisplayRequired: "Autoria apresentada *", privateCover: "Imagem de capa privada", coverPrivacy: "Só é visível para os membros desta biblioteca com sessão iniciada. O BOOKPILE descarta o original depois de remover os metadados e criar uma cópia WebP privada.", storedCover: "Capa privada guardada", noCover: "Nenhuma capa selecionada", chooseCover: "Fotografar ou escolher capa", removeCover: "Remover capa", keepCover: "Conservar capa existente",
  contributorHelp: "Adicione autores, tradutores, ilustradores e outras funções creditadas pela ordem em que são apresentados.", contributorName: "Nome do colaborador", moveUp: "Subir", moveDown: "Descer", removeContributor: "Remover colaborador", addContributor: "Adicionar colaborador", editionClassification: "Edição e classificação", editionNumber: "Número da edição", commaSeparated: "Separado por vírgulas", languageTranslation: "Idioma e tradução", translationStatus: "Estado da tradução", originalLanguageValue: "Idioma original", identifiers: "Identificadores", copyDetails: "Dados do exemplar",
  physicalLocationHelp: "Opcional. Uma posição ocupada cria espaço automaticamente; ao mover um livro, o contentor anterior é compactado.", bookcase: "Móvel", chooseShelf: "Escolher prateleira", container: "Contentor", chooseContainer: "Escolher contentor", libraryNotes: "Notas da biblioteca", optional: "opcional",
  initialReadingHelp: "Adicione o seu próprio registo de leitura e crítica do Goodreads ao criar este registo de catálogo partilhado. Estes valores são pessoais e são limpos antes do livro seguinte adicionado em lote.", readingRecord: "Registo de leitura", noReadingRecord: "Sem registo de leitura", historicalCompleted: "Leitura histórica — terminada", activeStarted: "Em leitura — iniciada", readingDatesUnknown: "Datas de leitura desconhecidas", started: "Início", finished: "Fim", goodreadsUrl: "URL da minha crítica no Goodreads",
  currentLoan: "Empréstimo atual", copyCurrentlyLoaned: "Este exemplar físico está atualmente emprestado", retainedPositionHelp: "A posição reservada na prateleira é conservada enquanto o exemplar aparece na área partilhada de empréstimos.", loanedToRequired: "Emprestado a *", loanDateLabel: "Data do empréstimo", optionalUnknown: "opcional / desconhecida", expectedReturnLabel: "Devolução prevista", privateOwnerNotes: "Notas privadas das pessoas proprietárias",
  processingPhotoHelp: "As fotografias grandes do telemóvel podem demorar vários segundos. Mantenha esta janela aberta.", finishBatch: "Terminar lote", cancel: "Cancelar", pleaseWait: "Aguarde…", saveScanNext: "Guardar e ler o seguinte", saveAddNext: "Guardar e adicionar o seguinte", saveBook: "Guardar livro", barcodeReadingLocally: "A ler o código de barras localmente…", checkingSources: "A consultar fontes bibliográficas e esta biblioteca…", selectedCoverPreview: "Pré-visualização da capa selecionada", loanReadingConflict: "Um exemplar não pode estar emprestado e em leitura ativa ao mesmo tempo.", processingCover: "A processar capa privada…", removingCover: "A remover capa privada…", savingGoodreads: "A guardar a sua crítica no Goodreads…", savingReadingHistory: "A guardar o seu histórico de leitura…", startingReading: "A iniciar a sua leitura…",
  partialSave: "O livro partilhado e a respetiva localização foram guardados, mas alguns dados da capa privada ou da leitura pessoal falharam. {error} Corrija-os e tente novamente: o BOOKPILE atualizará este livro em vez de criar um duplicado.", savedNext: "«{title}» guardado. Tudo pronto para o livro seguinte.", bookSaved: "Livro e capa privada guardados.", bookUpdated: "Livro atualizado.", deleteBookConfirm: "Eliminar definitivamente «{title}»? Esta ação não pode ser anulada.", bookDeleted: "Livro eliminado definitivamente.", personalDataUpdated: "Dados pessoais de leitura atualizados.", loanDataUpdated: "Dados partilhados do empréstimo atualizados.",
} satisfies Record<CatalogueCopyKey, string>;

