import type { MapCopyKey } from "../../mapCopy";

export const mapGl = {
  unavailable: "O mapa da biblioteca non está dispoñible.", bookUnavailable: "A información do libro non está dispoñible.", previewFailed: "Non se puido previsualizar o destino.", undoFailed: "Non se puido desfacer.", applyFailed: "Non se puido aplicar a reorganización.", loading: "Cargando o mapa da biblioteca…",
  visualIndex: "Índice visual da biblioteca", libraryMap: "Mapa da biblioteca", backCatalogue: "Volver ao catálogo", catalogue: "Catálogo", reorganize: "Reorganizar libros", editLayout: "Editar disposición", chooseInspection: "Escoller modo de inspección", books: "Libros", containers: "Contedores", inspectionMode: "Modo de inspección: {mode}. Toca para cambiar.",
  colourBy: "Cor segundo", genre: "Xénero", publisher: "Editorial", author: "Autoría", choose: "Escoller…", perspectiveColours: "As cores mostran a perspectiva de {username}. A custodia física é compartida.",
  dragObject: "Arrastrar o obxecto seleccionado", resizeObject: "Redimensionar o obxecto seleccionado", cameraControls: "Controis da cámara do mapa", resetView: "Restablecer vista", zoomIn: "Achegar", zoomOut: "Afastar",
  draftMovement: "Movemento en borrador", chooseBook: "Escoller un libro", chooseBookMap: "Escolle un libro no mapa", expandDraft: "Expandir borrador", collapseDraft: "Contraer borrador", expand: "Expandir", collapse: "Contraer", cancelDraft: "Cancelar borrador",
  oldPosition: "Posición anterior", newPosition: "Posición nova", collapsePosition: "Compactar", leaveGap: "Deixar o oco", squeeze: "Apertar", swap: "Intercambiar", continue: "Continuar", releaseSpace: "Liberar espazo no andel se este movemento retira páxinas do contedor de orixe",
  book: "Libro", chooseMapHere: "Escoller no mapa ou aquí", destinationContainer: "Contedor de destino", shelf: "Andel", background: "Fondo", foreground: "Primeiro plano", row: "Fila", pile: "Pila", position: "Posición", previewDestination: "Previsualizar destino", moveNumber: "Movemento {number}", unchangedDraft: "Este borrador produce a mesma disposición. Engade outro movemento ou cancélao.", undo: "Desfacer último paso", addMove: "Engadir outro movemento", apply: "Aplicar",
  bookMoved: "«{title}»: {source} → {destination}", bookShifted: "Desprazouse {count} libro {reason}.", booksShifted: "Desprazáronse {count} libros {reason}.", occupyGap: "para ocupar o oco", fillGapAndMakeRoom: "para encher o oco e crear espazo novo", makeRoom: "para crear espazo", continueWithBook: "Continúa con «{title}».", noStackingCapacity: "{container} non ten capacidade libre no eixe de apilamento.", booksCompressed: "{container} comprimirá os seus libros un {percent}%.", insufficientCapacity: "{container} precisa un {needed}%, pero só hai un {available}% dispoñible.", unknownScale: "{container} non tiña unha escala coñecida; o primeiro libro usa o 10% do espazo dispoñible.", layoutConflict: "A disposición proxectada entra en conflito con outro elemento físico.", rearrangementWarning: "O movemento require atención antes de poder aplicalo.",
  clearSelection: "Limpar selección", selectedBook: "Libro seleccionado", pages: "{count} páxinas", unknownPages: "Número de páxinas descoñecido · estimación visual de {count} páxinas", selectedContainer: "Contedor seleccionado", bookCount: "{count} libro", booksCount: "{count} libros", focusContainer: "Enfocar contedor", loadingDetails: "Cargando…", completeInformation: "Información completa", readOnlyInspection: "Inspección de só lectura",
  readingStatus: "Estado de lectura", acquisitionRecency: "Antigüidade da adquisición", readingRecency: "Antigüidade da lectura", pendingDuration: "Tempo pendente", readingDuration: "Duración da lectura", readingRate: "Ritmo de lectura (páxinas/día)", language: "Idioma", originalLanguage: "Idioma orixinal", translationStatus: "Estado da tradución", editionYear: "Ano da edición actual", originalYear: "Ano de publicación orixinal", genreFocus: "Xénero destacado", publisherFocus: "Editorial destacada", authorFocus: "Autoría destacada", fictionCategory: "Ficción / non ficción", binding: "Encadernación", publicationType: "Tipo de publicación",
  pending: "Pendente", reading: "En lectura", onLoan: "Prestado", physicalCopyReading: "Este exemplar físico está en lectura", physicalCopyOnLoan: "Este exemplar físico está prestado", rereading: "En relectura", read: "Lido", notSelected: "Non seleccionado", otherBooks: "Outros libros", chooseFocus: "Escoller {mode}", notRecorded: "Sen rexistrar", originalCollection: "Colección orixinal", noAcquisitionDate: "Sen data de adquisición", stillReading: "Aínda en lectura", stillRereading: "Aínda en relectura", readNoData: "Lido · sen datos", noData: "Sen datos", days: "{count} días", pagesPerDay: "{count} páxinas/día", noRecordedData: "Non hai datos rexistrados", shortest: "Máis breve", longest: "Máis longo", slowest: "Máis lento", fastest: "Máis rápido", oldest: "Máis antigo", newest: "Máis recente", endpointOne: "{adjective}: «{title}» · {value}", endpointTie: "{adjective}: empate ({count}) · {value}",
} satisfies Record<MapCopyKey, string>;
