import type { MapCopyKey } from "../../mapCopy";

export const mapEs = {
  unavailable: "El mapa de la biblioteca no está disponible.", bookUnavailable: "La información del libro no está disponible.", previewFailed: "No se ha podido previsualizar el destino.", undoFailed: "No se ha podido deshacer.", applyFailed: "No se ha podido aplicar la reorganización.", loading: "Cargando el mapa de la biblioteca…",
  visualIndex: "Índice visual de la biblioteca", libraryMap: "Mapa de la biblioteca", backCatalogue: "Volver al catálogo", catalogue: "Catálogo", reorganize: "Reorganizar libros", editLayout: "Editar disposición", chooseInspection: "Elegir modo de inspección", books: "Libros", containers: "Contenedores", inspectionMode: "Modo de inspección: {mode}. Toca para cambiar.",
  colourBy: "Colorear por", genre: "Género", publisher: "Editorial", author: "Autoría", choose: "Elegir…", perspectiveColours: "Los colores muestran la perspectiva de {username}. La custodia física es compartida.",
  dragObject: "Arrastrar objeto seleccionado", resizeObject: "Cambiar tamaño del objeto seleccionado", cameraControls: "Controles de cámara del mapa", resetView: "Restablecer vista", zoomIn: "Acercar", zoomOut: "Alejar",
  draftMovement: "Movimiento provisional", chooseBook: "Elegir un libro", chooseBookMap: "Elegir un libro en el mapa", expandDraft: "Expandir borrador", collapseDraft: "Contraer borrador", expand: "Expandir", collapse: "Contraer", cancelDraft: "Cancelar borrador",
  oldPosition: "Posición anterior", newPosition: "Posición nueva", collapsePosition: "Compactar", leaveGap: "Dejar hueco", squeeze: "Comprimir", swap: "Intercambiar", continue: "Continuar", releaseSpace: "Liberar espacio del estante si este movimiento retira páginas de su contenedor de origen",
  book: "Libro", chooseMapHere: "Elegir en el mapa o aquí", destinationContainer: "Contenedor de destino", shelf: "Estante", background: "Fondo", foreground: "Primer plano", row: "Fila", pile: "Pila", position: "Posición", previewDestination: "Previsualizar destino", moveNumber: "Movimiento {number}", unchangedDraft: "Este borrador da como resultado una disposición sin cambios. Añade otro movimiento o cancélalo.", undo: "Deshacer último paso", addMove: "Añadir otro movimiento", apply: "Aplicar",
  bookMoved: "«{title}»: {source} → {destination}", bookShifted: "Se ha desplazado {count} libro {reason}.", booksShifted: "Se han desplazado {count} libros {reason}.", occupyGap: "para ocupar el hueco", fillGapAndMakeRoom: "para llenar el hueco y crear espacio", makeRoom: "para crear espacio", continueWithBook: "Continuar con «{title}».", noStackingCapacity: "{container} no tiene espacio libre en el eje de apilado.", booksCompressed: "{container} comprimirá sus libros un {percent}%.", insufficientCapacity: "{container} necesita un {needed}%, pero solo hay un {available}% disponible.", unknownScale: "{container} no tenía una escala conocida; su primer libro usa el 10% del espacio disponible.", layoutConflict: "La disposición proyectada entra en conflicto con otro elemento físico.", rearrangementWarning: "El movimiento requiere atención antes de poder aplicarlo.",
  clearSelection: "Borrar selección", selectedBook: "Libro seleccionado", pages: "{count} páginas", unknownPages: "Número de páginas desconocido · estimación visual de {count} páginas", selectedContainer: "Contenedor seleccionado", bookCount: "{count} libro", booksCount: "{count} libros", focusContainer: "Centrar contenedor", loadingDetails: "Cargando…", completeInformation: "Información completa", readOnlyInspection: "Inspección de solo lectura",
  readingStatus: "Estado de lectura", acquisitionRecency: "Antigüedad de adquisición", readingRecency: "Antigüedad de lectura", pendingDuration: "Tiempo pendiente", readingDuration: "Duración de la lectura", readingRate: "Ritmo de lectura (páginas/día)", language: "Idioma", originalLanguage: "Idioma original", translationStatus: "Estado de traducción", editionYear: "Año de la edición actual", originalYear: "Año de publicación original", genreFocus: "Género destacado", publisherFocus: "Editorial destacada", authorFocus: "Autoría destacada", fictionCategory: "Ficción / no ficción", binding: "Encuadernación", publicationType: "Tipo de publicación",
  pending: "Pendiente", reading: "En lectura", onLoan: "Prestado", physicalCopyReading: "Este ejemplar físico está en lectura", physicalCopyOnLoan: "Este ejemplar físico está prestado", rereading: "En relectura", read: "Leído", notSelected: "No seleccionado", otherBooks: "Otros libros", chooseFocus: "Elegir {mode}", notRecorded: "Sin registrar", originalCollection: "Colección original", noAcquisitionDate: "Sin fecha de adquisición", stillReading: "Todavía en lectura", stillRereading: "Todavía en relectura", readNoData: "Leído · sin datos", noData: "Sin datos", days: "{count} días", pagesPerDay: "{count} páginas/día", noRecordedData: "No hay datos registrados", shortest: "Más breve", longest: "Más largo", slowest: "Más lento", fastest: "Más rápido", oldest: "Más antiguo", newest: "Más reciente", endpointOne: "{adjective}: «{title}» · {value}", endpointTie: "{adjective}: empate ({count}) · {value}",
} satisfies Record<MapCopyKey, string>;
