version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-security-and-maintenance:
        patterns: ["*"]
        update-types: ["patch"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      server-security-and-maintenance:
        patterns: ["*"]
        update-types: ["patch"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      local-security-and-maintenance:
        patterns: ["*"]
        update-types: ["patch"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-security-and-maintenance:
        patterns: ["*"]
        update-types: ["patch"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: docker
    directory: /server/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      docker-security-and-maintenance:
        patterns: ["*"]
        update-types: ["patch"]
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
