version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend-security-and-maintenance:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      server-security-and-maintenance:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      local-security-and-maintenance:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /server/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
