import type { AuthenticatedCopyKey } from "../../authenticatedCopy";

export const authenticatedZh = {
  requestFailed: "BOOKPILE 无法处理此请求。", openingAccount: "正在打开账户…", privateAccount: "私人账户", yourProfile: "您的个人资料", profileIntro: "选择其他已登录 BOOKPILE 的用户可以看到哪些内容。电子邮箱、安全信息和存储数据始终保持私密。", profileImage: "头像", yourProfileImage: "您的个人资料", chooseImage: "选择图片", remove: "移除", whoCanSeeIt: "谁可以看到？", aboutYou: "关于您", name: "姓名", nameHelp: "仅显示在您的个人资料中；BOOKPILE 在应用其他位置使用 @{username}。", timezone: "时区", notSpecified: "未指定", city: "城市", stateRegion: "省／地区", country: "国家／地区", dateOfBirth: "出生日期", gender: "性别", leaveBlank: "留空", male: "男性", female: "女性", custom: "自定义", customGender: "自定义性别", preferredPronoun: "首选代词", neutral: "中性", neutralPronounText: "中性代词文本", neutralPronounPlaceholder: "其", pronounVisibility: "即使性别保密，代词仍会向已登录用户显示。", privacy: "隐私", privacyHelp: "个人数据包括性别、位置和出生日期。代词仍会向已登录用户显示。", fieldName: "姓名", fieldTimezone: "时区", fieldPersonalData: "个人数据", visibilityPrivate: "仅自己", visibilityLibrary: "共享书库的用户", visibilityAuthenticated: "所有 BOOKPILE 用户", saving: "保存中…", saveProfile: "保存个人资料", profileSaved: "个人资料和隐私选项已保存。", imageUpdated: "私人头像已更新。", imageRemoved: "头像已移除。",
  storage: "存储", storageHelp: "每种颜色表示已用空间的分配。共享书库的存储由所有者共同承担。", accountData: "账户数据", accountDataStorageLabel: "账户数据占用空间", libraryStorageLabel: "{library} 对账户已用空间的占用", totalAccountStorage: "账户总存储", totalStorageLabel: "账户使用的总存储", account: "账户", username: "用户名", registrationEmail: "注册邮箱", password: "密码", notSet: "未设置", memberSince: "加入时间", language: "语言", languageHelp: "账户语言首选项会跨设备同步，并用于账户消息。邀请可以使用其他语言。", bookpileLanguage: "BOOKPILE 语言", languageSaved: "账户语言首选项已保存。",
  inviteSomeone: "邀请他人加入 BOOKPILE", betaInvitationHelp: "每在三个不同日期使用 BOOKPILE，您便会获得一个测试账户邀请。每天只计一次，第三个活跃日后重新累计。已创建的邀请将在七天后过期。", invitationProgressLabel: "距离下个邀请：{active}/{required} 个活跃日", invitationProgress: "距离您的下个邀请：{active}/{required} 个活跃日", invitationsReady: "可创建", invitationsOpen: "已创建且仍可使用", invitationLanguage: "邀请语言", createAccountInvitation: "创建账户邀请", invitationReady: "账户邀请已准备好，仅在本次会话中显示。", invitationMessage: "邀请消息", invitationLink: "邀请链接", copyMessage: "复制消息", copyLinkOnly: "仅复制链接", copied: "已复制{label}。", clipboardFailed: "BOOKPILE 无法访问剪贴板。请手动选择并复制可见链接。", invitationExpires: "{date} 过期。为安全起见请立即复制；BOOKPILE 仅保存其哈希值。",
  recentlyDeletedLibraries: "最近删除的书库", recoveryHelp: "删除时的任何所有者均可在 48 小时内恢复整个书库。恢复是完整的，并需要足够的共享可用空间。", recoverableUntil: "可恢复至 {date}", restore: "恢复", libraryRestored: "“{name}”及其所有成员关系已恢复。", security: "安全", securityHelp: "更改密码或关闭活动会话。", currentPassword: "当前密码", newPassword: "新密码", confirmNewPassword: "确认新密码", changePassword: "更改密码", passwordChanged: "密码已更改，其他设备已退出。", signOut: "退出登录", signOutEverywhere: "在所有设备上退出", deleteAccount: "删除账户", completeRecovery: "完成恢复", restoreLibraryTitle: "恢复“{name}”？", restoreLibraryHelp: "图书、封面、布局、阅读、借阅和所有旧成员关系将一并恢复。", yourCurrentPassword: "您的当前密码", cancel: "取消", restoring: "恢复中…", restoreLibrary: "恢复书库", dangerZone: "危险区域", deleteAccountTitle: "删除您的账户？", deleteAccountHelp: "您的个人资料将不再可见，所有会话会关闭，查看者成员关系会立即移除。必须先转让或删除您所有的书库。账户可在 48 小时内完整恢复；此后个人资料、个人阅读和个人数据将被永久删除。", typeUsername: "准确输入 {username}", deletionAcknowledgement: "我了解账户恢复期将在 48 小时后结束。", deleting: "删除中…",
  navControls: "BOOKPILE 工作区控件", chooseLibrary: "选择书库", owner: "所有者", viewer: "查看者", myProfile: "我的个人资料", customizeLayout: "自定义布局", protectedSession: "受保护的会话", openPrivateProfile: "打开私人个人资料和账户", yourLibraries: "您的书库", closeLibraries: "关闭书库面板", viewerCatalogueMap: "查看者 · 目录 + 地图", viewerCatalogue: "查看者 · 目录", noLibraries: "尚无书库。请在下方创建第一个书库。", librarySettings: "书库设置", librarySettingsHelp: "成员、实体结构和删除", newLibraryName: "新书库名称", createLibrary: "创建书库", libraryInvitation: "书库邀请链接或代码", joinLibrary: "加入书库", viewPerspective: "视图和阅读视角", closeViewPanel: "关闭视图和视角面板", libraryView: "书库视图", catalogue: "目录", libraryMap: "书库地图", statistics: "统计", catalogueAndMap: "目录和地图", catalogueOnly: "仅目录", perspectiveHelp: "选择要显示的个人阅读数据。其他用户的视角为只读。", editablePerspective: "您的可编辑视角", readOnly: "只读", memberProfiles: "成员个人资料", self: "自己",
} satisfies Record<AuthenticatedCopyKey, string>;
