import type { CatalogueCopyKey } from "../../catalogueCopy";

export const catalogueZh = {
  serverUnavailable: "BOOKPILE 无法连接服务器，请重试。", coverOf: "《{title}》的封面", shelf: "书架", background: "后层", foreground: "前层", row: "横排", pile: "书堆", position: "位置", contributorRolesUnavailable: "贡献者角色不可用。请重新加载页面后重试。",
  noSuggestedBooks: "没有符合当前目录筛选条件的待读图书。", privateCatalogue: "私人目录", sharedCatalogue: "共享目录", yourBooks: "您的图书", usersBooks: "{username} 的图书", owner: "所有者", viewer: "查看者", memberCount: "{count} 名成员", book: "本书", books: "本书", match: "项匹配", newRead: "新阅读", add: "添加", addSingleBook: "添加一本书", batchAdd: "批量添加", scanSingleBarcode: "扫描条形码", batchScan: "批量扫描", readingSuggestion: "阅读建议", another: "换一本", startReading: "开始阅读", closeSuggestion: "关闭建议", readingSummary: "目录阅读摘要", totalBooks: "图书总数", waitingToRead: "待读", currentlyReading: "阅读中", read: "已读",
  searchPlaceholder: "按标题、作者、贡献者或系列搜索", searchCatalogue: "搜索目录", sort: "排序", sortCatalogue: "目录排序", advancedSort: "高级排序", title: "标题", author: "作者", physicalLocation: "实体位置", advanced: "高级", languages: "语言", originalLanguages: "原始语言", genres: "类型", publishers: "出版社", series: "系列", translation: "翻译", category: "类别", binding: "装帧", publicationType: "出版物类型", unknown: "未知", original: "原著", translated: "译著", fiction: "虚构", nonFiction: "非虚构", hardcover: "精装", paperback: "平装", flexibound: "软精装", spiral: "螺旋装订", stapled: "骑马订", other: "其他", conventionalBook: "普通图书", comicGraphicNovel: "漫画／图像小说", atlas: "地图集", reference: "参考书", artPhotographyIllustrated: "艺术／摄影／图册", magazinePeriodical: "杂志／期刊", seriesMembership: "系列归属", any: "不限", inSeries: "属于系列", notInSeries: "不属于系列", authors: "作者", singleAuthor: "单一作者", multipleAuthors: "多位作者", minimumPages: "最少页数", maximumPages: "最多页数", yearField: "年份字段", currentEdition: "当前版本", originalPublication: "原始出版", minimumYear: "最早年份", maximumYear: "最晚年份",
  personalReadingState: "个人阅读状态", pending: "待读", activeReading: "阅读中 — 任一活动阅读", firstReading: "阅读中 — 首次", rereadingNow: "重读中", readInactive: "已读 — 无活动阅读", rereadingHistory: "重读记录", hasBeenReread: "曾重读", hasNotBeenReread: "未曾重读", readingDate: "阅读日期", readingStarted: "开始阅读", finishedReading: "完成阅读", readingDateFrom: "阅读日期起", readingDateTo: "阅读日期止",
  loanHistory: "借阅记录", currentlyOnLoan: "当前借出", overdue: "已逾期", everLoaned: "曾借出", neverLoaned: "从未借出", borrowerContains: "借阅人姓名包含", loanDate: "借出日期", loaned: "借出", expectedReturn: "预计归还", returned: "已归还", loanDateFrom: "借出日期起", loanDateTo: "借出日期止",
  sortBy: "排序依据", dateAdded: "添加日期", lastUpdated: "最近更新", pages: "页数", publisher: "出版社", editionYear: "版本年份", originalYear: "原始年份", acquisitionDate: "入藏日期", loanedDate: "借出日期", ascending: "升序", descending: "降序", direction: "方向", clear: "清除", applyFilters: "应用筛选",
  onLoanTo: "借给 {borrower}", onLoan: "借出中", returnsTo: "归还至 {location}", beingRead: "阅读中", noPhysicalLocation: "无实体位置", pageCount: "{count} 页", noOptionalMetadata: "未保存可选元数据", completeInformation: "完整信息", goodreadsReview: "{username} 的 Goodreads 书评", myReading: "我的阅读", manageLoan: "管理或结束借阅", loanBook: "借出此书", editBookLocation: "编辑图书和实体位置", delete: "删除",
  everyBookPlace: "每本书都有位置", buildPhysicalLibrary: "构建您的实体书库", mapOnboarding: "BOOKPILE 地图将每条目录记录与现实位置相连。此功能可选，但现在花几分钟设置书柜、书架和容器，会让添加和查找图书更加容易。", setUpMap: "设置书库地图", skipMap: "您也可以跳过此步，随时直接添加图书。", noBooksMatch: "没有匹配的图书", tryAnotherFilter: "请尝试其他页面或筛选条件。", noCatalogueRecords: "此书库尚无目录记录。", cataloguePages: "目录页", previous: "上一页", next: "下一页", close: "关闭", readOnlyRecord: "只读目录记录", contributors: "贡献者", selectedOwner: "所选所有者", notRecorded: "未记录",
  editBook: "编辑图书", subtitle: "副标题", isbn10: "ISBN-10", isbn13: "ISBN-13", currentEditionYear: "当前版本年份", originalPublicationYear: "原始出版年份", language: "语言", originalLanguage: "原始语言", edition: "版本", seriesVolume: "系列卷次", acquired: "入藏", originalCollection: "原始收藏", height: "高度", width: "宽度", thickness: "厚度", notes: "备注", chooseTransferValues: "选择要传入的值", transferNoneAutomatic: "不会自动选择或保存任何值。", applyMetadata: "应用所选元数据",
  batchCataloguing: "批量编目", sharedRecord: "共享目录记录", addNextBook: "添加下一本书", addBook: "添加图书", batchCountOne: "本批次已添加 {count} 本书。", batchCountMany: "本批次已添加 {count} 本书。", batchHelp: "保存后 BOOKPILE 会清除图书数据，但保留此容器并建议下一个位置。",
  identifyIsbn: "通过 ISBN 或条形码识别", barcodePrivacy: "条形码照片在此设备上解码后立即删除。传入前请核对供应商数据。", enterIsbn: "请先输入或扫描 ISBN。", lookingUp: "查询中…", lookupIsbn: "查询 ISBN", readingPhoto: "正在读取照片…", takeBarcodePhoto: "拍摄条形码", isbnAlreadyPresent: "书库中已存在此 ISBN", noBibliographicRecord: "未找到书目记录，您可以继续手动输入。",
  requiredInformation: "必填信息", titleRequired: "标题 *", authorDisplayRequired: "显示作者 *", privateCover: "私人封面图片", coverPrivacy: "仅此书库中已登录的成员可见。BOOKPILE 会在移除元数据并生成私人 WebP 副本后删除原图。", storedCover: "已保存私人封面", noCover: "未选择封面", chooseCover: "拍摄或选择封面", removeCover: "移除封面", keepCover: "保留现有封面",
  contributorHelp: "按署名顺序添加作者、译者、插画师和其他贡献角色。", contributorName: "贡献者姓名", moveUp: "上移", moveDown: "下移", removeContributor: "移除贡献者", addContributor: "添加贡献者", editionClassification: "版本和分类", editionNumber: "版次", commaSeparated: "用逗号分隔", languageTranslation: "语言和翻译", translationStatus: "翻译状态", originalLanguageValue: "原始语言", identifiers: "标识符", copyDetails: "副本详情",
  physicalLocationHelp: "可选。占用的位置会自动腾出空间；移动图书时会收紧原容器。", bookcase: "书柜", chooseShelf: "选择书架", container: "容器", chooseContainer: "选择容器", libraryNotes: "书库备注", optional: "可选",
  initialReadingHelp: "创建此共享记录时添加阅读记录和 Goodreads 书评。这些值属于个人，并会在批量添加下一本书前清除。", readingRecord: "阅读记录", noReadingRecord: "无阅读记录", historicalCompleted: "历史阅读 — 已完成", activeStarted: "活动阅读 — 已开始", readingDatesUnknown: "阅读日期未知", started: "开始", finished: "完成", goodreadsUrl: "我的 Goodreads 书评网址",
  currentLoan: "当前借阅", copyCurrentlyLoaned: "此实体副本当前已借出", retainedPositionHelp: "副本显示在共享借阅区时，书架位置仍会保留。", loanedToRequired: "借给 *", loanDateLabel: "借出日期", optionalUnknown: "可选／未知", expectedReturnLabel: "预计归还", privateOwnerNotes: "所有者私人备注",
  processingPhotoHelp: "处理手机拍摄的大型照片可能需要几秒，请保持窗口打开。", finishBatch: "结束批次", cancel: "取消", pleaseWait: "请稍候…", saveScanNext: "保存并扫描下一本", saveAddNext: "保存并添加下一本", saveBook: "保存图书", barcodeReadingLocally: "正在本地读取条形码…", checkingSources: "正在查询书目来源和此书库…", selectedCoverPreview: "所选封面预览", loanReadingConflict: "一个副本不能同时处于借出和阅读状态。", processingCover: "正在处理私人封面…", removingCover: "正在移除私人封面…", savingGoodreads: "正在保存 Goodreads 书评…", savingReadingHistory: "正在保存阅读记录…", startingReading: "正在开始阅读…",
  partialSave: "共享图书和位置已保存，但部分私人封面或个人阅读数据失败。{error}请修正后重试：BOOKPILE 会更新此书，而不是创建重复记录。", savedNext: "“{title}”已保存，可以添加下一本书。", bookSaved: "图书和私人封面已保存。", bookUpdated: "图书已更新。", deleteBookConfirm: "永久删除“{title}”？此操作无法撤销。", bookDeleted: "图书已永久删除。", personalDataUpdated: "个人阅读数据已更新。", loanDataUpdated: "共享借阅数据已更新。",
} satisfies Record<CatalogueCopyKey, string>;
