import type { LibraryAdminCopyKey } from "../../libraryAdminCopy";

export const libraryAdminZh = {
  requestFailed: "BOOKPILE 无法处理此请求。", libraryCreated: "“{name}”已创建，您是首位所有者。", joinedOwner: "您已作为所有者加入“{name}”。", joinedViewer: "您已作为查看者加入“{name}”。", invitationReadyNotice: "书库一次性邀请已准备好，将在七天后过期。", copied: "已将{label}复制到剪贴板。", clipboardFailed: "BOOKPILE 无法访问剪贴板。请手动选择并复制显示的内容。", invitationMessageLabel: "书库邀请消息", invitationLinkLabel: "书库邀请链接", memberUpdated: "{username} 的成员关系已更新。", libraryDeleted: "“{name}”已删除。删除时的所有者可在 48 小时内从私人个人资料恢复。", newLibraryImported: "“{name}”已创建，并以原子方式导入 {source} 书库。", existingLibraryImported: "已将 {source} 书库导入“{name}”，未替换现有图书。", sourceServer: "Server", sourceLocal: "Local", preparingExport: "正在准备“{name}”的私人可移植导出。",
  updateMembership: "更新成员关系", confirmAccessChange: "确认更改此成员的书库访问权限。", giveMapTitle: "授予 {username} 地图访问权限？", removeMapTitle: "移除 {username} 的地图访问权限？", giveMapHelp: "除了目录外，该查看者还可查看书库实体地图和已保存的图书位置。访问权限仍为只读。", removeMapHelp: "该查看者仍可只读访问目录，但将无法看到实体位置和书库地图。", promoteTitle: "将 {username} 提升为权限相同的共同所有者？", promoteHelp: "共同所有者拥有与您相同的权限：可编辑目录和布局、管理成员和借阅、移除您的成员关系、导出或恢复数据，并发起删除整个书库。仅向完全信任的人授予此角色。", downgradeTitle: "将 {username} 从所有者降为查看者？", downgradeHelp: "此人将失去所有编辑和成员管理权限。请选择保留的只读访问是否包括实体地图。", removeTitle: "从此书库移除 {username}？", removeHelp: "这会立即移除其目录、地图、封面、阅读视角访问权限和书库成员关系，但不会删除 BOOKPILE 账户。",
  closeSettings: "关闭设置面板", settingsTitle: "书库设置：{name}", manageStructure: "管理实体结构", manageStructureHelp: "创建或删除书柜、书架和容器。", manageMembers: "管理成员", manageMembersHelp: "成员、权限和邀请。", dataPortability: "数据和可移植性", dataPortabilityHelp: "导入 BOOKPILE Local 副本或导出此书库。", deleteLibrary: "删除书库", deleteLibraryMenuHelp: "为所有人删除，并保留 48 小时恢复期。", equalCoOwner: "权限相同的共同所有者", viewerCatalogueMap: "查看者 · 目录 + 地图", viewerCatalogueOnly: "查看者 · 仅目录", giveMapAccess: "授予地图访问", removeMapAccess: "移除地图访问", makeCoOwner: "设为共同所有者", makeViewer: "设为查看者", remove: "移除", inviteMember: "邀请成员", role: "角色", viewer: "查看者", access: "访问", catalogueOnly: "仅目录", catalogueMap: "目录和地图", invitationLanguage: "邀请语言", ownerAcknowledgement: "我了解此人将拥有与我相同的权限，并可移除我的成员关系。", generateInvitation: "生成邀请", invitationMessage: "邀请消息", copyMessage: "复制消息", copyLinkOnly: "仅复制链接",
  exportTitle: "导出“{name}”", exportHelp: "下载经过验证的 Server ZIP，其中包含此书库、地图、私人封面、借阅以及按成员标识的阅读数据。绝不包含登录凭据、电子邮箱、个人资料或其他书库。", downloadZip: "下载可移植 ZIP", importTitle: "恢复或导入 BOOKPILE ZIP", importHelp: "Local 副本会添加目录并将个人记录分配给一位所有者。Server 可移植导出会精确恢复共享结构，并可将每个原始身份映射到当前所有者。", zipSource: "ZIP 来源", localBackup: "BOOKPILE Local 完整副本", serverExport: "BOOKPILE Server 可移植导出", localZip: "Local 完整副本 ZIP", serverZip: "Server 可移植 ZIP", readingOwner: "阅读记录归属", you: "您", inspecting: "正在安全检查…", inspectZip: "检查 ZIP", importLimit: "压缩 ZIP 上限为 100 MiB。检查过程相互隔离，批准报告前无法修改此书库。", uploading: "正在上传并检查 ZIP…", uploadingHelp: "正在验证校验和、封面、数据完整性和关系。大型书库可能需要一些时间，请保持窗口打开。", readyReview: "可供审核", exportDescription: "Server 导出“{name}”", localDescription: "Local 副本", format: "格式", schema: "架构", created: "创建时间", capacityError: "最终 Server 数据目前超过此书库所有者的共享可用空间。", repeatedArchive: "我希望从同一存档再添加一组实体副本。", countBooks: "图书", countBookcases: "书柜", countShelves: "书架", countContainers: "容器", countContributors: "贡献者", countAuthors: "作者", countReadings: "阅读", countLoans: "借阅", countCovers: "封面",
  warningRepeated: "同一 ZIP 已在此书库中准备或导入。", warningDuplicateIsbn: "导入的 {count} 本书可能与现有图书 ISBN 相同。", warningDuplicateTitle: "导入的 {count} 本书可能与现有图书标题和作者相同。", warningCapacity: "导入数据超过所有者的共享空间。", warningCoordinates: "此书库使用不同的地图模式或坐标系统。请恢复为新书库以保留几何结构。", warningFurniture: "此书库中已存在部分书柜名称。请重命名或恢复为新书库。", warningOutsideAreas: "部分现有书库外区域将优先。导入图书和共享数据不受影响。", warningGeneric: "检查发现需要注意的情况（{code}）。",
  personalDataTitle: "“{name}”中的个人数据", personalDataHelp: "成员关系绝不会恢复。将原始用户映射到当前所有者，才能恢复其阅读和 Goodreads 链接。", sourcePersonalCounts: "@{username} · {readings} 条阅读 · {records} 条个人记录", doNotRestorePersonal: "不恢复个人数据", duplicateOwner: "每个目标所有者只能接收一个原始身份。", omitUnmapped: "我了解未映射的阅读和 Goodreads 链接将被省略。", creatingImport: "正在创建书库并以原子方式导入…", importing: "正在以原子方式导入…", processingImport: "正在处理 {books} 本书、{covers} 个封面、{readings} 条阅读和 {loans} 条借阅。除非操作全部完成，否则不会显示任何内容。", cancelStaging: "取消并删除临时区", restoreHere: "恢复到此书库", importHere: "导入到此书库", createSeparate: "或创建独立书库", newLibraryName: "新书库名称", sourceIdentity: "将恢复为您的原始身份", noneOmitPersonal: "无 — 省略所有个人数据", sourceReadings: "@{username} · {readings} 条阅读", omitOtherMembers: "我了解其他原始成员的阅读和 Goodreads 链接将被省略。", creatingAndImporting: "正在创建和导入…", importAsNew: "导入为新书库", newOwnerHelp: "您将是唯一的初始所有者。Server 成员关系绝不会重建；请随后邀请其他人。", importComplete: "导入完成。已添加 {books} 本书及所有兼容记录。",
  permissionChange: "权限更改", viewerAccess: "查看者访问", currentPassword: "您的当前密码", cancel: "取消", applying: "应用中…", confirmChange: "确认更改", dangerZone: "危险区域", deleteTitle: "删除“{name}”？", deleteHelp: "这会立即移除所有成员的访问权限，并隔离图书、封面、实体布局、阅读和借阅。删除时的任何所有者均可在 48 小时内恢复全部内容，此后将永久删除。", typeExactly: "准确输入 {name}", deletionAcknowledgement: "我了解恢复期将在 48 小时后结束，随后书库数据将被永久删除。", deleting: "删除中…", emptyTitle: "创建或加入书库", emptyHelp: "账户和书库相互独立：一个账户可以拥有或查看多个书库。",
} satisfies Record<LibraryAdminCopyKey, string>;
