import type { PhysicalCopyKey } from "../../physicalCopy";

export const physicalZh = {
  requestFailed: "BOOKPILE 无法处理此请求。", maintenance: "实体书库管理", editTarget: "编辑{target}", bookcase: "书柜", shelf: "书架", container: "容器", nameRequired: "名称 *", description: "描述", numberRequired: "{target}编号 *", optionalDimensions: "可选实体尺寸", height: "高度", width: "宽度", depth: "深度", usableHeight: "可用高度", usableWidth: "可用宽度", usableDepth: "可用深度", cancel: "取消", saveChanges: "保存更改", dimensionsMissing: "未记录尺寸", homogeneousConfirm: "将此书柜设为均匀结构？保存时会重新计算独立书架边框和隔板，其边界可能移动。", recalculateConfirm: "这会重新计算共享书架几何。仅当所有书架均能容纳时，预览值才会替换当前派生布局。是否继续？",
  visualWorkspace: "可视工作区", customizeMap: "自定义书库地图", expandEditor: "展开布局编辑器", minimizeEditor: "最小化布局编辑器", expand: "展开", minimize: "最小化", cancelEditing: "取消布局编辑", preciseHelp: "在地图上选择对象可显示移动和尺寸控件，也可使用这些精确设置。按下“应用”前，更改仅保留在本地预览中。", geometryMode: "几何模式", projection: "投影", manualProportions: "手动比例", physicalDimensions: "实体尺寸", physicalModeHelp: "书柜外部尺寸和书架内部尺寸决定投影。缺少数据的轴使用标记的估算值；无效结构无法应用。", manualModeHelp: "书柜使用相当于毫米的地图单位。书架和容器设置是父元素的百分比；实体元数据仅供参考。",
  furnitureGeometry: "书柜几何（毫米）", sizeFixed: "大小由已记录的实体尺寸固定。", exteriorBoth: "外部宽度和高度", exteriorWidth: "外部宽度", exteriorHeight: "外部高度", sizeFixedHelp: "{dimensions}无法在地图上更改。请在书库布局中修改书柜尺寸以更改{pronoun}。", horizontalLeft: "水平 — 左边距", floorBaseline: "地面基线", fixedDistribution: "固定书架分布", topBottom: "从上到下", bottomTop: "从下到上", leftRight: "从左到右", rightLeft: "从右到左", homogeneous: "均匀结构", sharedStructure: "共享书架定位结构", sharedStructureHelp: "边框和封板用于定位书柜内的书架隔间。隔板厚度设定相邻书架间距。即使书架宽度或高度由已记录尺寸固定，这些值仍可编辑。", leftFrame: "左边框", rightFrame: "右边框", upperClosure: "上封板", lowerClosure: "下封板／底板", separatorThickness: "隔板厚度", fallbackExterior: "缺少的外部尺寸使用可在地图上编辑的估算毫米值（默认：2,200 × 800 × 280）。",
  shelfCompartment: "书架隔间 {unit}", chooseShelf: "选择书架", noShelves: "此书柜没有书架", shelfNumber: "书架 {number}", recordedSizeFixed: "仅已记录的尺寸固定。", interiorBoth: "内部宽度和高度", interiorWidth: "内部宽度", interiorHeight: "内部高度", shelfFixedHelp: "{dimensions}无法在地图上更改。其位置仍可通过{structure}调整。请在书库布局中修改实体尺寸。", sharedStructureReference: "书柜几何的共享边框、封板和隔板", independentStructureReference: "下方书架的独立结构", derivedLeft: "派生左边距（毫米）", leftPercent: "左边距（%）", derivedFloor: "派生基线（毫米）", floorPercent: "基线（%）", widthPercent: "宽度（%）", heightPercent: "高度（%）", sourceSummary: "左边距和基线由定位结构计算。宽度来源：{width} · 高度来源：{height}。", sourceEntered: "输入值", sourceFallback: "估算值", sourceDerived: "派生值", resetAutomatic: "恢复未测量尺寸的自动调整", openTop: "开放式顶层书架", independentStructure: "独立书架结构", independentHelp: "边框定义此书架的可用矩形。对齐调整仅为少数已测量的非对称书架保留。",
  lowerBoard: "底板", followingSeparator: "下一隔板", advancedAlignment: "高级对齐调整", horizontalAlignment: "水平对齐", left: "左", centre: "居中", right: "右", alignmentOffset: "额外偏移", separatorAnchor: "隔板基准", containerGeometry: "容器 {unit} 的几何和支撑", chooseContainer: "选择容器", noContainers: "此书架没有容器", chooseShelfFirst: "请先选择书架", backgroundShort: "后", foregroundShort: "前", background: "后层", foreground: "前层", row: "横排", pile: "书堆", anchorPosition: "基准位置 {unit}", alignmentPosition: "对齐位置 {unit}", bottomClearance: "底部间隙 {unit}", occupiedHelp: "占用宽高来自图书实体尺寸和有记录的估算值。请在此更改基准、对齐或支撑；修改图书尺寸可改变占用大小。", envelopeHelp: "如果图书没有实体尺寸，会保留此可编辑的可视包络；手动模式以百分比表示。底部间隙相对于直接支撑物，零表示实体接触。", depthOffsetHelp: "只有放在书架上的后层容器可以使用可视深度偏移。", rowAnchor: "横排增长基准", leftGrowRight: "固定左边距 — 向右增长", rightGrowLeft: "固定右边距 — 向左增长", restsOn: "放置于", shelfBottom: "书架底部", supportHelp: "只能使用同一书架和层级中非空且类型相反的容器。", pileAlignment: "书堆对齐", unmeasuredRow: "未测量横排", unmeasuredRowHelp: "此横排中的图书均无明确实体尺寸，因此添加测量值前可手动设置可视包络。", fillShelf: "占满书架宽度", outsideAreas: "书库外区域（毫米）", area: "区域", reading: "阅读中", onLoan: "借出中", horizontal: "水平", areaHelp: "水平表示左边距；基线表示下边距。宽度和高度从这些坐标向右和向上延伸。",
  saving: "保存中…", applyLayout: "应用可视布局", layout: "书库布局", loadingPhysical: "正在加载实体书库…", unavailable: "实体书库不可用。", sharedPhysical: "共享实体结构", structure: "书库结构", ownerHelp: "创建、编辑或删除书柜、书架、横排和书堆。可视布局仅用于在地图上定位和调整其表示。", viewerHelp: "只读实体层级。您的查看者权限包括书库地图。", visualLayout: "可视布局", addBookcase: "添加书柜", initialStructure: "初始结构和尺寸", numberingDirection: "书架编号方向", homogeneousShelf: "均匀书架结构", exteriorDepth: "外部深度", directionHelp: "添加第一个书架时会固定方向。空尺寸在地图上使用独立估算值，不会保存为实体测量。", addShelf: "添加书架", chooseBookcase: "选择书柜", number: "编号", addContainer: "添加容器", type: "类型", layer: "层级", addedBookcase: "书柜已添加。", addedShelf: "书架已添加。", addedContainer: "容器已添加。", updated: "实体书库已更新。", layoutSaved: "可视布局已保存。", deleteConfirm: "删除{label}？如果仍包含其他实体书库元素，BOOKPILE 将拒绝操作。", deleted: "已删除{label}。", bookCount: "{count} 本书", booksCount: "{count} 本书", shelfCount: "{count} 个书架", shelvesCount: "{count} 个书架", editBookcase: "编辑书柜", deleteBookcase: "删除书柜", editShelf: "编辑书架", deleteShelf: "删除书架", editContainer: "编辑容器", deleteContainer: "删除容器", noStructure: "尚无实体结构", addFirst: "请在上方添加第一个书柜。", ownersNotConfigured: "所有者尚未配置书库地图。",
} satisfies Record<PhysicalCopyKey, string>;
