import type { AuthenticatedCopyKey } from "../../authenticatedCopy";

export const authenticatedCa = {
  requestFailed: "BOOKPILE no ha pogut completar aquesta sol·licitud.",
  openingAccount: "Obrint el teu compte…",
  privateAccount: "Compte privat",
  yourProfile: "El teu perfil",
  profileIntro: "Tria què poden veure les altres persones amb sessió iniciada a BOOKPILE. El correu electrònic, la seguretat i les dades d'emmagatzematge sempre són privats.",
  profileImage: "Imatge de perfil", yourProfileImage: "El teu perfil", chooseImage: "Tria una imatge", remove: "Elimina", whoCanSeeIt: "Qui la pot veure?", aboutYou: "Sobre tu", name: "Nom", nameHelp: "Només es mostra al teu perfil; BOOKPILE utilitza @{username} a la resta de l'aplicació.", timezone: "Zona horària", notSpecified: "No especificat", city: "Ciutat", stateRegion: "Província / regió", country: "País", dateOfBirth: "Data de naixement", gender: "Gènere", leaveBlank: "Deixa-ho en blanc", male: "Masculí", female: "Femení", custom: "Personalitzat", customGender: "Gènere personalitzat", preferredPronoun: "Pronom preferit", neutral: "Neutre", neutralPronounText: "Text del pronom neutre", neutralPronounPlaceholder: "elle", pronounVisibility: "Els pronoms són visibles per a les persones amb sessió iniciada encara que el gènere sigui privat.",
  privacy: "Privacitat", privacyHelp: "Les dades personals agrupen el gènere, la ubicació i la data de naixement. Els pronoms continuen visibles per a les persones amb sessió iniciada.", fieldName: "Nom", fieldTimezone: "Zona horària", fieldPersonalData: "Dades personals", visibilityPrivate: "Només jo", visibilityLibrary: "Persones que comparteixen una biblioteca", visibilityAuthenticated: "Totes les persones usuàries de BOOKPILE", saving: "Desant…", saveProfile: "Desa el perfil", profileSaved: "El teu perfil i les opcions de privacitat s'han desat.", imageUpdated: "La teva imatge de perfil privada s'ha actualitzat.", imageRemoved: "La teva imatge de perfil s'ha eliminat.",
  storage: "Emmagatzematge", storageHelp: "Cada color mostra com es distribueix l'espai utilitzat. L'emmagatzematge de les biblioteques compartides es reparteix entre les persones propietàries.", accountData: "Dades del compte", accountDataStorageLabel: "Contribució de les dades del compte a l'emmagatzematge utilitzat", libraryStorageLabel: "{library}, contribució a l'emmagatzematge utilitzat del compte", totalAccountStorage: "Emmagatzematge total del compte", totalStorageLabel: "Emmagatzematge total utilitzat pel compte",
  account: "Compte", username: "Nom d'usuari", registrationEmail: "Correu electrònic de registre", password: "Contrasenya", notSet: "No establert", memberSince: "Membre des de", language: "Idioma", languageHelp: "La preferència del teu compte et segueix entre dispositius i s'utilitza per als missatges del compte. Les invitacions poden utilitzar un altre idioma.", bookpileLanguage: "Idioma de BOOKPILE", languageSaved: "La preferència d'idioma del teu compte s'ha desat.",
  inviteSomeone: "Convida algú a BOOKPILE", betaInvitationHelp: "Per cada tres dies diferents que utilitzis BOOKPILE, obtens una invitació per a un compte beta. Cada dia compta una vegada i el progrés es reinicia després del tercer dia actiu. Les invitacions creades caduquen al cap de set dies.", invitationProgressLabel: "{active} de {required} dies actius per a la invitació següent", invitationProgress: "{active} de {required} dies actius per a la teva invitació següent", invitationsReady: "disponibles per crear", invitationsOpen: "creades i encara utilitzables", invitationLanguage: "Idioma de la invitació", createAccountInvitation: "Crea una invitació de compte", invitationReady: "La invitació de compte està preparada. Només es mostra en aquesta sessió.", invitationMessage: "Missatge de la invitació", invitationLink: "Enllaç de la invitació", copyMessage: "Copia el missatge", copyLinkOnly: "Copia només l'enllaç", copied: "S'ha copiat {label}.", clipboardFailed: "BOOKPILE no ha pogut accedir al porta-retalls. Selecciona i copia manualment l'enllaç visible.", invitationExpires: "Caduca el {date}. Per seguretat, copia-la ara; BOOKPILE només en desa el hash.",
  recentlyDeletedLibraries: "Biblioteques eliminades recentment", recoveryHelp: "Qualsevol persona que en fos propietària pot restaurar la biblioteca completa durant 48 hores. La recuperació és integral i requereix prou emmagatzematge compartit disponible.", recoverableUntil: "Recuperable fins al {date}", restore: "Restaura", libraryRestored: "S'han restaurat «{name}» i totes les seves pertinences.", security: "Seguretat", securityHelp: "Canvia la contrasenya o tanca les sessions iniciades.", currentPassword: "Contrasenya actual", newPassword: "Contrasenya nova", confirmNewPassword: "Confirma la contrasenya nova", changePassword: "Canvia la contrasenya", passwordChanged: "La contrasenya s'ha canviat. S'han desconnectat els altres dispositius.", signOut: "Tanca la sessió", signOutEverywhere: "Tanca la sessió a tots els dispositius", deleteAccount: "Elimina el compte",
  completeRecovery: "Completa la recuperació", restoreLibraryTitle: "Vols restaurar «{name}»?", restoreLibraryHelp: "Els llibres, les cobertes, la disposició, les lectures, els préstecs i totes les pertinences anteriors tornaran conjuntament.", yourCurrentPassword: "La teva contrasenya actual", cancel: "Cancel·la", restoring: "Restaurant…", restoreLibrary: "Restaura la biblioteca", dangerZone: "Zona de perill", deleteAccountTitle: "Vols eliminar el teu compte?", deleteAccountHelp: "El teu perfil deixa de ser visible, es tanquen totes les sessions i s'eliminen immediatament les teves pertinences com a visitant. Primer has de transferir o eliminar totes les biblioteques que posseeixes. Pots recuperar el compte complet durant 48 hores; després s'eliminen definitivament el perfil, les lectures personals i les dades personals.", typeUsername: "Escriu {username} exactament", deletionAcknowledgement: "Entenc que la recuperació del compte caduca al cap de 48 hores.", deleting: "Eliminant…",
  navControls: "Controls de l'espai de treball de BOOKPILE", chooseLibrary: "Tria una biblioteca", owner: "Propietari/ària", viewer: "Visitant", myProfile: "El meu perfil", customizeLayout: "Personalitza la disposició", protectedSession: "Sessió protegida", openPrivateProfile: "Obre el teu perfil i el teu compte privats", yourLibraries: "Les teves biblioteques", closeLibraries: "Tanca el tauler de biblioteques", viewerCatalogueMap: "Visitant · catàleg + mapa", viewerCatalogue: "Visitant · catàleg", noLibraries: "Encara no hi ha biblioteques. Crea la primera aquí sota.", librarySettings: "Configuració de la biblioteca", librarySettingsHelp: "Membres, estructura física i eliminació", newLibraryName: "Nom de la biblioteca nova", createLibrary: "Crea la biblioteca", libraryInvitation: "Enllaç o codi d'invitació a la biblioteca", joinLibrary: "Uneix-te a la biblioteca", viewPerspective: "Vista i perspectiva de lectura", closeViewPanel: "Tanca el tauler de vista i perspectiva", libraryView: "Vista de la biblioteca", catalogue: "Catàleg", libraryMap: "Mapa de la biblioteca", statistics: "Estadístiques", catalogueAndMap: "Catàleg i mapa", catalogueOnly: "Només catàleg", perspectiveHelp: "Tria les dades personals de lectura que es representen. Les perspectives d'altres persones són només de lectura.", editablePerspective: "la teva perspectiva editable", readOnly: "només de lectura", memberProfiles: "Perfils dels membres", self: "jo",
} satisfies Record<AuthenticatedCopyKey, string>;
