import type { CatalogueCopyKey } from "../../catalogueCopy";

export const catalogueCa = {
  serverUnavailable: "BOOKPILE no s'ha pogut connectar amb el servidor. Torna-ho a provar.", coverOf: "Coberta de {title}", shelf: "Prestatge", background: "Fons", foreground: "Primer pla", row: "Fila", pile: "Pila", position: "Posició",
  contributorRolesUnavailable: "Els rols de col·laboració no estan disponibles. Recarrega la pàgina i torna-ho a provar.",
  noSuggestedBooks: "No hi ha llibres pendents disponibles que coincideixin amb els filtres actuals del catàleg.", privateCatalogue: "Catàleg privat", sharedCatalogue: "Catàleg compartit", yourBooks: "Els teus llibres", usersBooks: "Llibres de {username}", owner: "Propietari/ària", viewer: "Visitant", memberCount: "{count} membres", book: "llibre", books: "llibres", match: "coincidència", newRead: "Lectura nova", add: "Afegeix", addSingleBook: "Afegeix un llibre", batchAdd: "Afegeix en lot", scanSingleBarcode: "Llegeix un codi de barres", batchScan: "Llegeix en lot", readingSuggestion: "Suggeriment de lectura", another: "Un altre", startReading: "Comença a llegir", closeSuggestion: "Tanca el suggeriment", readingSummary: "Resum de lectura del catàleg", totalBooks: "Total de llibres", waitingToRead: "Per llegir", currentlyReading: "En lectura", read: "Llegits",
  searchPlaceholder: "Cerca per títol, autoria, col·laborador o sèrie", searchCatalogue: "Cerca al catàleg", sort: "Ordena", sortCatalogue: "Ordena el catàleg", advancedSort: "Ordenació avançada", title: "Títol", author: "Autoria", physicalLocation: "Ubicació física", advanced: "Avançat", languages: "Idiomes", originalLanguages: "Idiomes originals", genres: "Gèneres", publishers: "Editorials", series: "Sèries", translation: "Traducció", category: "Categoria", binding: "Enquadernació", publicationType: "Tipus de publicació", unknown: "Desconegut", original: "Original", translated: "Traduït", fiction: "Ficció", nonFiction: "No-ficció", hardcover: "Tapa dura", paperback: "Tapa tova", flexibound: "Tapa flexible", spiral: "Espiral", stapled: "Grapat", other: "Altres", conventionalBook: "Llibre convencional", comicGraphicNovel: "Còmic / novel·la gràfica", atlas: "Atles", reference: "Consulta", artPhotographyIllustrated: "Art / fotografia / il·lustrat", magazinePeriodical: "Revista / publicació periòdica", seriesMembership: "Pertinença a una sèrie", any: "Qualsevol", inSeries: "En una sèrie", notInSeries: "Fora d'una sèrie", authors: "Autories", singleAuthor: "Una autoria", multipleAuthors: "Diverses autories", minimumPages: "Mínim de pàgines", maximumPages: "Màxim de pàgines", yearField: "Camp d'any", currentEdition: "Edició actual", originalPublication: "Publicació original", minimumYear: "Any mínim", maximumYear: "Any màxim",
  personalReadingState: "Estat personal de lectura", pending: "Pendent", activeReading: "En lectura — qualsevol lectura activa", firstReading: "En lectura — primera vegada", rereadingNow: "En relectura", readInactive: "Llegit — sense lectura activa", rereadingHistory: "Historial de relectures", hasBeenReread: "S'ha rellegit", hasNotBeenReread: "No s'ha rellegit", readingDate: "Data de lectura", readingStarted: "Inici de la lectura", finishedReading: "Final de la lectura", readingDateFrom: "Data de lectura des de", readingDateTo: "Data de lectura fins a",
  loanHistory: "Historial de préstecs", currentlyOnLoan: "Prestat actualment", overdue: "Endarrerit", everLoaned: "Prestat alguna vegada", neverLoaned: "No prestat mai", borrowerContains: "El nom de qui l'ha demanat conté", loanDate: "Data del préstec", loaned: "Prestat", expectedReturn: "Devolució prevista", returned: "Retornat", loanDateFrom: "Data del préstec des de", loanDateTo: "Data del préstec fins a",
  sortBy: "Ordena per", dateAdded: "Data d'addició", lastUpdated: "Darrera actualització", pages: "Pàgines", publisher: "Editorial", editionYear: "Any de l'edició", originalYear: "Any original", acquisitionDate: "Data d'adquisició", loanedDate: "Data del préstec", ascending: "Ascendent", descending: "Descendent", direction: "Direcció", clear: "Neteja", applyFilters: "Aplica els filtres",
  onLoanTo: "Prestat a {borrower}", onLoan: "Prestat", returnsTo: "torna a {location}", beingRead: "En lectura", noPhysicalLocation: "Sense ubicació física", pageCount: "{count} pàgines", noOptionalMetadata: "No s'han registrat metadades opcionals", completeInformation: "Informació completa", goodreadsReview: "Ressenya de {username} a Goodreads", myReading: "La meva lectura", manageLoan: "Gestiona o retorna el préstec", loanBook: "Presta aquest llibre", editBookLocation: "Edita el llibre i la ubicació física", delete: "Elimina",
  everyBookPlace: "Un lloc per a cada llibre", buildPhysicalLibrary: "Construeix la teva biblioteca física", mapOnboarding: "El mapa de BOOKPILE connecta cada registre del catàleg amb el seu lloc real. És opcional, però dedicar ara uns minuts a definir els mobles, els prestatges i els contenidors farà molt més fàcil afegir i trobar llibres.", setUpMap: "Configura el mapa de la biblioteca", skipMap: "També pots ometre'l i afegir llibres directament quan vulguis.", noBooksMatch: "Cap llibre no coincideix", tryAnotherFilter: "Prova una altra pàgina o un altre filtre.", noCatalogueRecords: "Aquesta biblioteca encara no té registres al catàleg.", cataloguePages: "Pàgines del catàleg", previous: "Anterior", next: "Següent", close: "Tanca", readOnlyRecord: "Registre de catàleg només de lectura", contributors: "Col·laboradors", selectedOwner: "Propietari seleccionat", notRecorded: "No registrat",
  editBook: "Edita el llibre", subtitle: "Subtítol", isbn10: "ISBN-10", isbn13: "ISBN-13", currentEditionYear: "Any de l'edició actual", originalPublicationYear: "Any de la publicació original", language: "Idioma", originalLanguage: "Idioma original", edition: "Edició", seriesVolume: "Volum de la sèrie", acquired: "Adquirit", originalCollection: "Col·lecció original", height: "Alçada", width: "Amplada", thickness: "Gruix", notes: "Notes", chooseTransferValues: "Tria els valors que vols transferir", transferNoneAutomatic: "No se selecciona ni es desa res automàticament.", applyMetadata: "Aplica les metadades seleccionades",
  batchCataloguing: "Catalogació en lot", sharedRecord: "Registre de catàleg compartit", addNextBook: "Afegeix el llibre següent", addBook: "Afegeix un llibre", batchCountOne: "S'ha afegit {count} llibre en aquest lot.", batchCountMany: "S'han afegit {count} llibres en aquest lot.", batchHelp: "Després de desar, BOOKPILE neteja les dades del llibre, però conserva aquest contenidor i suggereix la posició següent.",
  identifyIsbn: "Identifica per ISBN o codi de barres", barcodePrivacy: "La fotografia del codi de barres es descodifica en aquest dispositiu i es descarta immediatament. Revisa els valors del proveïdor abans de transferir-los.", enterIsbn: "Introdueix o llegeix primer un ISBN.", lookingUp: "Cercant…", lookupIsbn: "Cerca l'ISBN", readingPhoto: "Llegint la fotografia…", takeBarcodePhoto: "Fotografia el codi de barres", isbnAlreadyPresent: "Aquest ISBN ja existeix a la biblioteca", noBibliographicRecord: "No s'ha trobat cap registre bibliogràfic. Pots continuar manualment.",
  requiredInformation: "Informació obligatòria", titleRequired: "Títol *", authorDisplayRequired: "Autoria mostrada *", privateCover: "Imatge de coberta privada", coverPrivacy: "Només és visible per als membres d'aquesta biblioteca amb la sessió iniciada. BOOKPILE descarta l'original després d'eliminar-ne les metadades i crear una còpia WebP privada.", storedCover: "Coberta privada desada", noCover: "Cap coberta seleccionada", chooseCover: "Fotografia o tria una coberta", removeCover: "Elimina la coberta", keepCover: "Conserva la coberta existent",
  contributorHelp: "Afegeix autors, traductors, il·lustradors i altres rols acreditats en l'ordre en què es mostren.", contributorName: "Nom del col·laborador", moveUp: "Puja", moveDown: "Baixa", removeContributor: "Elimina el col·laborador", addContributor: "Afegeix un col·laborador", editionClassification: "Edició i classificació", editionNumber: "Número d'edició", commaSeparated: "Separat per comes", languageTranslation: "Idioma i traducció", translationStatus: "Estat de la traducció", originalLanguageValue: "Idioma original", identifiers: "Identificadors", copyDetails: "Dades de l'exemplar",
  physicalLocationHelp: "Opcional. Una posició ocupada crea espai automàticament; quan es mou un llibre, el contenidor anterior es compacta.", bookcase: "Moble", chooseShelf: "Tria un prestatge", container: "Contenidor", chooseContainer: "Tria un contenidor", libraryNotes: "Notes de la biblioteca", optional: "opcional",
  initialReadingHelp: "Afegeix el teu propi registre de lectura i la ressenya de Goodreads quan creïs aquest registre de catàleg compartit. Aquests valors són personals i es netegen abans del llibre següent afegit en lot.", readingRecord: "Registre de lectura", noReadingRecord: "Sense registre de lectura", historicalCompleted: "Lectura històrica — acabada", activeStarted: "En lectura — iniciada", readingDatesUnknown: "Dates de lectura desconegudes", started: "Inici", finished: "Final", goodreadsUrl: "URL de la meva ressenya a Goodreads",
  currentLoan: "Préstec actual", copyCurrentlyLoaned: "Aquest exemplar físic està prestat actualment", retainedPositionHelp: "La posició reservada al prestatge es conserva mentre l'exemplar apareix a l'àrea compartida de préstecs.", loanedToRequired: "Prestat a *", loanDateLabel: "Data del préstec", optionalUnknown: "opcional / desconeguda", expectedReturnLabel: "Devolució prevista", privateOwnerNotes: "Notes privades de les persones propietàries",
  processingPhotoHelp: "Les fotografies grans del mòbil poden trigar uns segons. Mantén aquesta finestra oberta.", finishBatch: "Acaba el lot", cancel: "Cancel·la", pleaseWait: "Espera…", saveScanNext: "Desa i llegeix el següent", saveAddNext: "Desa i afegeix el següent", saveBook: "Desa el llibre", barcodeReadingLocally: "Llegint el codi de barres localment…", checkingSources: "Consultant fonts bibliogràfiques i aquesta biblioteca…", selectedCoverPreview: "Previsualització de la coberta seleccionada", loanReadingConflict: "Un exemplar no pot estar prestat i en lectura activa alhora.", processingCover: "Processant la coberta privada…", removingCover: "Eliminant la coberta privada…", savingGoodreads: "Desant la teva ressenya de Goodreads…", savingReadingHistory: "Desant el teu historial de lectura…", startingReading: "Iniciant la teva lectura…",
  partialSave: "El llibre compartit i la seva ubicació s'han desat, però han fallat algunes dades de la coberta privada o de la lectura personal. {error} Corregeix-les i torna-ho a provar: BOOKPILE actualitzarà aquest llibre en lloc de crear-ne un duplicat.", savedNext: "«{title}» desat. Tot a punt per al llibre següent.", bookSaved: "Llibre i coberta privada desats.", bookUpdated: "Llibre actualitzat.", deleteBookConfirm: "Vols eliminar definitivament «{title}»? Aquesta acció no es pot desfer.", bookDeleted: "Llibre eliminat definitivament.", personalDataUpdated: "Dades personals de lectura actualitzades.", loanDataUpdated: "Dades compartides del préstec actualitzades.",
} satisfies Record<CatalogueCopyKey, string>;
