import type { CatalogueCopyKey } from "../../catalogueCopy";

export const catalogueEu = {
  serverUnavailable: "BOOKPILE ezin izan da zerbitzarira konektatu. Saiatu berriro.", coverOf: "{title} liburuaren azala", shelf: "Apala", background: "Atzealdea", foreground: "Aurrealdea", row: "Ilara", pile: "Pila", position: "Kokapena", contributorRolesUnavailable: "Kolaboratzaile-rolak ez daude erabilgarri. Birkargatu orria eta saiatu berriro.",
  noSuggestedBooks: "Ez dago uneko katalogo-iragazkiekin bat datorren zain dagoen libururik.", privateCatalogue: "Katalogo pribatua", sharedCatalogue: "Katalogo partekatua", yourBooks: "Zure liburuak", usersBooks: "{username}(r)en liburuak", owner: "Jabea", viewer: "Ikuslea", memberCount: "{count} kide", book: "liburu", books: "liburu", match: "bat-etortze", newRead: "Irakurketa berria", add: "Gehitu", addSingleBook: "Gehitu liburu bat", batchAdd: "Sortaka gehitu", scanSingleBarcode: "Eskaneatu barra-kode bat", batchScan: "Sortaka eskaneatu", readingSuggestion: "Irakurketa-iradokizuna", another: "Beste bat", startReading: "Hasi irakurtzen", closeSuggestion: "Itxi iradokizuna", readingSummary: "Katalogoko irakurketen laburpena", totalBooks: "Liburuak guztira", waitingToRead: "Irakurtzeke", currentlyReading: "Irakurtzen", read: "Irakurrita",
  searchPlaceholder: "Bilatu izenburu, egile, kolaboratzaile edo sailaren arabera", searchCatalogue: "Bilatu katalogoan", sort: "Ordenatu", sortCatalogue: "Ordenatu katalogoa", advancedSort: "Ordenatze aurreratua", title: "Izenburua", author: "Egilea", physicalLocation: "Kokapen fisikoa", advanced: "Aurreratua", languages: "Hizkuntzak", originalLanguages: "Jatorrizko hizkuntzak", genres: "Generoak", publishers: "Argitaletxeak", series: "Sailak", translation: "Itzulpena", category: "Kategoria", binding: "Azaleztapena", publicationType: "Argitalpen mota", unknown: "Ezezaguna", original: "Jatorrizkoa", translated: "Itzulia", fiction: "Fikzioa", nonFiction: "Ez-fikzioa", hardcover: "Azal gogorra", paperback: "Azal biguna", flexibound: "Azal malgua", spiral: "Espirala", stapled: "Grapatua", other: "Beste bat", conventionalBook: "Ohiko liburua", comicGraphicNovel: "Komikia / eleberri grafikoa", atlas: "Atlasa", reference: "Erreferentzia-lana", artPhotographyIllustrated: "Artea / argazkigintza / ilustratua", magazinePeriodical: "Aldizkaria / periodikoa", seriesMembership: "Sail bateko kidetza", any: "Edozein", inSeries: "Sail batean", notInSeries: "Sailetik kanpo", authors: "Egileak", singleAuthor: "Egile bakarra", multipleAuthors: "Egile bat baino gehiago", minimumPages: "Gutxieneko orriak", maximumPages: "Gehieneko orriak", yearField: "Urtearen eremua", currentEdition: "Uneko edizioa", originalPublication: "Jatorrizko argitalpena", minimumYear: "Gutxieneko urtea", maximumYear: "Gehieneko urtea",
  personalReadingState: "Irakurketa-egoera pertsonala", pending: "Irakurtzeke", activeReading: "Irakurtzen — edozein irakurketa aktibo", firstReading: "Irakurtzen — lehen aldia", rereadingNow: "Berrirakurtzen", readInactive: "Irakurrita — irakurketa aktiborik ez", rereadingHistory: "Berrirakurketen historia", hasBeenReread: "Berrirakurri da", hasNotBeenReread: "Ez da berrirakurri", readingDate: "Irakurketa-data", readingStarted: "Irakurketa hasi", finishedReading: "Irakurketa amaitu", readingDateFrom: "Irakurketa-data hemendik", readingDateTo: "Irakurketa-data honaino",
  loanHistory: "Maileguen historia", currentlyOnLoan: "Une honetan mailegatuta", overdue: "Epez kanpo", everLoaned: "Noizbait mailegatua", neverLoaned: "Inoiz mailegatu gabe", borrowerContains: "Mailegu-hartzailearen izenak hau dauka", loanDate: "Mailegu-data", loaned: "Mailegatua", expectedReturn: "Aurreikusitako itzulera", returned: "Itzulia", loanDateFrom: "Mailegu-data hemendik", loanDateTo: "Mailegu-data honaino",
  sortBy: "Ordenatu honen arabera", dateAdded: "Gehitze-data", lastUpdated: "Azken eguneratzea", pages: "Orriak", publisher: "Argitaletxea", editionYear: "Edizioaren urtea", originalYear: "Jatorrizko urtea", acquisitionDate: "Eskuratze-data", loanedDate: "Mailegu-data", ascending: "Goranzkoa", descending: "Beheranzkoa", direction: "Noranzkoa", clear: "Garbitu", applyFilters: "Aplikatu iragazkiak",
  onLoanTo: "{borrower}-(r)i mailegatuta", onLoan: "Mailegatuta", returnsTo: "{location} kokapenera itzuliko da", beingRead: "Irakurtzen", noPhysicalLocation: "Kokapen fisikorik gabe", pageCount: "{count} orri", noOptionalMetadata: "Ez dago aukerako metadaturik gordeta", completeInformation: "Informazio osoa", goodreadsReview: "{username}(r)en Goodreadseko iritzia", myReading: "Nire irakurketa", manageLoan: "Kudeatu edo amaitu mailegua", loanBook: "Mailegatu liburu hau", editBookLocation: "Editatu liburua eta kokapen fisikoa", delete: "Ezabatu",
  everyBookPlace: "Liburu bakoitzarentzako tokia", buildPhysicalLibrary: "Eraiki zure liburutegi fisikoa", mapOnboarding: "BOOKPILEren mapak katalogoko erregistro bakoitza benetako kokapenarekin lotzen du. Aukerakoa da, baina altzariak, apalak eta ontziak orain zehazteak liburuak gehitzea eta aurkitzea askoz errazago egingo du.", setUpMap: "Konfiguratu liburutegiaren mapa", skipMap: "Urrats hau saltatu eta nahi duzunean liburuak zuzenean gehi ditzakezu.", noBooksMatch: "Ez dago bat datorren libururik", tryAnotherFilter: "Saiatu beste orri edo iragazki batekin.", noCatalogueRecords: "Liburutegi honek oraindik ez du katalogo-erregistrorik.", cataloguePages: "Katalogoaren orriak", previous: "Aurrekoa", next: "Hurrengoa", close: "Itxi", readOnlyRecord: "Irakurtzeko soilik den katalogo-erregistroa", contributors: "Kolaboratzaileak", selectedOwner: "Hautatutako jabea", notRecorded: "Erregistratu gabe",
  editBook: "Editatu liburua", subtitle: "Azpititulua", isbn10: "ISBN-10", isbn13: "ISBN-13", currentEditionYear: "Uneko edizioaren urtea", originalPublicationYear: "Jatorrizko argitalpen-urtea", language: "Hizkuntza", originalLanguage: "Jatorrizko hizkuntza", edition: "Edizioa", seriesVolume: "Saileko liburukia", acquired: "Eskuratua", originalCollection: "Jatorrizko bilduma", height: "Altuera", width: "Zabalera", thickness: "Lodiera", notes: "Oharrak", chooseTransferValues: "Aukeratu transferitu beharreko balioak", transferNoneAutomatic: "Ez da baliorik automatikoki hautatu edo gordetzen.", applyMetadata: "Aplikatu hautatutako metadatuak",
  batchCataloguing: "Sortakako katalogazioa", sharedRecord: "Katalogo-erregistro partekatua", addNextBook: "Gehitu hurrengo liburua", addBook: "Gehitu liburua", batchCountOne: "Liburu {count} gehitu da sorta honetan.", batchCountMany: "{count} liburu gehitu dira sorta honetan.", batchHelp: "Gorde ondoren, BOOKPILEk liburuaren datuak garbitzen ditu, baina ontzi hau mantendu eta hurrengo kokapena iradokitzen du.",
  identifyIsbn: "Identifikatu ISBN edo barra-kode bidez", barcodePrivacy: "Barra-kodearen argazkia gailu honetan deskodetu eta berehala ezabatzen da. Egiaztatu hornitzailearen balioak transferitu aurretik.", enterIsbn: "Idatzi edo eskaneatu lehenik ISBN bat.", lookingUp: "Bilatzen…", lookupIsbn: "Bilatu ISBN", readingPhoto: "Argazkia irakurtzen…", takeBarcodePhoto: "Atera barra-kodearen argazkia", isbnAlreadyPresent: "ISBN hau dagoeneko badago liburutegian", noBibliographicRecord: "Ez da erregistro bibliografikorik aurkitu. Eskuz jarrai dezakezu.",
  requiredInformation: "Nahitaezko informazioa", titleRequired: "Izenburua *", authorDisplayRequired: "Bistaratutako egilea *", privateCover: "Azal-irudi pribatua", coverPrivacy: "Liburutegi honetako saioa hasitako kideek bakarrik ikus dezakete. BOOKPILEk jatorrizkoa ezabatzen du metadatuak kendu eta WebP kopia pribatua sortu ondoren.", storedCover: "Gordetako azal pribatua", noCover: "Ez da azalik hautatu", chooseCover: "Atera edo aukeratu azalaren argazkia", removeCover: "Kendu azala", keepCover: "Mantendu uneko azala",
  contributorHelp: "Gehitu egileak, itzultzaileak, ilustratzaileak eta bestelako kreditatutako rolak agertzen diren ordenan.", contributorName: "Kolaboratzailearen izena", moveUp: "Igo", moveDown: "Jaitsi", removeContributor: "Kendu kolaboratzailea", addContributor: "Gehitu kolaboratzailea", editionClassification: "Edizioa eta sailkapena", editionNumber: "Edizio-zenbakia", commaSeparated: "Komaz bereizita", languageTranslation: "Hizkuntza eta itzulpena", translationStatus: "Itzulpen-egoera", originalLanguageValue: "Jatorrizko hizkuntza", identifiers: "Identifikatzaileak", copyDetails: "Alearen datuak",
  physicalLocationHelp: "Aukerakoa. Betetako kokapen batek automatikoki egiten du tokia; liburu bat mugitzean, aurreko ontziko tartea ixten da.", bookcase: "Altzaria", chooseShelf: "Aukeratu apala", container: "Ontzia", chooseContainer: "Aukeratu ontzia", libraryNotes: "Liburutegiaren oharrak", optional: "aukerakoa",
  initialReadingHelp: "Gehitu irakurketa-historia eta Goodreadseko iritzia erregistro partekatu hau sortzean. Balio horiek pertsonalak dira eta sortako hurrengo liburua baino lehen garbitzen dira.", readingRecord: "Irakurketa-historia", noReadingRecord: "Irakurketa-historiarik ez", historicalCompleted: "Irakurketa historikoa — amaituta", activeStarted: "Irakurketa aktiboa — hasita", readingDatesUnknown: "Irakurketa-datak ezezagunak", started: "Hasita", finished: "Amaituta", goodreadsUrl: "Nire Goodreadseko iritziaren URLa",
  currentLoan: "Uneko mailegua", copyCurrentlyLoaned: "Ale fisiko hau mailegatuta dago", retainedPositionHelp: "Apaleko kokapena erreserbatuta mantentzen da alea maileguen eremu partekatuan agertzen den bitartean.", loanedToRequired: "Nori mailegatua *", loanDateLabel: "Mailegu-data", optionalUnknown: "aukerakoa / ezezaguna", expectedReturnLabel: "Aurreikusitako itzulera", privateOwnerNotes: "Jabeen ohar pribatuak",
  processingPhotoHelp: "Telefonoko argazki handiak prozesatzeak segundo batzuk behar ditzake. Mantendu leihoa irekita.", finishBatch: "Amaitu sorta", cancel: "Utzi", pleaseWait: "Itxaron…", saveScanNext: "Gorde eta eskaneatu hurrengoa", saveAddNext: "Gorde eta gehitu hurrengoa", saveBook: "Gorde liburua", barcodeReadingLocally: "Barra-kodea lokalean irakurtzen…", checkingSources: "Iturri bibliografikoak eta liburutegi hau egiaztatzen…", selectedCoverPreview: "Hautatutako azalaren aurrebista", loanReadingConflict: "Ale bat ezin da aldi berean mailegatuta eta irakurtzen egon.", processingCover: "Azal pribatua prozesatzen…", removingCover: "Azal pribatua kentzen…", savingGoodreads: "Goodreadseko iritzia gordetzen…", savingReadingHistory: "Irakurketa-historia gordetzen…", startingReading: "Zure irakurketa hasten…",
  partialSave: "Liburu partekatua eta kokapena gorde dira, baina azal pribatuaren edo irakurketa pertsonalaren datu batzuek huts egin dute. {error} Zuzendu eta saiatu berriro: BOOKPILEk liburu hau eguneratuko du bikoiztua sortu beharrean.", savedNext: "«{title}» gorde da. Hurrengo libururako prest.", bookSaved: "Liburua eta azal pribatua gorde dira.", bookUpdated: "Liburua eguneratu da.", deleteBookConfirm: "Betiko ezabatu «{title}»? Ekintza hau ezin da desegin.", bookDeleted: "Liburua betiko ezabatu da.", personalDataUpdated: "Irakurketa-datu pertsonalak eguneratu dira.", loanDataUpdated: "Maileguaren datu partekatuak eguneratu dira.",
} satisfies Record<CatalogueCopyKey, string>;
