import type { CatalogueCopyKey } from "../../catalogueCopy";

export const catalogueOc = {
  serverUnavailable: "BOOKPILE non s'a pogut connectar ath servidor. Torna-ac a sajar.", coverOf: "Cobèrta de {title}", shelf: "Estatgèra", background: "Hons", foreground: "Dauant", row: "Hilèra", pile: "Pila", position: "Posicion", contributorRolesUnavailable: "Es ròtles des collaboradors non son disponibles. Torna a cargar era pagina.",
  noSuggestedBooks: "Cap libre pendent non coincidís damb es filtres actuaus deth catalòg.", privateCatalogue: "Catalòg privat", sharedCatalogue: "Catalòg compartit", yourBooks: "Es tòns libres", usersBooks: "Libres de {username}", owner: "Proprietari", viewer: "Visitant", memberCount: "{count} membres", book: "libre", books: "libres", match: "coincidéncia", newRead: "Lectura naua", add: "A híger", addSingleBook: "A híger un libre", batchAdd: "A híger en lòt", scanSingleBarcode: "Escanejar un còdi de barres", batchScan: "Escanejar en lòt", readingSuggestion: "Suggestion de lectura", another: "Ua auta", startReading: "Començar era lectura", closeSuggestion: "Barrar era suggestion", readingSummary: "Resumit de lectura deth catalòg", totalBooks: "Libres totaus", waitingToRead: "Pendent de liéger", currentlyReading: "En lectura", read: "Liejudi",
  searchPlaceholder: "Cercar per títol, autor, collaborador o seria", searchCatalogue: "Cercar en catalòg", sort: "Ordenar", sortCatalogue: "Ordenar eth catalòg", advancedSort: "Ordenacion avançada", title: "Títol", author: "Autor", physicalLocation: "Localizacion fisica", advanced: "Avançat", languages: "Lengües", originalLanguages: "Lengües originaus", genres: "Genres", publishers: "Editoraus", series: "Series", translation: "Traduccion", category: "Categoria", binding: "Enquadernacion", publicationType: "Tipe de publicacion", unknown: "Desconeishut", original: "Originau", translated: "Tradusit", fiction: "Ficcion", nonFiction: "Non-ficcion", hardcover: "Cobèrta dura", paperback: "Cobèrta mofla", flexibound: "Enquadernacion flexibla", spiral: "Espirau", stapled: "Grapat", other: "Un aute", conventionalBook: "Libre convencionau", comicGraphicNovel: "Benda dessenhada / novèlla grafica", atlas: "Atlas", reference: "Òbra de referéncia", artPhotographyIllustrated: "Art / fotografia / illustrat", magazinePeriodical: "Revista / periodic", seriesMembership: "Apartenença a ua seria", any: "Quinsevolh", inSeries: "En ua seria", notInSeries: "Dehòra de seria", authors: "Autors", singleAuthor: "Un solet autor", multipleAuthors: "Divèrsi autors", minimumPages: "Pagines minimes", maximumPages: "Pagines maximes", yearField: "Camp der an", currentEdition: "Edicion actuau", originalPublication: "Publicacion originau", minimumYear: "An minim", maximumYear: "An maxim",
  personalReadingState: "Estat personau de lectura", pending: "Pendent de liéger", activeReading: "En lectura — quinsevolh lectura activa", firstReading: "En lectura — prumèr còp", rereadingNow: "En relectura", readInactive: "Liejut — sense lectura activa", rereadingHistory: "Istòria de relectures", hasBeenReread: "S'a tornat a liéger", hasNotBeenReread: "Non s'a tornat a liéger", readingDate: "Data de lectura", readingStarted: "Lectura començada", finishedReading: "Lectura acabada", readingDateFrom: "Data de lectura des de", readingDateTo: "Data de lectura enquia",
  loanHistory: "Istòria de prèsti", currentlyOnLoan: "Actuaument en prèst", overdue: "Dehòra de tèrme", everLoaned: "Prestat bèth còp", neverLoaned: "Jamès prestat", borrowerContains: "Eth nòm deth prestatari conten", loanDate: "Data deth prèst", loaned: "Prestat", expectedReturn: "Retorn previst", returned: "Tornat", loanDateFrom: "Data deth prèst des de", loanDateTo: "Data deth prèst enquia",
  sortBy: "Ordenar per", dateAdded: "Data d'addicion", lastUpdated: "Darrèra actualizacion", pages: "Pagines", publisher: "Editorau", editionYear: "An dera edicion", originalYear: "An originau", acquisitionDate: "Data d'aquisicion", loanedDate: "Data deth prèst", ascending: "Ascendent", descending: "Descendent", direction: "Direccion", clear: "Netejar", applyFilters: "Aplicar es filtres",
  onLoanTo: "Prestat a {borrower}", onLoan: "En prèst", returnsTo: "torne a {location}", beingRead: "En lectura", noPhysicalLocation: "Sense localizacion fisica", pageCount: "{count} pagines", noOptionalMetadata: "Sense metadonades opcionaus sauves", completeInformation: "Informacion completa", goodreadsReview: "Opinion Goodreads de {username}", myReading: "Era mia lectura", manageLoan: "Gerir o acabar eth prèst", loanBook: "Prestar aguest libre", editBookLocation: "Editar eth libre e era localizacion fisica", delete: "Eliminar",
  everyBookPlace: "Un lòc entà cada libre", buildPhysicalLibrary: "Bastís era tua bibliotèca fisica", mapOnboarding: "Eth mapa de BOOKPILE connècte cada registre deth catalòg damb eth sòn lòc reau. Ei opcionau, mès definir ara es mòbles, estatgères e contenidors facilitarà fòrça a híger e trobar libres.", setUpMap: "Configurar eth mapa dera bibliotèca", skipMap: "Tanben pòs sautar aguest pas e a híger libres directament quan volgues.", noBooksMatch: "Cap libre non coincidís", tryAnotherFilter: "Saja ua auta pagina o filtre.", noCatalogueRecords: "Aguesta bibliotèca encara non a cap de registre de catalòg.", cataloguePages: "Pagines deth catalòg", previous: "Anterior", next: "Següenta", close: "Barrar", readOnlyRecord: "Registre de catalòg sonque de lectura", contributors: "Collaboradors", selectedOwner: "Proprietari seleccionat", notRecorded: "Non registrat",
  editBook: "Editar eth libre", subtitle: "Sostítol", isbn10: "ISBN-10", isbn13: "ISBN-13", currentEditionYear: "An dera edicion actuau", originalPublicationYear: "An dera publicacion originau", language: "Lengua", originalLanguage: "Lengua originau", edition: "Edicion", seriesVolume: "Volum dera seria", acquired: "Aquerit", originalCollection: "Colleccion originau", height: "Nautada", width: "Amplada", thickness: "Celh", notes: "Nòtes", chooseTransferValues: "Causir es valors a transferir", transferNoneAutomatic: "Cap valor se seleccione ne se sauve automaticament.", applyMetadata: "Aplicar es metadonades seleccionades",
  batchCataloguing: "Catalogacion en lòt", sharedRecord: "Registre de catalòg compartit", addNextBook: "A híger eth libre següent", addBook: "A híger un libre", batchCountOne: "S'a ahijut {count} libre pendent aguest lòt.", batchCountMany: "S'an ahijut {count} libres pendent aguest lòt.", batchHelp: "Dempús de sauvar, BOOKPILE escafe es donades deth libre, mès manten aguest contenidor e suggerís era posicion següenta.",
  identifyIsbn: "Identificar per ISBN o còdi de barres", barcodePrivacy: "Era fotografia deth còdi se descodifique en aguest dispositiu e s'elimine immediatament. Verifica es valors deth provedidor abans de transferir-les.", enterIsbn: "Escriu o escaneja prumèr un ISBN.", lookingUp: "En tot cercar…", lookupIsbn: "Cercar er ISBN", readingPhoto: "En tot liéger era fotografia…", takeBarcodePhoto: "Fotografiar eth còdi de barres", isbnAlreadyPresent: "Aguest ISBN ja existís ena bibliotèca", noBibliographicRecord: "Non s'a trobat cap de registre bibliografic. Pòs contunhar manuaument.",
  requiredInformation: "Informacion obligatòria", titleRequired: "Títol *", authorDisplayRequired: "Autor mostrat *", privateCover: "Imatge de cobèrta privada", coverPrivacy: "Sonque ei visibla entàs membres connectadi d'aguesta bibliotèca. BOOKPILE elimine er originau dempús de trèir es metadonades e crear ua còpia WebP privada.", storedCover: "Cobèrta privada sauva", noCover: "Cap cobèrta seleccionada", chooseCover: "Fotografiar o causir era cobèrta", removeCover: "Eliminar era cobèrta", keepCover: "Mantier era cobèrta actuau",
  contributorHelp: "Ahig autors, traductors, illustradors e auti ròtles acreditadi en orde de presentacion.", contributorName: "Nòm deth collaborator", moveUp: "Pujar", moveDown: "Baishar", removeContributor: "Eliminar eth collaborator", addContributor: "A híger un collaborator", editionClassification: "Edicion e classificacion", editionNumber: "Numèro dera edicion", commaSeparated: "Separadi per comes", languageTranslation: "Lengua e traduccion", translationStatus: "Estat dera traduccion", originalLanguageValue: "Lengua originau", identifiers: "Identificadors", copyDetails: "Donades der exemplar",
  physicalLocationHelp: "Opcionau. Ua posicion ocupada cree automaticament espaci; quan se desplace un libre, eth contenidor anterior se sarre.", bookcase: "Mòble", chooseShelf: "Causir ua estatgèra", container: "Contenidor", chooseContainer: "Causir un contenidor", libraryNotes: "Nòtes dera bibliotèca", optional: "opcionau",
  initialReadingHelp: "Ahig era tua istòria de lectura e opinion Goodreads quan crees aguest registre compartit. Aguesti valors son personaus e s'escafen abans deth següent libre deth lòt.", readingRecord: "Istòria de lectura", noReadingRecord: "Sense istòria de lectura", historicalCompleted: "Lectura istorica — acabada", activeStarted: "Lectura activa — començada", readingDatesUnknown: "Dates de lectura desconeishudes", started: "Començada", finished: "Acabada", goodreadsUrl: "URL dera mia opinion Goodreads",
  currentLoan: "Prèst actuau", copyCurrentlyLoaned: "Aguest exemplar fisic ei actuaument prestat", retainedPositionHelp: "Era posicion reservada ena estatgèra se manten mentre er exemplar apareish ena zòna compartida des prèsti.", loanedToRequired: "Prestat a *", loanDateLabel: "Data deth prèst", optionalUnknown: "opcionau / desconeishuda", expectedReturnLabel: "Retorn previst", privateOwnerNotes: "Nòtes privades des proprietaris",
  processingPhotoHelp: "Processar fotografies granes deth telefon pòt tardar quauqui segons. Manten aguesta hièstra dubèrta.", finishBatch: "Acabar eth lòt", cancel: "Anullar", pleaseWait: "Demora…", saveScanNext: "Sauvar e escanejar eth següent", saveAddNext: "Sauvar e a híger eth següent", saveBook: "Sauvar eth libre", barcodeReadingLocally: "En tot liéger eth còdi locaument…", checkingSources: "En tot consultar es hònts bibliografiques e aguesta bibliotèca…", selectedCoverPreview: "Previsualizacion dera cobèrta seleccionada", loanReadingConflict: "Un exemplar non pòt èster prestat e en lectura ath madeish temps.", processingCover: "En tot processar era cobèrta privada…", removingCover: "En tot eliminar era cobèrta privada…", savingGoodreads: "En tot sauvar era opinion Goodreads…", savingReadingHistory: "En tot sauvar era istòria de lectura…", startingReading: "En tot iniciar era tua lectura…",
  partialSave: "Eth libre compartit e era localizacion s'an sauvat, mès quauques donades dera cobèrta privada o lectura personau an falhat. {error} Corregís-les e torna-ac a sajar: BOOKPILE actualizarà aguest libre en lòc de crear-ne un duplicat.", savedNext: "«{title}» sauvat. Tot ei prèst entath libre següent.", bookSaved: "Libre e cobèrta privada sauvadi.", bookUpdated: "Libre actualizat.", deleteBookConfirm: "Eliminar definitivament «{title}»? Aguesta accion non se pòt des·hèr.", bookDeleted: "Libre eliminat definitivament.", personalDataUpdated: "Donades personaus de lectura actualizades.", loanDataUpdated: "Donades compartides deth prèst actualizades.",
} satisfies Record<CatalogueCopyKey, string>;
